<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#데이터-로드-및-결측치-제거" data-toc-modified-id="데이터-로드-및-결측치-제거-1">데이터 로드 및 결측치 제거</a></span></li><li><span><a href="#위도,-경도-변환할-도로명-주소-리스트-생성" data-toc-modified-id="위도,-경도-변환할-도로명-주소-리스트-생성-2">위도, 경도 변환할 도로명 주소 리스트 생성</a></span></li><li><span><a href="#카카오-API-활용---위도,-경도-변환" data-toc-modified-id="카카오-API-활용---위도,-경도-변환-3">카카오 API 활용 - 위도, 경도 변환</a></span></li></ul></div>

In [23]:
import requests
from urllib.parse import urlparse
import numpy as np
import pandas as pd
import geopandas

import warnings
warnings.filterwarnings(action='ignore')

## 데이터 로드 및 결측치 제거

In [2]:
data = pd.read_csv('data/단독다가구(전월세).csv')
data.head()

,시군구,번지,도로조건,계약면적(㎡),전월세구분,계약년월,계약일,보증금(만원),월세(만원),건축년도,도로명
0,서울특별시 강남구 개포동,1***,-,10.0,전세,201501,16,"9,500",0,1989.0,NaN
1,서울특별시 강남구 개포동,1***,-,15.0,월세,201504,4,200,35,1988.0,논현로6길
2,서울특별시 강남구 개포동,1***,-,15.0,월세,201506,9,500,30,1998.0,논현로18길
3,서울특별시 강남구 개포동,1***,-,15.0,월세,201507,27,500,40,1998.0,개포로20길
4,서울특별시 강남구 개포동,1**,8m미만,15.0,전세,201509,22,"3,000",0,1987.0,선릉로12길

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 762504 entries, 0 to 762503
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   시군구      762504 non-null  object
 1   번지       762421 non-null  object
 2   도로조건     762448 non-null  object
 3   계약면적(㎡)  762504 non-null  float64
 4   전월세구분    762504 non-null  object
 5   계약년월     762504 non-null  int64
 6   계약일      762504 non-null  int64
 7   보증금(만원)  762504 non-null  object
 8   월세(만원)   762504 non-null  object
 9   건축년도     726086 non-null  float64
 10  도로명      688663 non-null  object
dtypes: float64(2), int64(2), object(7)
memory usage: 64.0+ MB

In [6]:
data['도로명'].isnull().sum()

73841

In [11]:
data = data.dropna(subset=['도로명']).reset_index(drop=True)
data.head()

,시군구,번지,도로조건,계약면적(㎡),전월세구분,계약년월,계약일,보증금(만원),월세(만원),건축년도,도로명
0,서울특별시 강남구 개포동,1***,-,15.0,월세,201504,4,200,35,1988.0,논현로6길
1,서울특별시 강남구 개포동,1***,-,15.0,월세,201506,9,500,30,1998.0,논현로18길
2,서울특별시 강남구 개포동,1***,-,15.0,월세,201507,27,500,40,1998.0,개포로20길
3,서울특별시 강남구 개포동,1**,8m미만,15.0,전세,201509,22,"3,000",0,1987.0,선릉로12길
4,서울특별시 강남구 개포동,1**,8m미만,15.0,전세,201511,25,"3,000",0,1987.0,선릉로12길

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 688663 entries, 0 to 688662
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   시군구      688663 non-null  object
 1   번지       688663 non-null  object
 2   도로조건     688607 non-null  object
 3   계약면적(㎡)  688663 non-null  float64
 4   전월세구분    688663 non-null  object
 5   계약년월     688663 non-null  int64
 6   계약일      688663 non-null  int64
 7   보증금(만원)  688663 non-null  object
 8   월세(만원)   688663 non-null  object
 9   건축년도     657947 non-null  float64
 10  도로명      688663 non-null  object
dtypes: float64(2), int64(2), object(7)
memory usage: 57.8+ MB

## 위도, 경도 변환할 도로명 주소 리스트 생성

In [13]:
len(data['도로명'].unique())

12342

In [14]:
add_list = data['도로명'].unique().tolist()
add_list

['논현로6길',
 '논현로18길',
 '개포로20길',
 '선릉로12길',
 '논현로8길',
 '선릉로14길',
 '개포로15길',
 '논현로16길',
 '논현로4길',
 '논현로',
 '개포로17길',
 '논현로12길',
 '논현로10길',
 '논현로2길',
 '논현로20길',
 '개포로28길',
 '개포로24길',
 '개포로32길',
 '개포로22길',
 '개포로25길',
 '선릉로10길',
 '개포로36길',
 '개포로21길',
 '개포로',
 '언주로6길',
 '개포로31길',
 '선릉로8길',
 '논현로14길',
 '개포로34길',
 '선릉로16길',
 '선릉로18길',
 '개포로30길',
 '개포로26길',
 '선릉로6길',
 '강남대로118길',
 '봉은사로25길',
 '논현로124길',
 '봉은사로33길',
 '봉은사로11길',
 '논현로122길',
 '강남대로132길',
 '언주로122길',
 '강남대로126길',
 '학동로4길',
 '논현로136길',
 '선릉로125길',
 '학동로12길',
 '도산대로54길',
 '학동로2길',
 '강남대로120길',
 '강남대로150길',
 '선릉로137길',
 '강남대로122길',
 '봉은사로51길',
 '선릉로115길',
 '학동로42길',
 '선릉로129길',
 '학동로43길',
 '언주로149길',
 '학동로47길',
 '학동로18길',
 '봉은사로1길',
 '봉은사로7길',
 '언주로113길',
 '논현로126길',
 '강남대로128길',
 '강남대로116길',
 '강남대로124길',
 '학동로6길',
 '봉은사로29길',
 '강남대로114길',
 '언주로150길',
 '논현로142길',
 '선릉로141길',
 '논현로114길',
 '언주로147길',
 '학동로48길',
 '학동로41길',
 '선릉로127길',
 '논현로128길',
 '도산대로12길',
 '학동로30길',
 '논현로149길',
 '강남대로146길',
 '도산대로4길',
 '도산대로30길',
 '학동로24길',
 '논현로119길',
 '도산대로16길',
 '학동로26길',
 '논현로145길',
 '학동로33길',
 '학동로44길',
 '선릉로111길',
 '도산대로50길',
 '학동로19길',
 '논현로117길',
 '봉은사로37길',
 '봉은사로21길',
 '봉은사로47길',
 '논현로121길',
 '봉은사로13길',
 '논현로111길',
 '논현로131길',
 '선릉로135길',
 '학동로20길',
 '언주로141길',
 '언주로114길',
 '논현로115길',
 '논현로146길',
 '도산대로8길',
 '선릉로133길',
 '학동로31길',
 '논현로116길',
 '학동로38길',
 '논현로140길',
 '강남대로112길',
 '학동로21길',
 '논현로113길',
 '학동로8길',
 '학동로14길',
 '언주로124길',
 '언주로116길',
 '학동로34길',
 '강남대로136길',
 '선릉로121길',
 '언주로140길',
 '논현로123길',
 '학동로11길',
 '언주로135길',
 '선릉로145길',
 '학동로3길',
 '봉은사로49길',
 '학동로28길',
 '학동로53길',
 '선릉로119길',
 '논현로150길',
 '논현로133길',
 '언주로125길',
 '도산대로28길',
 '언주로136길',
 '봉은사로43길',
 '도산대로26길',
 '논현로132길',
 '도산대로34길',
 '언주로121길',
 '학동로5길',
 '학동로',
 '언주로115길',
 '논현로127길',
 '논현로134길',
 '논현로135길',
 '삼성로63길',
 '도곡로73길',
 '도곡로69길',
 '역삼로74길',
 '삼성로84길',
 '역삼로86길',
 '삼성로69길',
 '삼성로76길',
 '역삼로83길',
 '삼성로81길',
 '역삼로90길',
 '선릉로82길',
 '삼성로61길',
 '삼성로75길',
 '도곡로63길',
 '삼성로71길',
 '선릉로86길',
 '선릉로72길',
 '선릉로68길',
 '테헤란로68길',
 '선릉로64길',
 '역삼로70길',
 '역삼로84길',
 '역삼로64길',
 '역삼로63길',
 '역삼로77길',
 '선릉로66길',
 '역삼로88길',
 '도곡로93길',
 '역삼로81길',
 '역삼로',
 '역삼로78길',
 '역삼로71길',
 '역삼로65길',
 '역삼로87길',
 '테헤란로84길',
 '역삼로67길',
 '삼성로51길',
 '삼성로68길',
 '역삼로73길',
 '도곡로77길',
 '영동대로65길',
 '삼성로67길',
 '테헤란로70길',
 '선릉로76길',
 '역삼로69길',
 '역삼로92길',
 '선릉로62길',
 '삼성로57길',
 '삼성로72길',
 '삼성로64길',
 '삼성로70길',
 '논현로57길',
 '강남대로54길',
 '강남대로44길',
 '남부순환로375길',
 '남부순환로363길',
 '논현로38길',
 '양재천로',
 '도곡로18길',
 '논현로26길',
 '남부순환로381길',
 '남부순환로351길',
 '도곡로2길',
 '강남대로58길',
 '남부순환로365길',
 '논현로36길',
 '도곡로4길',
 '남부순환로370길',
 '남부순환로379길',
 '강남대로48길',
 '남부순환로359길',
 '언주로',
 '논현로24길',
 '남부순환로355길',
 '논현로34길',
 '도곡로14길',
 '도곡로',
 '선릉로112길',
 '봉은사로78길',
 '삼성로103길',
 '삼성로108길',
 '영동대로118길',
 '삼성로107길',
 '봉은사로74길',
 '봉은사로82길',
 '봉은사로63길',
 '선릉로116길',
 '봉은사로67길',
 '봉은사로57길',
 '선릉로120길',
 '테헤란로77길',
 '삼성로116길',
 '봉은사로72길',
 '봉은사로59길',
 '삼성로104길',
 '봉은사로105길',
 '학동로56길',
 '봉은사로68길',
 '선릉로108길',
 '봉은사로69길',
 '봉은사로84길',
 '봉은사로61길',
 '봉은사로73길',
 '테헤란로79길',
 '삼성로115길',
 '봉은사로71길',
 '영동대로116길',
 '봉은사로55길',
 '봉은사로111길',
 '테헤란로83길',
 '영동대로122길',
 '삼성로126길',
 '학동로82길',
 '선릉로126길',
 '봉은사로109길',
 '삼성로99길',
 '봉은사로70길',
 '삼성로120길',
 '선릉로96길',
 '테헤란로81길',
 '선릉로118길',
 '봉은사로97길',
 '봉은사로64길',
 '삼성로112길',
 '삼성로',
 '봉은사로',
 '삼성로119길',
 '선릉로122길',
 '헌릉로622길',
 '밤고개로34길',
 '헌릉로569길',
 '헌릉로571길',
 '헌릉로645길',
 '헌릉로618길',
 '밤고개로36길',
 '헌릉로637길',
 '밤고개로29길',
 '광평로',
 '광평로56길',
 '광평로42길',
 '광평로46길',
 '광평로31길',
 '선릉로157길',
 '언주로165길',
 '강남대로162길',
 '도산대로19길',
 '논현로151길',
 '논현로164길',
 '도산대로15길',
 '논현로153길',
 '논현로157길',
 '도산대로1길',
 '압구정로10길',
 '강남대로154길',
 '도산대로17길',
 '도산대로11길',
 '강남대로156길',
 '도산대로23길',
 '논현로159길',
 '논현로161길',
 '강남대로152길',
 '강남대로158길',
 '압구정로8길',
 '논현로160길',
 '논현로155길',
 '언주로159길',
 '압구정로4길',
 '강남대로160길',
 '도산대로13길',
 '논현로163길',
 '논현로152길',
 '언주로167길',
 '언주로172길',
 '압구정로14길',
 '압구정로2길',
 '논현로175길',
 '도산대로49길',
 '언주로153길',
 '논현로154길',
 '압구정로12길',
 '선릉로155길',
 '논현로168길',
 '논현로158길',
 '압구정로46길',
 '도산대로25길',
 '언주로173길',
 '압구정로34길',
 '도산대로37길',
 '도산대로35길',
 '압구정로30길',
 '언주로168길',
 '역삼로33길',
 '논현로66길',
 '테헤란로1길',
 '도곡로13길',
 '역삼로5길',
 '언주로93길',
 '언주로67길',
 '언주로69길',
 '테헤란로14길',
 '언주로63길',
 '역삼로34길',
 '논현로70길',
 '논현로68길',
 '봉은사로4길',
 '역삼로11길',
 '역삼로17길',
 '논현로63길',
 '역삼로12길',
 '논현로75길',
 '언주로65길',
 '테헤란로8길',
 '테헤란로16길',
 '논현로79길',
 '테헤란로4길',
 '선릉로69길',
 '역삼로18길',
 '역삼로14길',
 '언주로99길',
 '강남대로84길',
 '언주로97길',
 '봉은사로22길',
 '강남대로100길',
 '논현로65길',
 '논현로106길',
 '언주로104길',
 '도곡로5길',
 '도곡로3길',
 '역삼로20길',
 '테헤란로33길',
 '역삼로9길',
 '테헤란로22길',
 '언주로79길',
 '선릉로103길',
 '논현로64길',
 '도곡로37길',
 '도곡로57길',
 '테헤란로39길',
 '논현로71길',
 '역삼로19길',
 '봉은사로44길',
 '역삼로37길',
 '봉은사로38길',
 '언주로103길',
 '논현로76길',
 '강남대로94길',
 '봉은사로34길',
 '테헤란로19길',
 '테헤란로34길',
 '봉은사로18길',
 '봉은사로6길',
 '도곡로23길',
 '논현로102길',
 '테헤란로37길',
 '테헤란로57길',
 '도곡로17길',
 '테헤란로10길',
 '강남대로66길',
 '강남대로',
 '봉은사로48길',
 '도곡로33길',
 '언주로75길',
 '언주로98길',
 '테헤란로30길',
 '테헤란로51길',
 '테헤란로53길',
 '테헤란로38길',
 '봉은사로30길',
 '테헤란로13길',
 '테헤란로55길',
 '선릉로107길',
 '언주로70길',
 '강남대로78길',
 '언주로71길',
 '논현로74길',
 '테헤란로28길',
 '논현로105길',
 '봉은사로20길',
 '논현로80길',
 '도곡로7길',
 '언주로106길',
 '테헤란로5길',
 '봉은사로26길',
 '테헤란로43길',
 '논현로67길',
 '테헤란로6길',
 '도곡로27길',
 '언주로108길',
 '논현로97길',
 '도곡로11길',
 '논현로95길',
 '역삼로38길',
 '강남대로110길',
 '봉은사로24길',
 '역삼로15길',
 '도곡로25길',
 '봉은사로52길',
 '강남대로98길',
 '테헤란로32길',
 '언주로94길',
 '봉은사로50길',
 '언주로100길',
 '도곡로43길',
 '강남대로62길',
 '논현로72길',
 '언주로107길',
 '논현로94길',
 '역삼로25길',
 '언주로81길',
 '테헤란로21길',
 '역삼로10길',
 '논현로101길',
 '테헤란로',
 '역삼로26길',
 '봉은사로16길',
 '도곡로21길',
 '밤고개로24길',
 '밤고개로23길',
 '밤고개로27길',
 '개포로118길',
 '양재대로45길',
 '양재대로37길',
 '개포로124길',
 '양재대로47길',
 '양재대로51길',
 '일원로9길',
 '개포로128길',
 '개포로130길',
 '일원로',
 '양재대로53길',
 '양재대로27길',
 '양재대로49길',
 '일원로3길',
 '개포로138길',
 '양재대로39길',
 '일원로5길',
 '개포로136길',
 '양재대로31길',
 '양재대로35길',
 '개포로120길',
 '개포로116길',
 '양재대로41길',
 '양재대로33길',
 '양재대로43길',
 '광평로5길',
 '광평로3길',
 '개포로140길',
 '양재대로29길',
 '광평로1길',
 '광평로9길',
 '광평로7길',
 '자곡로7길',
 '밤고개로12길',
 '자곡로',
 '밤고개로14길',
 '선릉로158길',
 '선릉로132길',
 '도산대로66길',
 '삼성로144길',
 '삼성로146길',
 '도산대로98길',
 '도산대로78길',
 '삼성로149길',
 '삼성로147길',
 '도산대로62길',
 '삼성로135길',
 '영동대로',
 '도산대로100길',
 '도산대로94길',
 '선릉로148길',
 '도산대로87길',
 '삼성로140길',
 '학동로55길',
 '도산대로99길',
 '삼성로145길',
 '도산대로70길',
 '선릉로146길',
 '도산대로58길',
 '도산대로85길',
 '도산대로68길',
 '학동로59길',
 '압구정로79길',
 '압구정로75길',
 '학동로97길',
 '도산대로72길',
 '도산대로102길',
 '도산대로83길',
 '선릉로138길',
 '도산대로89길',
 '도산대로81길',
 '학동로77길',
 '상일로25길',
 '아리수로74길',
 '동남로87길',
 '고덕로83길',
 '아리수로64길',
 '동남로81길',
 '동남로83길',
 '동남로85길',
 '상일로21길',
 '상일로23길',
 '아리수로72길',
 '아리수로76길',
 '아리수로',
 '동남로82길',
 '아리수로82길',
 '상일로17길',
 '아리수로78길',
 '아리수로62길',
 '상일로19길',
 '고덕로61길',
 '상일로15길',
 '고덕로79길',
 '아리수로66길',
 '상일로',
 '아리수로61길',
 '아리수로68길',
 '천중로50길',
 '천중로53길',
 '양재대로110길',
 '진황도로49길',
 '천중로48길',
 '양재대로112길',
 '양재대로124길',
 '천호대로191길',
 '천중로54길',
 '양재대로116길',
 '천중로51길',
 '명일로',
 '천중로49길',
 '명일로17길',
 '천중로',
 '천호대로173길',
 '천중로40길',
 '진황도로47길',
 '천호대로187길',
 '양재대로115길',
 '명일로19길',
 '천호대로185길',
 '천중로42길',
 '천호대로189길',
 '명일로18길',
 '양재대로111길',
 '천중로52길',
 '양재대로126길',
 '명일로27길',
 '천중로55길',
 '양재대로128길',
 '성안로',
 '천중로49가길',
 '천호대로197길',
 '양재대로',
 '천호대로203길',
 '천호대로199길',
 '천호대로201길',
 '천중로44길',
 '양재대로114길',
 '명일로16길',
 '양재대로122길',
 '양재대로122가길',
 '천중로38가길',
 '천중로56길',
 '천호대로193길',
 '천중로38길',
 '양재대로117길',
 '천호대로177길',
 '풍성로65길',
 '진황도로61길',
 '동남로53길',
 '양재대로100길',
 '동남로49길',
 '양재대로96길',
 '풍성로61길',
 '명일로10길',
 '진황도로',
 '천호대로188길',
 '풍성로63길',
 '천호대로',
 '양재대로98길',
 '천호대로182길',
 '양재대로102길',
 '명일로10가길',
 '명일로13길',
 '천호대로186길',
 '동남로',
 '양재대로102가길',
 '천호대로200길',
 '풍성로73길',
 '명일로10나길',
 '풍성로67길',
 '상암로63길',
 '동남로65길',
 '상암로67길',
 '양재대로147길',
 '고덕로38길',
 '동남로67길',
 '상암로47길',
 '양재대로138길',
 '상암로',
 '동남로75길',
 '양재대로136길',
 '상암로51길',
 '구천면로',
 '구천면로65길',
 '양재대로134길',
 '양재대로143길',
 '상암로49길',
 '양재대로151길',
 '양재대로141길',
 '고덕로46길',
 '양재대로145길',
 '구천면로78길',
 '상암로61길',
 '상일로5길',
 '천호대로219가길',
 '천호대로219길',
 '구천면로100길',
 '상일로7길',
 '천호대로219나길',
 '상암로81길',
 '구천면로98길',
 '상암로79가길',
 '초광로294번길',
 '천호대로219다길',
 '상일로3길',
 '상일로12길',
 '천호대로213길',
 '천호대로221길',
 '상암로79길',
 '양재대로97길',
 '풍성로37가길',
 '천호대로168가길',
 '풍성로35길',
 '천호대로162가길',
 '올림픽로60길',
 '풍성로',
 '올림픽로58길',
 '천호대로168길',
 '양재대로89길',
 '천호옛길',
 '천호대로162길',
 '풍성로41길',
 '천호대로168다길',
 '올림픽로62길',
 '천호옛10길',
 '천호대로164길',
 '풍성로54길',
 '성안로13길',
 '천호대로168나길',
 '양재대로99길',
 '천호대로168라길',
 '강동대로55길',
 '양재대로103길',
 '양재대로87길',
 '양재대로91길',
 '양재대로95길',
 '풍성로57길',
 '천호옛14길',
 '천호대로158길',
 '양재대로85길',
 '천호옛8길',
 '성내로13길',
 '천호옛6길',
 '천호옛12길',
 '풍성로37길',
 '성내로3가길',
 '풍성로39길',
 '성안로3길',
 '풍성로45길',
 '천호대로176길',
 '천호대로174길',
 '천호대로170길',
 '양재대로101길',
 '풍성로55길',
 '풍성로42길',
 '양재대로91가길',
 '풍성로52길',
 '성내로6길',
 '성내로',
 '강동대로51길',
 '성안로9길',
 '풍성로58길',
 '성내로6다길',
 '풍성로53길',
 '양재대로91나길',
 '천호옛17길',
 '올림픽로',
 '성내로18길',
 '풍성로51길',
 '풍성로38길',
 '성내로17길',
 '강동대로53길',
 '성내로15길',
 '풍성로56길',
 '성안로7길',
 '양재대로89가길',
 '올림픽로54길',
 '성내로14길',
 '성내로5길',
 '성내로6가길',
 '양재대로83길',
 '성내로10길',
 '성내로3길',
 '성내로9길',
 '양재대로81길',
 '구천면로53길',
 '올림픽로112길',
 '상암로21길',
 '고덕로20가길',
 '구천면로57길',
 '고덕로25길',
 '암사18길',
 '구천면로47가길',
 '구천면로47길',
 '고덕로20다길',
 '올림픽로93길',
 '상암로17길',
 '상암로23길',
 '올림픽로100길',
 '암사11길',
 '상암로4가길',
 '고덕로14가길',
 '암사길',
 '암사1가길',
 '고덕로28길',
 '고덕로8길',
 '구천면로55길',
 '고덕로10길',
 '고덕로24나길',
 '상암로4길',
 '상암로6길',
 '고덕로20길',
 '고덕로20나길',
 '올림픽로98가길',
 '올림픽로91길',
 '올림픽로98길',
 '상암로5길',
 '고덕로16길',
 '고덕로',
 '고덕로14길',
 '고덕로24길',
 '상암로15길',
 '고덕로19길',
 '올림픽로107길',
 '암사13길',
 '고덕로3길',
 '구천면로59길',
 '구천면로53가길',
 '고덕로18길',
 '고덕로20라길',
 '구천면로47나길',
 '고덕로23길',
 '암사5길',
 '고덕로20마길',
 '고덕로1길',
 '고덕로24가길',
 '아리수로25길',
 '아리수로25나길',
 '아리수로25가길',
 '상암로11길',
 '암사1길',
 '고덕로27길',
 '상암로3길',
 '아리수로27길',
 '고덕로13길',
 '성안로27길',
 '올림픽로79길',
 '상암로35길',
 '성안로31길',
 '구천면로29길',
 '천중로29길',
 '구천면로68나길',
 '구천면로68가길',
 '상암로27가길',
 '양재대로123길',
 '구천면로42가길',
 '상암로28길',
 '선사로',
 '천중로18길',
 '올림픽로78길',
 '천중로27길',
 '구천면로18길',
 '천중로39길',
 '구천면로35길',
 '구천면로17길',
 '구천면로42길',
 '천중로35길',
 '성안로31나길',
 '천중로3길',
 '구천면로23길',
 '올림픽로76길',
 '성안로31가길',
 '구천면로68길',
 '구천면로34길',
 '진황도로29길',
 '구천면로33길',
 '성안로31다길',
 '구천면로36길',
 '구천면로16길',
 '성안로31라길',
 '상암로14길',
 '구천면로28길',
 '구천면로30길',
 '올림픽로80길',
 '천중로32길',
 '상암로27길',
 '천중로43길',
 '천중로30길',
 '상암로16길',
 '구천면로50길',
 '올림픽로89길',
 '올림픽로71길',
 '구천면로11길',
 '구천면로12길',
 '올림픽로70길',
 '천중로11길',
 '양재대로127길',
 '진황도로23길',
 '천중로21길',
 '양재대로125길',
 '진황도로27다길',
 '양재대로133길',
 '천중로17길',
 '천중로34길',
 '진황도로27길',
 '진황도로27라길',
 '천중로31길',
 '구천면로14길',
 '구천면로62길',
 '구천면로64길',
 '상암로27나길',
 '올림픽로72길',
 '선사로10길',
 '구천면로62가길',
 '올림픽로92길',
 '천호대로161길',
 '올림픽로77길',
 '상암로12길',
 '천중로35나길',
 '구천면로13길',
 '상암로41나길',
 '상암로41가길',
 '천호대로159길',
 '구천면로15길',
 '올림픽로81길',
 '구천면로46길',
 '구천면로39길',
 '상암로39길',
 '구천면로41길',
 '진황도로31길',
 '구천면로60길',
 '천중로33길',
 '천중로23길',
 '진황도로27가길',
 '천중로15길',
 '선사로6길',
 '천중로2길',
 '올림픽로87길',
 '천중로5길',
 '구천면로25길',
 '성안로31마길',
 '천중로16길',
 '양재대로121길',
 '양재대로135길',
 '천중로12길',
 '천중로15가길',
 '구천면로48길',
 '구천면로40길',
 '양재대로131가길',
 '천중로35가길',
 '진황도로33길',
 '올림픽로83길',
 '구천면로52길',
 '상암로41길',
 '천중로26길',
 '천호대로163길',
 '진황도로25길',
 '진황도로27나길',
 '천중로15나길',
 '구천면로21길',
 '올림픽로88길',
 '천중로14길',
 '천중로9길',
 '천호대로151길',
 '성안로25길',
 '양재대로131길',
 '솔매로46길',
 '월계로3가길',
 '월계로21다길',
 '숭인로7나길',
 '도봉로49길',
 '도봉로53길',
 '덕릉로30길',
 '도봉로78길',
 '삼양로57길',
 '솔매로',
 '도봉로21길',
 '삼양로24가길',
 '숭인로7길',
 '도봉로37길',
 '삼양로57가길',
 '도봉로63길',
 '도봉로76가길',
 '숭인로13길',
 '솔샘로60나길',
 '솔샘로64나길',
 '도봉로68길',
 '도봉로10라길',
 '삼양로28길',
 '도봉로23길',
 '솔샘로',
 '삼양로64가길',
 '오패산로35길',
 '오현로6길',
 '오현로10길',
 '월계로7나길',
 '오현로',
 '솔샘로35가길',
 '도봉로34길',
 '오패산로37길',
 '월계로7길',
 '도봉로27길',
 '도봉로36길',
 '도봉로65길',
 '도봉로8길',
 '솔매로41길',
 '도봉로29길',
 '솔샘로68길',
 '도봉로61길',
 '도봉로57길',
 '삼양로16길',
 '오현로9라길',
 '도봉로50길',
 '오패산로30길',
 '삼양로',
 '오패산로',
 '삼양로20길',
 '삼양로22길',
 '도봉로76길',
 '솔매로45길',
 '오패산로38길',
 '솔샘로67길',
 '솔매로54길',
 '오패산로31길',
 '도봉로28나길',
 '인수봉로6길',
 '삼양로54마길',
 ...]

## 카카오 API 활용 - 위도, 경도 변환

In [24]:
# 주소 검색 함수 정의
def address_to_latlon(address):
    url = "https://dapi.kakao.com/v2/local/search/address.json?&query=" + address
    result = requests.get(urlparse(url).geturl(),
                          headers={"Authorization":"KakaoAK *****"})
    json_obj = result.json()
    global val   # 전역 변수를 지역 범위에서 사용하고 싶을 경우
    for document in json_obj['documents']:
        # 값이 NoneType 일 경우의 오류 방지
        try:
            val = [document['address_name'], document['y'], document['x']]
        except:
            val = [0, 0, 0]
    return val

In [42]:
# 주소 검색 함수 적용
address_to_latlon('온수역')

['서울 구로구 온수동', '37.4941466665876', '126.820586087352']

In [18]:
# 주소 검색 함수 반복 적용
list1 = []
for i in add_list:
    list1.append(address_to_latlon(i))

In [19]:
data2 = pd.DataFrame(add_list, columns=['도로명'])
data2.head()

      도로명
0   논현로6길
1  논현로18길
2  개포로20길
3  선릉로12길
4   논현로8길

In [20]:
data3 = pd.DataFrame(list1, columns=['주소','위도','경도']).drop('주소', axis=1)
data3.head()

                 위도                경도
0  37.4735609971211  127.050895232485
1  37.4778848357129  127.046338152861
2   37.477039601042  127.048356001948
3  37.4838993527963  127.060991290466
4  37.4744673496263  127.051458050333

In [21]:
data4 = pd.concat([data2, data3], axis=1)
data4.head()

      도로명                위도                경도
0   논현로6길  37.4735609971211  127.050895232485
1  논현로18길  37.4778848357129  127.046338152861
2  개포로20길   37.477039601042  127.048356001948
3  선릉로12길  37.4838993527963  127.060991290466
4   논현로8길  37.4744673496263  127.051458050333

In [22]:
data4.to_csv('data/단독다가구_위도경도.csv', index=False)