<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#데이터-로드-및-결측치-제거" data-toc-modified-id="데이터-로드-및-결측치-제거-1">데이터 로드 및 결측치 제거</a></span></li><li><span><a href="#위도,-경도-변환할-도로명-주소-리스트-생성" data-toc-modified-id="위도,-경도-변환할-도로명-주소-리스트-생성-2">위도, 경도 변환할 도로명 주소 리스트 생성</a></span></li><li><span><a href="#카카오-API-활용---위도,-경도-변환" data-toc-modified-id="카카오-API-활용---위도,-경도-변환-3">카카오 API 활용 - 위도, 경도 변환</a></span></li></ul></div>

In [2]:
import requests
from urllib.parse import urlparse
import numpy as np
import pandas as pd
import geopandas

import warnings
warnings.filterwarnings(action='ignore')

## 데이터 로드 및 결측치 제거

In [2]:
data = pd.read_csv('data/연립(전월세).csv')
data.head()

,시군구,번지,본번,부번,건물명,전월세구분,전용면적(㎡),계약년월,계약일,보증금(만원),월세(만원),층,건축년도,도로명
0,서울특별시 강남구 개포동,1163-4,1163,4,(1163-4),월세,13.56,201910,26,"1,000",50,4.0,2013.0,논현로 10
1,서울특별시 강남구 개포동,1163-4,1163,4,(1163-4),전세,21.88,202002,27,"16,000",0,5.0,2013.0,논현로 10
2,서울특별시 강남구 개포동,1163-4,1163,4,(1163-4),월세,13.56,202007,9,"6,000",25,2.0,2013.0,논현로 10
3,서울특별시 강남구 개포동,1163-4,1163,4,(1163-4),월세,13.56,202007,17,"3,000",40,2.0,2013.0,논현로 10
4,서울특별시 강남구 개포동,1163-4,1163,4,(1163-4),월세,13.56,202008,5,"1,000",50,2.0,2013.0,논현로 10

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503838 entries, 0 to 503837
Data columns (total 14 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   시군구      503838 non-null  object
 1   번지       503825 non-null  object
 2   본번       503838 non-null  int64
 3   부번       503838 non-null  int64
 4   건물명      503833 non-null  object
 5   전월세구분    503838 non-null  object
 6   전용면적(㎡)  503838 non-null  float64
 7   계약년월     503838 non-null  int64
 8   계약일      503838 non-null  int64
 9   보증금(만원)  503838 non-null  object
 10  월세(만원)   503838 non-null  object
 11  층        500682 non-null  float64
 12  건축년도     503824 non-null  float64
 13  도로명      503838 non-null  object
dtypes: float64(3), int64(4), object(7)
memory usage: 53.8+ MB

In [7]:
data['도로명'].isnull().sum()

0

- 보증금(만원), 월세(만원), 도로명 컬럼에 결측치 없음. 그대로 진행.

## 위도, 경도 변환할 도로명 주소 리스트 생성

In [10]:
len(data['도로명'].unique())

82435

In [11]:
add_list = data['도로명'].unique().tolist()
add_list

['논현로 10',
 '논현로2길 66',
 '논현로8길 62-1',
 '논현로8길 63',
 '개포로26길 16',
 '논현로18길 18-5',
 '개포로21길 21',
 '개포로31길 15-4',
 '개포로31길 23-10',
 '선릉로8길 12',
 '선릉로6길 27',
 '선릉로10길 9',
 '선릉로12길 5',
 '선릉로12길 17',
 '선릉로14길 14',
 '언주로6길 9',
 '언주로6길 17-1',
 '언주로6길 19',
 '언주로6길 18',
 '언주로6길 24',
 '언주로6길 4',
 '논현로6길 18-8',
 '개포로32길 6',
 '개포로24길 32',
 '선릉로16길 14',
 '선릉로10길 16',
 '논현로12길 9-6',
 '논현로6길 30-6',
 '개포로17길 9-3',
 '논현로16길 10-6',
 '개포로22길 33',
 '논현로6길 10-14',
 '논현로20길 22',
 '논현로6길 4-11',
 '개포로15길 25',
 '개포로20길 35',
 '논현로12길 14',
 '언주로6길 21',
 '개포로28길 14',
 '선릉로4길 19',
 '논현로12길 23-6',
 '논현로2길 41',
 '개포로25길 27',
 '논현로2길 6',
 '개포로31길 23-3',
 '개포로31길 2-4',
 '개포로26길 28',
 '개포로21길 11',
 '선릉로14길 12',
 '논현로 78',
 '논현로6길 10-12',
 '개포로35길 11',
 '개포로31길 17',
 '논현로2길 59',
 '논현로20길 4-27',
 '논현로6길 18-10',
 '개포로30길 22',
 '개포로20길 21',
 '개포로20길 39',
 '개포로22길 39-6',
 '개포로21길 10',
 '개포로31길 29-2',
 '개포로21길 25',
 '논현로12길 9-7',
 '개포로21길 12',
 '논현로18길 10-4',
 '개포로31길 16',
 '논현로2길 9',
 '논현로8길 66-9',
 '논현로8길 46-5',
 '개포로31길 13',
 '논현로8길 39',
 '논현로8길 29',
 '개포로26길 22',
 '논현로6길 14-3',
 '개포로22길 45-15',
 '개포로25길 13-6',
 '개포로25길 17-8',
 '논현로4길 25',
 '개포로32길 21',
 '개포로31길 9-13',
 '개포로20길 57',
 '논현로16길 10-13',
 '개포로34길 18',
 '개포로17길 12',
 '개포로15길 28-4',
 '개포로22길 42',
 '개포로20길 45',
 '선릉로6길 20',
 '개포로28길 18',
 '개포로38길 16',
 '논현로6길 22-8',
 '개포로15길 3-15',
 '논현로6길 30',
 '개포로32길 10',
 '개포로31길 29-3',
 '논현로2길 63',
 '논현로2길 35',
 '개포로24길 23',
 '개포로31길 23-9',
 '논현로2길 15',
 '개포로20길 9',
 '개포로25길 21-3',
 '개포로22길 49-11',
 '논현로18길 10-18',
 '개포로17길 13-10',
 '개포로17길 9-7',
 '논현로16길 10-7',
 '논현로16길 10-5',
 '논현로4길 54',
 '개포로32길 14',
 '논현로16길 20-9',
 '개포로25길 28',
 '논현로18길 10-8',
 '개포로22길 49-7',
 '선릉로14길 20',
 '논현로8길 58-6',
 '개포로25길 17-9',
 '논현로10길 24',
 '논현로8길 58-5',
 '논현로2길 43',
 '개포로30길 24',
 '논현로8길 62-5',
 '개포로35길 15',
 '개포로32길 19',
 '개포로25길 13-9',
 '개포로25길 13-10',
 '논현로8길 54-7',
 '개포로36길 18',
 '논현로8길 46-7',
 '개포로31길 15-10',
 '논현로12길 23-8',
 '논현로2길 53',
 '선릉로6길 25',
 '개포로31길 29',
 '논현로2길 21',
 '논현로18길 14-18',
 '개포로25길 3-8',
 '개포로32길 13',
 '개포로34길 14',
 '개포로26길 25',
 '논현로8길 46-8',
 '개포로31길 19-6',
 '개포로15길 11',
 '개포로32길 16',
 '논현로8길 54-5',
 '개포로17길 9-4',
 '개포로34길 22',
 '선릉로10길 12',
 '선릉로10길 10-3',
 '선릉로10길 14-4',
 '개포로26길 27',
 '논현로16길 20-3',
 '선릉로8길 21',
 '개포로15길 32-3',
 '논현로6길 14-9',
 '개포로22길 45-9',
 '논현로2길 13',
 '논현로8길 62-4',
 '논현로8길 62-8',
 '개포로22길 18',
 '개포로17길 3-8',
 '개포로25길 23',
 '개포로25길 25',
 '개포로21길 28',
 '개포로20길 24-1',
 '논현로20길 4-1',
 '논현로20길 4-15',
 '개포로21길 6',
 '논현로18길 15',
 '논현로8길 58-8',
 '논현로12길 9-1',
 '논현로14길 5',
 '언주로6길 22',
 '개포로17길 16',
 '논현로6길 4-13',
 '개포로30길 7',
 '논현로20길 4-33',
 '논현로14길 14',
 '논현로8길 58-4',
 '개포로21길 27',
 '개포로17길 3-4',
 '선릉로10길 28',
 '논현로6길 22-5',
 '개포로22길 45-8',
 '개포로26길 18',
 '개포로30길 18',
 '논현로18길 14-10',
 '논현로16길 20-11',
 '논현로8길 45',
 '선릉로6길 29',
 '개포로22길 45-14',
 '논현로8길 23',
 '논현로4길 52',
 '논현로8길 54',
 '개포로22길 36',
 '개포로22길 76',
 '언주로6길 15',
 '개포로17길 13-11',
 '개포로20길 56',
 '개포로17길 25',
 '논현로16길 14-10',
 '논현로16길 10-9',
 '개포로24길 22',
 '논현로12길 23-9',
 '개포로28길 24-1',
 '논현로4길 27',
 '개포로32길 22',
 '논현로8길 66-5',
 '개포로26길 14',
 '논현로4길 13',
 '개포로25길 17-7',
 '개포로30길 12',
 '개포로36길 3',
 '논현로16길 20-5',
 '개포로21길 14',
 '개포로35길 13',
 '논현로16길 20-4',
 '개포로20길 53',
 '개포로22길 54',
 '언주로6길 4-3',
 '개포로21길 23',
 '개포로25길 9-7',
 '개포로20길 49',
 '선릉로8길 28',
 '개포로31길 29-5',
 '논현로6길 18-3',
 '개포로22길 106',
 '논현로18길 18-22',
 '개포로15길 3-13',
 '논현로12길 9-12',
 '개포로17길 9-10',
 '개포로25길 17-5',
 '논현로12길 3-4',
 '논현로12길 3-6',
 '개포로38길 24',
 '논현로8길 32-13',
 '논현로20길 4-34',
 '개포로31길 18',
 '논현로8길 32-12',
 '논현로8길 32-14',
 '논현로4길 49',
 '개포로31길 11',
 '개포로25길 17-3',
 '논현로6길 23',
 '개포로36길 9',
 '논현로6길 14-5',
 '개포로26길 24',
 '개포로31길 19-3',
 '논현로20길 4-23',
 '개포로34길 19',
 '언주로138길 14',
 '언주로136길 33',
 '학동로43길 26',
 '학동로53길 27',
 '도산대로12길 17-5',
 '학동로47길 13-5',
 '학동로47길 13-9',
 '학동로47길 13-8',
 '학동로28길 24',
 '학동로28길 26',
 '학동로20길 19-12',
 '학동로20길 30',
 '강남대로128길 60-2',
 '강남대로128길 66',
 '강남대로126길 65-3',
 '강남대로126길 65-1',
 '강남대로126길 55',
 '강남대로124길 67-1',
 '강남대로126길 56',
 '강남대로124길 47',
 '강남대로128길 44-7',
 '강남대로126길 21',
 '학동로18길 32-12',
 '학동로18길 32-16',
 '논현로123길 13-6',
 '논현로121길 29',
 '학동로18길 49',
 '학동로18길 51',
 '봉은사로21길 52',
 '학동로18길 50-11',
 '학동로26길 57',
 '학동로26길 53',
 '봉은사로21길 60',
 '봉은사로21길 58',
 '학동로26길 58',
 '강남대로122길 59',
 '강남대로122길 57',
 '강남대로122길 39-10',
 '도산대로4길 18-5',
 '강남대로146길 9',
 '강남대로120길 21',
 '봉은사로21길 49-6',
 '봉은사로11길 46',
 '논현로121길 51',
 '봉은사로11길 56',
 '봉은사로11길 54',
 '논현로117길 28',
 '봉은사로21길 31',
 '봉은사로21길 27',
 '강남대로116길 20',
 '강남대로120길 74',
 '논현로113길 40',
 '봉은사로25길 13-14',
 '논현로113길 21',
 '강남대로114길 26',
 '논현로128길 16-1',
 '논현로122길 25',
 '학동로38길 34-4',
 '학동로30길 37-14',
 '학동로30길 43-9',
 '학동로30길 43-1',
 '논현로120길 220-19',
 '논현로122길 14',
 '봉은사로37길 45-13',
 '봉은사로29길 24-9',
 '봉은사로29길 24-7',
 '논현로116길 18',
 '언주로113길 20',
 '선릉로127길 16',
 '학동로50길 12',
 '선릉로125길 26',
 '선릉로125길 24',
 '언주로126길 13',
 '봉은사로43길 39',
 '봉은사로51길 24',
 '봉은사로51길 22',
 '봉은사로47길 21',
 '언주로114길 29-10',
 '언주로114길 29-14',
 '언주로114길 29-13',
 '봉은사로43길 6-4',
 '강남대로136길 58',
 '도산대로24길 4',
 '도산대로30길 13-7',
 '도산대로34길 21-3',
 '언주로147길 33',
 '도산대로30길 29-6',
 '도산대로34길 28',
 '논현로149길 17-6',
 '선릉로137길 18-7',
 '학동로14길 22',
 '학동로26길 39',
 '강남대로124길 20',
 '논현로117길 16',
 '논현로119길 17-4',
 '강남대로114길 41',
 '봉은사로49길 37-7',
 '봉은사로7길 48',
 '논현로123길 13-4',
 '봉은사로1길 42-28',
 '언주로147길 29-7',
 '논현로111길 21',
 '학동로42길 67-7',
 '논현로118길 27',
 '강남대로126길 25',
 '봉은사로25길 36-1',
 '학동로26길 64',
 '도산대로38길 52',
 '학동로31길 32',
 '논현로146길 38',
 '봉은사로47길 23',
 '강남대로132길 57',
 '봉은사로43길 49',
 '강남대로146길 8-9',
 '학동로25길 17',
 '논현로123길 31-1',
 '봉은사로49길 21-9',
 '논현로146길 39',
 '논현로111길 42',
 '학동로8길 7-6',
 '논현로119길 40',
 '강남대로136길 55',
 '학동로26길 16-1',
 '언주로140길 24',
 '학동로28길 21',
 '도산대로8길 20-9',
 '봉은사로49길 13',
 '선릉로111길 27',
 '논현로115길 41',
 '학동로20길 25-8',
 '논현로150길 42',
 '강남대로120길 27',
 '선릉로115길 23',
 '봉은사로11길 37',
 '학동로3길 28',
 '학동로33길 34',
 '봉은사로37길 45-8',
 '언주로136길 30',
 '논현로115길 48',
 '선릉로119길 33',
 '선릉로119길 35',
 '논현로123길 50',
 '강남대로132길 27',
 '강남대로126길 27',
 '학동로42길 36',
 '학동로42길 38',
 '논현로117길 15',
 '논현로117길 24',
 '봉은사로51길 20-1',
 '봉은사로49길 26',
 '언주로124길 28',
 '선릉로135길 15',
 '강남대로116길 11',
 '강남대로120길 20',
 '논현로145길 38',
 '강남대로114길 33',
 '강남대로124길 48-4',
 '선릉로127길 5-6',
 '학동로18길 18',
 '봉은사로11길 62',
 '강남대로118길 66',
 '강남대로118길 73',
 '학동로44길 36',
 '논현로121길 58',
 '언주로136길 32',
 '논현로131길 10-4',
 '강남대로126길 42',
 '강남대로126길 68',
 '강남대로116길 35',
 '학동로3길 35',
 '학동로30길 49',
 '봉은사로37길 49',
 '언주로114길 15-7',
 '학동로11길 18',
 '학동로33길 39',
 '논현로115길 53',
 '학동로19길 34',
 '학동로42길 45',
 '학동로4길 43-8',
 '선릉로111길 38-17',
 '학동로3길 6',
 '학동로6길 6-13',
 '강남대로122길 29-1',
 '강남대로122길 29-6',
 '학동로18길 67',
 '학동로21길 48',
 '도산대로38길 56',
 '선릉로125길 27',
 '도산대로38길 60',
 '도산대로26길 34-11',
 '논현로119길 31',
 '강남대로126길 46',
 '도산대로8길 17-7',
 '봉은사로51길 48',
 '강남대로136길 31',
 '봉은사로49길 42-1',
 '봉은사로51길 43',
 '논현로123길 54',
 '선릉로133길 20',
 '선릉로125길 22',
 '논현로121길 41',
 '도산대로38길 58',
 '도산대로54길 48-11',
 '봉은사로37길 21',
 '봉은사로37길 23',
 '논현로115길 18-6',
 '강남대로146길 8-7',
 '논현로139길 7',
 '학동로18길 64',
 '논현로111길 16-3',
 '학동로4길 15',
 '도산대로54길 41',
 '봉은사로49길 19-6',
 '학동로50길 6',
 '언주로147길 29',
 '봉은사로37길 29',
 '논현로111길 38',
 '학동로5길 21',
 '논현로123길 52-5',
 '도산대로12길 17-11',
 '선릉로135길 13-3',
 '논현로115길 67',
 '언주로141길 34',
 '학동로11길 23',
 '학동로18길 9',
 '언주로138길 13',
 '강남대로114길 30',
 '논현로120길 16-1',
 '봉은사로37길 24-1',
 '학동로26길 55',
 '논현로119길 33',
 '강남대로120길 73',
 '학동로25길 27',
 '강남대로120길 56',
 '언주로135길 32-5',
 '논현로123길 44',
 '봉은사로29길 24-1',
 '봉은사로29길 24-8',
 '논현로115길 4-2',
 '학동로18길 32-8',
 '논현로117길 22',
 '논현로117길 20',
 '논현로119길 20-5',
 '강남대로124길 27',
 '논현로111길 20-4',
 '선릉로141길 3-4',
 '논현로124길 19-5',
 '학동로5길 23',
 '언주로147길 50',
 '언주로147길 51',
 '논현로111길 46',
 '봉은사로49길 21-10',
 '학동로44길 43-4',
 '논현로140길 13',
 '봉은사로25길 68',
 '논현로114길 19',
 '봉은사로51길 30',
 '봉은사로51길 32',
 '학동로46길 43',
 '학동로12길 6-8',
 '논현로115길 28',
 '도산대로50길 31',
 '도산대로16길 13-7',
 '도산대로54길 56',
 '선릉로137길 14-8',
 '선릉로135길 21',
 '학동로26길 41',
 '강남대로116길 27',
 '논현로115길 23',
 '논현로145길 32',
 '봉은사로29길 24-12',
 '논현로115길 18',
 '강남대로120길 17',
 '학동로30길 43-13',
 '학동로30길 37-15',
 '학동로25길 23',
 '학동로11길 20-6',
 '봉은사로37길 47-6',
 '도산대로16길 13-5',
 '학동로18길 47',
 '학동로18길 43',
 '논현로121길 14',
 '학동로28길 19-2',
 '학동로9길 31',
 '언주로141길 29',
 '선릉로111길 38-15',
 '언주로114길 15-9',
 '학동로30길 37-13',
 '강남대로124길 57',
 '강남대로114길 48',
 '언주로122길 18',
 '강남대로122길 29-9',
 '논현로115길 4-1',
 '학동로23길 19',
 '학동로30길 43-8',
 '학동로42길 48',
 '학동로26길 52',
 '학동로12길 18',
 '학동로3길 25',
 '학동로47길 13-6',
 '봉은사로47길 16',
 '논현로118길 17-2',
 '강남대로120길 70',
 '봉은사로25길 13-8',
 '학동로47길 24',
 '학동로5길 16',
 '봉은사로21길 32',
 '선릉로137길 18-6',
 '언주로124길 43',
 '강남대로118길 34',
 '논현로149길 17',
 '학동로4길 43-9',
 '언주로136길 31',
 '도산대로34길 13',
 '강남대로116길 17',
 '논현로123길 34',
 '봉은사로33길 37',
 '봉은사로21길 57-15',
 '봉은사로33길 17',
 '언주로114길 15-12',
 '도산대로 126-8',
 '논현로119길 45',
 '논현로114길 15',
 '강남대로122길 29-11',
 '강남대로128길 44-8',
 '학동로18길 32-9',
 '강남대로124길 64',
 '봉은사로11길 63',
 '강남대로120길 16',
 '강남대로114길 28',
 '학동로4길 30',
 '도산대로30길 29-14',
 '논현로127길 13-6',
 '논현로136길 22',
 '선릉로121길 59',
 '학동로18길 32-4',
 '강남대로120길 24',
 '강남대로136길 34',
 '강남대로146길 15',
 '선릉로121길 61',
 '봉은사로37길 7-6',
 '논현로142길 33',
 '선릉로111길 22-8',
 '강남대로126길 22',
 '학동로42길 67-11',
 '봉은사로37길 8',
 '학동로12길 23',
 '선릉로133길 15',
 '논현로123길 13-5',
 '학동로20길 25-9',
 '봉은사로11길 61',
 '논현로126길 21',
 '도산대로4길 12',
 '강남대로124길 54',
 '선릉로115길 3',
 '봉은사로51길 26',
 '선릉로145길 5-8',
 '언주로113길 13-1',
 '학동로18길 50-3',
 '학동로28길 15',
 '논현로116길 20',
 '선릉로115길 31',
 '선릉로115길 29',
 '학동로23길 37',
 '학동로23길 59',
 '강남대로116길 33',
 '선릉로137길 14-4',
 '논현로115길 19',
 '논현로115길 21',
 '논현로115길 18-8',
 '봉은사로43길 21-1',
 '선릉로119길 7',
 '학동로20길 25-6',
 '선릉로127길 13',
 '학동로30길 37-20',
 '학동로30길 37-18',
 '선릉로141길 3-6',
 '강남대로124길 68-1',
 '논현로113길 38',
 '강남대로120길 70-2',
 '도산대로54길 55',
 '논현로128길 24-1',
 '학동로14길 23',
 '강남대로128길 63',
 '학동로21길 15',
 '학동로28길 22',
 '언주로121길 15',
 '논현로140길 29',
 '학동로33길 35',
 '학동로48길 13',
 '언주로124길 30',
 '봉은사로51길 47',
 '봉은사로51길 47-5',
 '봉은사로49길 19',
 '학동로30길 43-16',
 '학동로44길 45',
 '언주로 121-17',
 '학동로50길 15',
 '학동로44길 47-5',
 '언주로114길 29-11',
 '도산대로8길 17-15',
 '강남대로124길 66',
 '논현로121길 59',
 '봉은사로11길 39',
 '강남대로122길 24',
 '강남대로120길 55',
 '학동로47길 13-4',
 '선릉로111길 34',
 '논현로116길 24',
 '학동로26길 63',
 '도산대로28길 47',
 '봉은사로37길 47-14',
 '언주로148길 8',
 '논현로126길 13',
 '강남대로116길 32',
 '논현로116길 13',
 '학동로18길 50-9',
 '논현로123길 49',
 '논현로140길 11',
 '강남대로136길 60',
 '학동로12길 9',
 '논현로115길 47',
 '선릉로115길 5',
 '강남대로120길 26',
 '논현로113길 43',
 '논현로111길 16-6',
 '강남대로128길 64-2',
 '도산대로12길 17-9',
 '논현로120길 16-3',
 '선릉로141길 13-1',
 '언주로136길 15-3',
 '강남대로114길 46',
 '학동로18길 38',
 '강남대로122길 30-4',
 '강남대로128길 64-1',
 '논현로146길 35',
 '논현로117길 30',
 '강남대로126길 26-5',
 '도산대로12길 20',
 '학동로23길 50',
 '학동로28길 19-4',
 '언주로141길 36',
 '논현로115길 40',
 '도산대로8길 20-7',
 '삼성로51길 10-8',
 '삼성로81길 28',
 '삼성로81길 40',
 '역삼로67길 33',
 '테헤란로68길 26',
 '선릉로82길 43',
 '선릉로86길 44-3',
 '선릉로82길 45',
 '선릉로76길 5-4',
 '선릉로76길 5-9',
 '역삼로67길 19',
 '역삼로67길 20',
 '역삼로67길 14',
 '테헤란로68길 46',
 '선릉로82길 40-4',
 '역삼로69길 23',
 '역삼로69길 15',
 '역삼로69길 28',
 '삼성로75길 40-5',
 '삼성로75길 40-12',
 '역삼로73길 15',
 '역삼로73길 19',
 '역삼로73길 18',
 '역삼로73길 16',
 '삼성로75길 32-14',
 '삼성로75길 32-4',
 '역삼로69길 20',
 '삼성로75길 28',
 '삼성로75길 31',
 '역삼로 433-1',
 '역삼로67길 6',
 '선릉로72길 15',
 '역삼로 408',
 '삼성로71길 38',
 '삼성로71길 26',
 '역삼로78길 1',
 '역삼로78길 5-1',
 '삼성로69길 5',
 '삼성로67길 8-8',
 '삼성로69길 14',
 '삼성로69길 19',
 '삼성로69길 46',
 '삼성로69길 44',
 '삼성로69길 38',
 '삼성로69길 29-3',
 '삼성로67길 28',
 '삼성로67길 30',
 '삼성로69길 35',
 '삼성로69길 39-1',
 '삼성로69길 43-3',
 '삼성로69길 47-4',
 '삼성로67길 52',
 '삼성로69길 29-5',
 '삼성로69길 29-1',
 '삼성로71길 27-6',
 '역삼로70길 19-5',
 '선릉로72길 26-16',
 '선릉로72길 26-7',
 '선릉로68길 27',
 '역삼로64길 16-4',
 '역삼로64길 16-2',
 '역삼로64길 16-3',
 '도곡로69길 30-2',
 '삼성로63길 48-43',
 '삼성로63길 48-25',
 '삼성로67길 47',
 '삼성로67길 45',
 '삼성로63길 48-36',
 '삼성로63길 48-30',
 '삼성로63길 48-28',
 '도곡로73길 27-2',
 '삼성로63길 48-26',
 '삼성로63길 44',
 '도곡로73길 21',
 '도곡로73길 35',
 '삼성로63길 48-38',
 '삼성로67길 37',
 '삼성로63길 38',
 '삼성로63길 36-6',
 '도곡로77길 27-4',
 '도곡로77길 27-3',
 '삼성로67길 27-1',
 '삼성로67길 21',
 '삼성로63길 16-9',
 '삼성로63길 16-6',
 '삼성로63길 16-16',
 '삼성로63길 4-11',
 '삼성로61길 14',
 '삼성로63길 11',
 '삼성로63길 7-6',
 '삼성로63길 7',
 '삼성로61길 18',
 '삼성로61길 26',
 '도곡로69길 14',
 '삼성로63길 49',
 '선릉로64길 10-4',
 '삼성로61길 51',
 '테헤란로92길 45',
 '삼성로76길 26-1',
 '삼성로82길 30',
 '역삼로87길 19',
 '삼성로76길 23-12',
 '역삼로87길 25',
 '역삼로87길 13-1',
 '삼성로76길 23-20',
 '삼성로76길 23-18',
 '삼성로76길 23-11',
 '삼성로76길 23-7',
 '역삼로83길 12-3',
 '역삼로83길 22-1',
 '역삼로83길 22',
 '삼성로84길 8',
 '역삼로81길 22-1',
 '역삼로81길 27',
 '삼성로76길 5-8',
 '삼성로76길 5-6',
 '삼성로76길 16',
 '역삼로84길 26',
 '역삼로90길 17',
 '도곡로83길 14',
 '역삼로90길 36',
 '삼성로62길 21',
 '역삼로69길 25-1',
 '삼성로67길 34',
 '삼성로67길 17',
 '삼성로84길 5',
 '삼성로62길 23',
 '삼성로67길 6',
 '선릉로82길 40-14',
 '삼성로61길 48',
 '선릉로64길 15-12',
 '선릉로86길 40-4',
 '역삼로67길 23',
 '역삼로67길 31',
 '선릉로82길 42',
 '테헤란로68길 45',
 '삼성로75길 27-1',
 '삼성로67길 48',
 '선릉로72길 10-9',
 '영동대로71길 18',
 '선릉로72길 43',
 '도곡로99길 8',
 '역삼로87길 15',
 '역삼로78길 26',
 '삼성로67길 25',
 '삼성로63길 48-14',
 '도곡로77길 31',
 '삼성로76길 23-13',
 '역삼로74길 14',
 '선릉로66길 5',
 '삼성로61길 32',
 '삼성로61길 36',
 '삼성로63길 48-41',
 '선릉로76길 9-11',
 '역삼로90길 30',
 '역삼로70길 23',
 '역삼로90길 34',
 '삼성로75길 32-3',
 '선릉로76길 9-18',
 '테헤란로68길 42',
 '삼성로63길 32-6',
 '영동대로71길 38',
 '역삼로87길 21',
 '삼성로76길 23-8',
 '삼성로69길 7',
 '삼성로63길 52',
 '삼성로69길 27',
 '삼성로69길 20',
 '역삼로70길 26',
 '역삼로74길 5-3',
 '삼성로71길 36',
 '삼성로63길 48-37',
 '삼성로63길 48-39',
 '삼성로63길 48-16',
 '도곡로77길 27',
 '삼성로75길 51',
 '삼성로69길 29-4',
 '선릉로76길 33',
 '삼성로63길 16-8',
 '역삼로65길 32',
 '삼성로64길 28',
 '선릉로72길 10-13',
 '역삼로65길 34',
 '삼성로67길 7',
 '삼성로69길 18',
 '삼성로76길 5-3',
 '역삼로74길 20',
 '역삼로83길 18',
 '삼성로67길 20-1',
 '삼성로61길 28',
 '역삼로87길 17',
 '삼성로61길 17',
 '삼성로57길 42',
 '역삼로64길 5',
 '삼성로75길 32-10',
 '테헤란로68길 40',
 '삼성로69길 25',
 '역삼로70길 19-10',
 '역삼로77길 7',
 '삼성로69길 33',
 '선릉로62길 39',
 '선릉로72길 6-11',
 '삼성로69길 10',
 '역삼로71길 6',
 '삼성로67길 13',
 '삼성로63길 49-5',
 '역삼로71길 7',
 '삼성로61길 46',
 '삼성로63길 48-46',
 '삼성로63길 32',
 '역삼로71길 17',
 '삼성로75길 26-4',
 '역삼로88길 9-10',
 '영동대로85길 17-10',
 '선릉로82길 29',
 '선릉로72길 38',
 '영동대로71길 14',
 '영동대로65길 44',
 '삼성로63길 33',
 '역삼로74길 24-1',
 '선릉로86길 44-5',
 '삼성로61길 4',
 '역삼로67길 15',
 '삼성로75길 40-9',
 '삼성로75길 40-3',
 '역삼로74길 21',
 '삼성로75길 29',
 '역삼로67길 16',
 '역삼로67길 11',
 '역삼로 455-5',
 '삼성로63길 48-18',
 '역삼로74길 27',
 '삼성로63길 12-12',
 '역삼로74길 13',
 '삼성로76길 26-3',
 '삼성로67길 19',
 '삼성로63길 51',
 '삼성로63길 43',
 '선릉로72길 39',
 '삼성로67길 53',
 '도곡로 425',
 '삼성로63길 32-4',
 '역삼로73길 24',
 '역삼로70길 5',
 '역삼로70길 20',
 '도곡로77길 30',
 '삼성로63길 11-6',
 '삼성로84길 9',
 '삼성로57길 46',
 '삼성로57길 48',
 '역삼로74길 17',
 '삼성로 414',
 '삼성로63길 19',
 '삼성로61길 34',
 '삼성로63길 8',
 '삼성로71길 33-5',
 '역삼로70길 21',
 '역삼로70길 24',
 '역삼로67길 26',
 '선릉로76길 9-7',
 '삼성로63길 32-22',
 '역삼로83길 16-1',
 '삼성로84길 12',
 '삼성로71길 43-5',
 '삼성로67길 27',
 '역삼로81길 18-1',
 '삼성로67길 49',
 '선릉로76길 5-14',
 '삼성로82길 22',
 '선릉로72길 40',
 '삼성로63길 16-11',
 '역삼로87길 3',
 '삼성로71길 27-4',
 '삼성로75길 32-7',
 '삼성로63길 16-21',
 '선릉로68길 37',
 '선릉로82길 40-6',
 '삼성로71길 35',
 '삼성로69길 45',
 '역삼로69길 17',
 '선릉로82길 20',
 '역삼로67길 25',
 '역삼로 433-5',
 '선릉로76길 5-7',
 '역삼로71길 5',
 '선릉로76길 9-14',
 '삼성로67길 38',
 '선릉로76길 5-12',
 '역삼로74길 26',
 '삼성로67길 29',
 '역삼로77길 21',
 '삼성로76길 23-4',
 '삼성로69길 17',
 '선릉로82길 40',
 '삼성로67길 42',
 '선릉로82길 40-12',
 '역삼로64길 23',
 '선릉로82길 40-8',
 '선릉로66길 5-1',
 '선릉로64길 10-3',
 '삼성로63길 11-3',
 '삼성로75길 26-14',
 '삼성로75길 32',
 '선릉로64길 32',
 '역삼로81길 13',
 ...]

## 카카오 API 활용 - 위도, 경도 변환

In [12]:
# 주소 검색 함수 정의
def address_to_latlon(address):
    url = "https://dapi.kakao.com/v2/local/search/address.json?&query=" + address
    result = requests.get(urlparse(url).geturl(),
                          headers={"Authorization":"KakaoAK *****"})
    json_obj = result.json()
    global val   # 전역 변수를 지역 범위에서 사용하고 싶을 경우
    for document in json_obj['documents']:
        # 값이 NoneType 일 경우의 오류 방지
        try:
            val = [document['y'], document['x']]
        except:
            val = [0, 0]
    return val

In [13]:
# 주소 검색 함수 적용
address_to_latlon('논현로 10')

['37.4723876864126', '127.050510865064']

In [14]:
# 주소 검색 함수 반복 적용
list1 = []
for i in add_list:
    list1.append(address_to_latlon(i))

KeyError: 'documents'

In [16]:
# API 쿼터 제한으로 오류 중단 -> 일단 데이터프레임으로 저장
print(len(list1))
list1

77040

[['37.4723876864126', '127.050510865064'],
 ['37.4745435620733', '127.055084221135'],
 ['37.4745435620733', '127.055084221135'],
 ['37.4753126502908', '127.053546142443'],
 ['37.4780340050176', '127.049108807588'],
 ['37.4777378645956', '127.046836978486'],
 ['37.4802050095945', '127.047060115492'],
 ['37.4801003654455', '127.048925759622'],
 ['37.4806143931064', '127.048263673953'],
 ['37.482947218924', '127.061758559555'],
 ['37.483589457892', '127.062784134247'],
 ['37.4834343639804', '127.060774393715'],
 ['37.4836275657618', '127.060373056666'],
 ['37.4840120774258', '127.060974874536'],
 ['37.4839570800511', '127.060694540667'],
 ['37.4779821530499', '127.058322306639'],
 ['37.4775660746296', '127.058851875778'],
 ['37.4774220072314', '127.058662620825'],
 ['37.4775421964326', '127.058491887528'],
 ['37.4773156510839', '127.058190870503'],
 ['37.4776086349626', '127.057873636837'],
 ['37.4732521542903', '127.05125791131'],
 ['37.4786814942828', '127.050124600494'],
 ['37.477106081167', '127.049478908065'],
 ['37.4841992876044', '127.060486695556'],
 ['37.4836153661169', '127.06131781719'],
 ['37.4748575708214', '127.048927316069'],
 ['37.4738403503004', '127.052044350915'],
 ['37.4791355932083', '127.046168433472'],
 ['37.4759264899821', '127.04747652125'],
 ['37.4770158604974', '127.049334251281'],
 ['37.472530654299', '127.050982711453'],
 ['37.4782405153824', '127.046665785012'],
 ['37.4725478953814', '127.050699424283'],
 ['37.4801009360233', '127.045467266355'],
 ['37.4767628966036', '127.04880498953'],
 ['37.4745104176784', '127.049346283588'],
 ['37.4773494304299', '127.058572798055'],
 ['37.478022335028', '127.049652375522'],
 ['37.4830288626892', '127.062591117133'],
 ['37.4755651856223', '127.049452229219'],
 ['37.4737205791333', '127.053317323934'],
 ['37.4808463371338', '127.04753695565'],
 ['37.4720546374135', '127.051221483585'],
 ['37.4804644108689', '127.048615986014'],
 ['37.4804644108689', '127.048615986014'],
 ['37.4774086127704', '127.04975869392'],
 ['37.4795411097809', '127.046924820029'],
 ['37.4839054870602', '127.060626772792'],
 ['37.4771343046129', '127.045618319547'],
 ['37.4726193815194', '127.050825295375'],
 ['37.4797994800616', '127.049879669702'],
 ['37.4800978712998', '127.049073866085'],
 ['37.47449849985', '127.054526732733'],
 ['37.4766189561444', '127.046468740431'],
 ['37.4731285689282', '127.051388850832'],
 ['37.4777370526888', '127.05055595686'],
 ['37.4775305129103', '127.048032413558'],
 ['37.4765591772227', '127.049025312895'],
 ['37.476834717527', '127.05007204019'],
 ['37.479321990844', '127.047134858655'],
 ['37.4809616178054', '127.048542592432'],
 ['37.4805102438498', '127.047129386719'],
 ['37.4748303042653', '127.048626580839'],
 ['37.4795388534159', '127.047160772269'],
 ['37.4775761068989', '127.045754820355'],
 ['37.4800914286455', '127.049399247402'],
 ['37.4723113379116', '127.051215328074'],
 ['37.4749677587303', '127.054498697625'],
 ['37.4742928297379', '127.052873666649'],
 ['37.4799052739424', '127.049198218444'],
 ['37.4745229118577', '127.051938669122'],
 ['37.4746822942135', '127.051126730846'],
 ['37.4776493771463', '127.049509339137'],
 ['37.4733322834471', '127.050981786303'],
 ['37.4767820159731', '127.050897982038'],
 ['37.4799636481731', '127.047687104667'],
 ['37.4802299104461', '127.047428253849'],
 ['37.4734067047445', '127.052020309829'],
 ['37.4779609528441', '127.051185379559'],
 ['37.4794641439217', '127.04853484022'],
 ['37.4756358846433', '127.049952534832'],
 ['37.4757496693414', '127.048027656118'],
 ['37.4782059520576', '127.051151290465'],
 ['37.4794445546766', '127.046613622311'],
 ['37.4798444783213', '127.045546478546'],
 ['37.4764349322293', '127.049447601821'],
 ['37.4763283227128', '127.049279985654'],
 ['37.4831202932491', '127.062462074136'],
 ['37.4778596267699', '127.049833044794'],
 ['37.4785990943998', '127.051904407335'],
 ['37.4733392113014', '127.051627190192'],
 ['37.4793622151961', '127.044715545013'],
 ['37.4740300104166', '127.0518450614'],
 ['37.4784800302789', '127.050332604183'],
 ['37.4807487498133', '127.048444092012'],
 ['37.4747433710188', '127.054966002815'],
 ['37.4734425276698', '127.052915913452'],
 ['37.4776714637946', '127.049265265902'],
 ['37.4804484810103', '127.048352545571'],
 ['37.4726303737781', '127.051656547411'],
 ['37.478181667469', '127.047375179361'],
 ['37.4803671276899', '127.047668140871'],
 ['37.4765846588174', '127.050772357901'],
 ['37.4768158948194', '127.046524711376'],
 ['37.4796406206956', '127.045674337515'],
 ['37.4790804809833', '127.045861220766'],
 ['37.4759694368396', '127.047777722652'],
 ['37.4760541672173', '127.047689934008'],
 ['37.4743900744405', '127.054012045769'],
 ['37.4782493587922', '127.05057427802'],
 ['37.4763900930285', '127.048722104604'],
 ['37.4809244735344', '127.048157709249'],
 ['37.477360506633', '127.045957849619'],
 ['37.4764726373799', '127.050622824534'],
 ['37.4841548073104', '127.06095520403'],
 ['37.4747268009675', '127.053574213462'],
 ['37.4800590009081', '127.047398637285'],
 ['37.4746888657842', '127.050511735375'],
 ['37.4748232283067', '127.053730180534'],
 ['37.4737957587524', '127.053438454011'],
 ['37.4776438432082', '127.050661262178'],
 ['37.4749854831206', '127.053965331603'],
 ['37.4800361237863', '127.049573548769'],
 ['37.4780810224358', '127.051057933642'],
 ['37.479721198292', '127.047434263633'],
 ['37.479930614036', '127.047381371168'],
 ['37.4745549754621', '127.053580647786'],
 ['37.4783298235113', '127.05139885655'],
 ['37.474194935275', '127.05297364757'],
 ['37.4801817243434', '127.048494037534'],
 ['37.4756646973463', '127.04935597369'],
 ['37.4742728923881', '127.05412297736'],
 ['37.4834974401087', '127.062661155891'],
 ['37.4807677772166', '127.048624209863'],
 ['37.4728895021804', '127.052071953804'],
 ['37.4769104936256', '127.046998243561'],
 ['37.4792097363449', '127.047556495504'],
 ['37.4784094932659', '127.050725882406'],
 ['37.4783936364577', '127.050933105245'],
 ['37.4776524892875', '127.049822166936'],
 ['37.4741004232385', '127.052763532899'],
 ['37.480360586305', '127.048684772293'],
 ['37.4792163134346', '127.045027498938'],
 ['37.4781481300309', '127.050680256958'],
 ['37.4746522476043', '127.053463256818'],
 ['37.4793635400468', '127.046190167887'],
 ['37.4779723989534', '127.05138538415'],
 ['37.4834177243636', '127.061067556761'],
 ['37.4833257664933', '127.061173875582'],
 ['37.4834071656038', '127.061274343303'],
 ['37.4775335964886', '127.049939779038'],
 ['37.4766596625131', '127.048313927005'],
 ['37.4836252242007', '127.062280459964'],
 ['37.4801575682925', '127.04626968537'],
 ['37.4730937699436', '127.051227392952'],
 ['37.4767412493802', '127.050362754139'],
 ['37.4725340213416', '127.051529075764'],
 ['37.474999738445', '127.053725106506'],
 ['37.4747911470752', '127.053939529156'],
 ['37.4776305457461', '127.048202626702'],
 ['37.478908591305', '127.045802212595'],
 ['37.4805503358705', '127.047809356498'],
 ['37.4806861246167', '127.04779282312'],
 ['37.4806543654808', '127.047453960726'],
 ['37.4806543654808', '127.047453960726'],
 ['37.4806543654808', '127.047453960726'],
 ['37.4772882165167', '127.045800884484'],
 ['37.4791580322216', '127.047072008373'],
 ['37.47799390127', '127.046227311836'],
 ['37.4746170063266', '127.053687977801'],
 ['37.4746170063266', '127.053687977801'],
 ['37.4753587094343', '127.047834538419'],
 ['37.477445126692', '127.058372425149'],
 ['37.4798473627369', '127.046697536358'],
 ['37.4724208945652', '127.050812273498'],
 ['37.4785827977229', '127.049997005906'],
 ['37.476520696477', '127.046594735049'],
 ['37.475521786568', '127.048511375918'],
 ['37.4748305578123', '127.053462479419'],
 ['37.4806684439383', '127.047172222937'],
 ['37.4789582321764', '127.046046221829'],
 ['37.4841624979295', '127.062104749539'],
 ['37.4736066403479', '127.05160600772'],
 ['37.4764840171362', '127.050348675859'],
 ['37.4778715757202', '127.049270710912'],
 ['37.4779416642331', '127.050362994434'],
 ['37.4773232329539', '127.046576353057'],
 ['37.4762458119835', '127.048793347891'],
 ['37.4746044703583', '127.05230840342'],
 ['37.4836827328029', '127.062914915443'],
 ['37.4766629142752', '127.05066093917'],
 ['37.4745448202154', '127.050661657434'],
 ['37.4742971519207', '127.053876883111'],
 ['37.4747773738062', '127.053117068919'],
 ['37.4767676434237', '127.049091359902'],
 ['37.4747441703865', '127.051594693336'],
 ['37.4777589316044', '127.058588154123'],
 ['37.4794090923494', '127.045594038066'],
 ['37.4757395813282', '127.049547195633'],
 ['37.4803084626536', '127.046561812207'],
 ['37.4759349926075', '127.048063160407'],
 ['37.4758487339381', '127.04792020591'],
 ['37.4777110044161', '127.048864282177'],
 ['37.4756252710278', '127.049048557003'],
 ['37.4756252710278', '127.049048557003'],
 ['37.4735222371651', '127.052172667851'],
 ['37.4778879806882', '127.050954694977'],
 ['37.4751606806047', '127.054268889598'],
 ['37.4781625380129', '127.048990634396'],
 ['37.4729429791811', '127.051138885853'],
 ['37.4800742616448', '127.047539066917'],
 ['37.4782972657932', '127.050001903237'],
 ['37.4791713418708', '127.051039229457'],
 ['37.4765669963134', '127.048417538135'],
 ['37.4797003732452', '127.047238658378'],
 ['37.4799447077703', '127.049701358535'],
 ['37.476538745187', '127.048097576386'],
 ['37.4758165981822', '127.049807834012'],
 ['37.4758136885953', '127.050083342621'],
 ['37.4776697910016', '127.058103074517'],
 ['37.480360058394', '127.047097409471'],
 ['37.4793626486237', '127.047529119193'],
 ['37.4760366297354', '127.049581759999'],
 ['37.4836962651801', '127.062712992655'],
 ['37.4807244824709', '127.048297775988'],
 ['37.4735014644471', '127.05125638582'],
 ['37.475698000287', '127.053770714483'],
 ['37.4770931180867', '127.04724967938'],
 ['37.4792341312026', '127.044611002813'],
 ['37.4751695417379', '127.048608938382'],
 ['37.4792609371718', '127.045669810203'],
 ['37.4800763615075', '127.047694299048'],
 ['37.4745156587499', '127.048657805221'],
 ['37.4746102150343', '127.048559737955'],
 ['37.4783827976602', '127.051823308904'],
 ['37.4738088663613', '127.050682414106'],
 ['37.4763742056044', '127.046789096983'],
 ['37.4801882522716', '127.049266918178'],
 ['37.4740435036024', '127.050649222651'],
 ['37.4739586834148', '127.050520853254'],
 ['37.4744069730315', '127.053506719804'],
 ['37.4797720411791', '127.049350760905'],
 ['37.4800975712057', '127.047828175107'],
 ['37.4742317910104', '127.051330480614'],
 ['37.479076588077', '127.051172686593'],
 ['37.4732415090836', '127.051080529718'],
 ['37.4775191273357', '127.049637910624'],
 ['37.4802022432468', '127.048771499463'],
 ['37.476891079484', '127.046191924713'],
 ['37.4781219040358', '127.051528842329'],
 ['37.5177663113712', '127.036713745695'],
 ['37.5178981174092', '127.038168829353'],
 ['37.5178163532576', '127.037742338516'],
 ['37.5188546019897', '127.039599468218'],
 ['37.5169351385765', '127.024541241447'],
 ['37.5173274146126', '127.038191274941'],
 ['37.5172470646197', '127.037850755925'],
 ['37.517462076838', '127.038029135281'],
 ['37.5120895074194', '127.030482341559'],
 ['37.5119923449461', '127.030614638064'],
 ['37.5114436652982', '127.029061343377'],
 ['37.5115127599737', '127.027993300902'],
 ['37.5116750444976', '127.026367784389'],
 ['37.5119791413522', '127.02673345542'],
 ['37.5117847727916', '127.026830206027'],
 ['37.511722096818', '127.026680429524'],
 ['37.5111627437288', '127.026321569844'],
 ['37.5111883787663', '127.02691482242'],
 ['37.5111271751513', '127.026629432986'],
 ['37.5099898235023', '127.025880275897'],
 ['37.5108797433054', '127.025890988912'],
 ['37.5097662836152', '127.024182615512'],
 ['37.5104162970614', '127.027741232056'],
 ['37.5102838826869', '127.027599123005'],
 ['37.5113746603102', '127.030444725611'],
 ['37.5100621276606', '127.030247616377'],
 ['37.5103206986116', '127.029604830838'],
 ['37.510269760955', '127.029727869079'],
 ['37.509457186179', '127.028834478559'],
 ['37.509447649826', '127.029143361558'],
 ['37.5098224587216', '127.029179926907'],
 ['37.5100431608213', '127.029357587307'],
 ['37.5098162817555', '127.028274636679'],
 ['37.5096856777558', '127.028476252255'],
 ['37.5099319977626', '127.028907500566'],
 ['37.5095092501792', '127.027378963692'],
 ['37.5094196198814', '127.027293989981'],
 ['37.5092475619004', '127.025944036248'],
 ['37.5149975863479', '127.020976553213'],
 ['37.5148821606457', '127.021016562579'],
 ['37.5074462800872', '127.025077060335'],
 ['37.5090927738569', '127.02865337305'],
 ['37.508520838801', '127.029295237163'],
 ['37.5087794820832', '127.029072978016'],
 ['37.5091909524397', '127.029869386112'],
 ['37.5090799694928', '127.029786889574'],
 ['37.5089905010814', '127.030487867527'],
 ['37.5084746716002', '127.030153440141'],
 ['37.5083734412179', '127.030339113313'],
 ['37.5063614179276', '127.025738101647'],
 ['37.5073843984273', '127.02930700794'],
 ['37.5075825082712', '127.030107614657'],
 ['37.507864306379', '127.031287150066'],
 ['37.5081055361102', '127.031510513786'],
 ['37.5061124899621', '127.026464223827'],
 ['37.5135171991961', '127.032652485295'],
 ['37.5123032761857', '127.033931775477'],
 ['37.5126155215681', '127.034079976055'],
 ['37.5118804204834', '127.033981916903'],
 ['37.5116548742581', '127.033754356071'],
 ['37.5116548742581', '127.033754356071'],
 ['37.5116548742581', '127.033754356071'],
 ['37.5118811734268', '127.033235633694'],
 ['37.5105938053585', '127.034227790703'],
 ['37.5093868683893', '127.034678523661'],
 ['37.5093877250463', '127.034522327741'],
 ['37.5095093779954', '127.034463004188'],
 ['37.5092540976839', '127.035761881388'],
 ['37.5155347483844', '127.040445383188'],
 ['37.5158730739723', '127.039919474597'],
 ['37.5146587288533', '127.039837387332'],
 ['37.5147456264418', '127.039983234711'],
 ['37.5137331949065', '127.036564613431'],
 ['37.5118852568171', '127.039031944779'],
 ['37.5116882614876', '127.042528326508'],
 ['37.5115837305079', '127.042568533322'],
 ['37.5111107261209', '127.040714564318'],
 ['37.5110242539561', '127.039850838063'],
 ['37.5112774646499', '127.039766368928'],
 ['37.5112260859036', '127.039562071241'],
 ['37.5096812329609', '127.0403337577'],
 ['37.5141221154955', '127.024967992711'],
 ['37.5184333924214', '127.026329553113'],
 ['37.5191778533927', '127.030249938198'],
 ['37.5190297680559', '127.031477664775'],
 ['37.5191864315715', '127.031556121751'],
 ['37.5179744529823', '127.030678617316'],
 ['37.5184949699917', '127.031336835044'],
 ['37.517883904991', '127.026975255843'],
 ['37.5193754143561', '127.038685630023'],
 ['37.5113694527888', '127.026237717209'],
 ['37.5108016186721', '127.030104270277'],
 ['37.5090490769969', '127.02421631512'],
 ['37.5095935711522', '127.031073313364'],
 ['37.5098339208024', '127.031218865322'],
 ['37.506694943703', '127.027455635353'],
 ['37.5126378798067', '127.040855083089'],
 ['37.5087928953912', '127.027231668304'],
 ['37.5114669304303', '127.030416486359'],
 ['37.5077239102269', '127.025356174039'],
 ['37.5190138407691', '127.032071416072'],
 ['37.5072530916303', '127.031860314802'],
 ['37.5114210194208', '127.038049935625'],
 ['37.510498678362', '127.035084068654'],
 ['37.5099035435144', '127.02444110371'],
 ['37.5096001395205', '127.032117380022'],
 ['37.5095758966299', '127.028636592112'],
 ['37.5172821621057', '127.032873796368'],
 ['37.5166457493636', '127.031679251863'],
 ['37.5186682372076', '127.031992990651'],
 ['37.5113005536137', '127.040493543906'],
 ['37.5135155072938', '127.02563287748'],
 ['37.5125720724891', '127.039091910665'],
 ['37.5142291807572', '127.021141932777'],
 ['37.5147578933433', '127.028425243007'],
 ['37.5110450554947', '127.029447220563'],
 ['37.5116303436975', '127.041210029711'],
 ['37.5189237257664', '127.032125447989'],
 ['37.5069849737549', '127.030060551215'],
 ['37.5113916797867', '127.024695061295'],
 ['37.5088986805704', '127.02981373606'],
 ['37.5144893575634', '127.024572337992'],
 ['37.5122011129834', '127.029531940223'],
 ['37.5183607582591', '127.037399980352'],
 ['37.5123200218957', '127.030685125207'],
 ['37.515249449176', '127.021793636208'],
 ['37.5108025582199', '127.041816048491'],
 ['37.5101945749492', '127.041262286593'],
 ['37.5079341037848', '127.029658968775'],
 ['37.5111649851832', '127.028690585457'],
 ['37.519791380477', '127.031834424192'],
 ['37.5075780186423', '127.025444004208'],
 ['37.5117626277824', '127.041162258028'],
 ['37.5082142701549', '127.02875234082'],
 ['37.5134440551961', '127.022075999092'],
 ['37.5169476942979', '127.032275949'],
 ['37.5109940236899', '127.034564125086'],
 ['37.5175953479222', '127.037989725371'],
 ['37.5081057208837', '127.029395848682'],
 ['37.5128755621809', '127.039806918079'],
 ['37.5128427224169', '127.039667550363'],
 ['37.5103062611625', '127.028219739286'],
 ['37.5127729455418', '127.023233470899'],
 ['37.5099668515448', '127.024598113611'],
 ['37.5131476635376', '127.036170819999'],
 ['37.5129550263643', '127.036178984002'],
 ['37.5094952983082', '127.031313166085'],
 ['37.5091834364612', '127.03071879018'],
 ['37.5116440419189', '127.042723298195'],
 ['37.5115780573568', '127.04180279517'],
 ['37.5130969473303', '127.037862911754'],
 ['37.5184240935', '127.03935728257'],
 ['37.5064038162443', '127.025081801094'],
 ['37.5071791101374', '127.025180344773'],
 ['37.5169783907014', '127.025791292075'],
 ['37.5065917191078', '127.026931381084'],
 ['37.5098156721384', '127.026230613279'],
 ['37.5152159847328', '127.041194355714'],
 ['37.5116080640939', '127.027318200038'],
 ['37.5095464927993', '127.030208274319'],
 ['37.5069637441071', '127.028091921984'],
 ['37.5071854898014', '127.028805442757'],
 ['37.513644224608', '127.037272979206'],
 ['37.5086325420494', '127.028647542'],
 ['37.5176311429186', '127.038191090383'],
 ['37.5147473903244', '127.029371759126'],
 ['37.5103386913463', '127.025885372977'],
 ['37.5115666568847', '127.027149089881'],
 ['37.5069008837344', '127.026800409217'],
 ['37.5138208843132', '127.021427987092'],
 ['37.5110702468476', '127.033316145141'],
 ['37.5112601822277', '127.034864432743'],
 ['37.5106443020933', '127.038487147187'],
 ['37.5134729765519', '127.024804558811'],
 ['37.5173430519124', '127.031954531105'],
 ['37.5079247946419', '127.028680975802'],
 ['37.5150218598207', '127.027007141339'],
 ['37.5124273369628', '127.036959290103'],
 ['37.5086990083959', '127.024786918462'],
 ['37.5111948688095', '127.039955552287'],
 ['37.5119368238789', '127.022717554052'],
 ['37.5106187898578', '127.023858842893'],
 ['37.5106187898578', '127.023858842893'],
 ['37.5089224374614', '127.025306700983'],
 ['37.5095860766998', '127.030790776271'],
 ['37.5161124428731', '127.026573968665'],
 ['37.5171268280583', '127.032877574153'],
 ['37.5143507199098', '127.039705901434'],
 ['37.5167593925781', '127.032900035933'],
 ['37.5167436837395', '127.02775895776'],
 ['37.5092197289918', '127.030440117967'],
 ['37.510601466225', '127.026104096868'],
 ['37.5161226705666', '127.022911795253'],
 ['37.513189446284', '127.04196363074'],
 ['37.5136959178712', '127.022854950676'],
 ['37.5128385756313', '127.041509301731'],
 ['37.5129033709166', '127.041727864358'],
 ['37.5100839418591', '127.028015501372'],
 ['37.5180479091636', '127.039132661174'],
 ['37.5147472756398', '127.040168060375'],
 ['37.5093598682909', '127.029600945149'],
 ['37.5169346372669', '127.032901809596'],
 ['37.5192016594365', '127.038537015615'],
 ['37.5095279929827', '127.036091370872'],
 ['37.5096383080924', '127.035986010914'],
 ['37.5089730950412', '127.031241240549'],
 ['37.5144138091038', '127.021071177145'],
 ['37.5164886404477', '127.028759926571'],
 ['37.5096327669786', '127.030372310102'],
 ['37.5077196990056', '127.031945791461'],
 ['37.5105152390861', '127.023536119994'],
 ['37.5200060485626', '127.039435939888'],
 ['37.5112234868765', '127.041362726072'],
 ['37.5162631648488', '127.039781909351'],
 ['37.5193394087597', '127.03194022449'],
 ['37.5099426623488', '127.035705883792'],

In [18]:
data2 = pd.DataFrame(add_list[:77040], columns=['도로명'])
data2.head()

          도로명
0      논현로 10
1    논현로2길 66
2  논현로8길 62-1
3    논현로8길 63
4   개포로26길 16

In [23]:
data3 = pd.DataFrame(list1, columns=['위도','경도'])
data3.head()

                 위도                경도
0  37.4723876864126  127.050510865064
1  37.4745435620733  127.055084221135
2  37.4745435620733  127.055084221135
3  37.4753126502908  127.053546142443
4  37.4780340050176  127.049108807588

In [25]:
data4 = pd.concat([data2, data3], axis=1)
data4.head()

          도로명                위도                경도
0      논현로 10  37.4723876864126  127.050510865064
1    논현로2길 66  37.4745435620733  127.055084221135
2  논현로8길 62-1  37.4745435620733  127.055084221135
3    논현로8길 63  37.4753126502908  127.053546142443
4   개포로26길 16  37.4780340050176  127.049108807588

In [26]:
data4.to_csv('data/연립_위도경도(1).csv', index=False)

In [34]:
# 이어서 주소 검색 함수 적용
add_list2 = add_list[77040:]
add_list2

['보문로13라길 10-13',
 '보문사길 88-4',
 '삼선교로10바길 8',
 '삼선교로10바길 27-1',
 '삼선교로16가길 38-15',
 '삼선교로20길 52-8',
 '삼선교로18가길 34',
 '보문로29나길 15',
 '삼선교로18나길 20',
 '삼선교로22길 28',
 '삼선교로20길 33',
 '화랑로18바길 12',
 '화랑로40길 46-14',
 '화랑로38길 5',
 '화랑로 202',
 '한천로69길 10-3',
 '한천로 536-6',
 '화랑로40길 36-13',
 '돌곶이로7길 32',
 '돌곶이로9가길 10',
 '돌곶이로9길 5-11',
 '돌곶이로21나길 6',
 '화랑로24길 22-17',
 '한천로81길 29-7',
 '화랑로32라길 3-2',
 '한천로76가길 14',
 '한천로82길 17',
 '한천로72길 24-8',
 '화랑로40길 36-9',
 '화랑로42길 29-5',
 '성북로10길 45-3',
 '성북로10길 7-10',
 '성북로24길 45-20',
 '성북로8다길 25',
 '성북로8다길 29-6',
 '성북로5길 48',
 '성북로5길 51-4',
 '창경궁로43길 63',
 '보국문로30길 36-1',
 '인촌로7길 56-13',
 '인촌로10길 32',
 '인촌로10길 65',
 '안암로7길 21',
 '안암로9가길 77',
 '인촌로 110-15',
 '한천로89길 32',
 '월계로 138-6',
 '장위로 34-27',
 '장위로50길 64-7',
 '화랑로37길 51-13',
 '돌곶이로31길 6-3',
 '돌곶이로 100-26',
 '장위로16길 77',
 '화랑로 241-3',
 '장월로28길 40-9',
 '한천로 618-9',
 '돌곶이로25길 24-10',
 '화랑로35길 28-3',
 '장위로20길 23-6',
 '장위로21다길 59-3',
 '월계로 146',
 '장위로 156-8',
 '장위로16길 35-17',
 '장위로50길 14-7',
 '장위로21길 76',
 '장위로40가길 9',
 '장월로4길 34-3',
 '장위로44길 67',
 '화랑로35길 35',
 '장위로31길 11-5',
 '장위로49길 1-20',
 '장위로11가길 16',
 '장위로48길 13',
 '장위로13길 14',
 '장위로46길 31',
 '장위로21길 17-13',
 '장위로11가길 64',
 '한천로101가길 50',
 '돌곶이로27나길 25-4',
 '장위로16길 78',
 '장위로15길 107',
 '장위로44길 14',
 '장위로 189-18',
 '화랑로37가길 15',
 '장위로48길 7',
 '장위로15길 26',
 '돌곶이로30가길 18',
 '한천로 635-9',
 '돌곶이로38길 35',
 '돌곶이로31길 5',
 '장위로 180-23',
 '장위로48길 32',
 '장월로31길 55',
 '장위로15길 42-22',
 '한천로89길 5-11',
 '장위로44길 8',
 '장월로 93-16',
 '동소문로35길 61',
 '보국문로8다길 67',
 '보국문로18가길 70',
 '보국문로10길 35-1',
 '솔샘로 16-7',
 '솔샘로5가길 16',
 '보국문로30나길 22-8',
 '보국문로16가길 34-4',
 '솔샘로18길 46',
 '솔샘로6가길 42',
 '보국문로34길 15-12',
 '북악산로1길 32',
 '보국문로8길 52',
 '보국문로16가길 32',
 '보국문로16가길 34',
 '보국문로17길 18-6',
 '보국문로38길 3',
 '보국문로4길 13-8',
 '솔샘로 16-10',
 '서경로13길 31',
 '정릉로21길 40-8',
 '아리랑로5길 101-2',
 '솔샘로15다길 54',
 '보국문로 210-8',
 '정릉로27가길 8',
 '정릉로10라길 5',
 '솔샘로6가길 46-3',
 '솔샘로6가길 9',
 '솔샘로9길 27',
 '서경로21가길 8',
 '보국문로8길 102',
 '정릉로12길 32',
 '정릉로21길 51',
 '보국문로16가길 71',
 '정릉로15길 26',
 '보국문로28길 5',
 '솔샘로4길 30-29',
 '솔샘로4길 30-43',
 '솔샘로9길 13',
 '정릉로10길 108',
 '보국문로29가길 4',
 '보국문로6길 7',
 '북악산로1라길 24',
 '보국문로36길 16',
 '정릉로40길 26',
 '보국문로36길 5-5',
 '보국문로38길 25-9',
 '정릉로27길 71',
 '정릉로 181-7',
 '서경로9길 45',
 '보국문로16나길 2',
 '정릉로24길 57-42',
 '정릉로10가길 6-11',
 '정릉로26가길 25',
 '아리랑로19길 89',
 '솔샘로5길 43-5',
 '보국문로10길 4',
 '보국문로 40-14',
 '보국문로30길 44',
 '보국문로20길 49-19',
 '정릉로34길 41',
 '정릉로31가길 51',
 '보국문로20길 31',
 '정릉로12길 12',
 '보국문로 210-10',
 '북악산로1다길 13',
 '정릉로27나길 5-4',
 '솔샘로1길 10',
 '정릉로27길 156',
 '북악산로1길 25',
 '북악산로1길 26-11',
 '서경로21길 51',
 '북악산로3길 42',
 '보국문로8길 37',
 '서경로21길 53',
 '북악산로1라길 36',
 '솔샘로11길 15',
 '보국문로38길 8',
 '정릉로29길 13',
 '회기로3길 8',
 '종암로13길 33',
 '종암로19길 64-26',
 '종암로19길 64-5',
 '종암로9길 68',
 '종암로19길 87',
 '종암로19다길 15',
 '종암로14길 32-27',
 '종암로14길 13-10',
 '종암로3길 17',
 '종암로13길 10-14',
 '종암로5길 37',
 '종암로3길 50',
 '월계로 28-10',
 '오패산로17길 10-8',
 '화랑로13길 102-10',
 '종암로32길 13-5',
 '화랑로14길 76',
 '종암로36길 31',
 '오패산로1길 39-10',
 '화랑로7길 9',
 '동남로20길 50-33',
 '송이로23길 38',
 '동남로20길 50',
 '오금로34길 4-18',
 '동남로13길 32-17',
 '오금로42길 4',
 '동남로9길 53',
 '동남로14길 17-32',
 '중대로10길 21',
 '성내천로20길 19',
 '오금로68길 26-4',
 '오금로53길 31',
 '오금로61길 28',
 '성내천로18길 20',
 '오금로53길 9-10',
 '거마로15길 22',
 '마천로48길 2',
 '감이남로 6-6',
 '성내천로53길 3-9',
 '성내천로49길 3',
 '성내천로33다길 19',
 '성내천로43다길 3',
 '성내천로47길 8-1',
 '성내천로43라길 13-5',
 '마천로37길 9',
 '거마로24길 5-13',
 '마천로65길 3-8',
 '성내천로43가길 15',
 '마천로39길 31',
 '성내천로22길 12',
 '성내천로23가길 14-21',
 '성내천로23길 36-7',
 '성내천로23가길 25',
 '성내천로32가길 2-10',
 '마천로39길 4-10',
 '마천로33길 11-5',
 '마천로 379',
 '마천로 383',
 '마천로33길 11-9',
 '성내천로23길 6',
 '성내천로21길 28-1',
 '성내천로43다길 2',
 '성내천로21길 23',
 '마천로35길 9',
 '송이로31길 32-17',
 '송이로31길 16-9',
 '동남로8길 19-11',
 '새말로17길 12-5',
 '송이로31길 32-31',
 '송이로31길 24-24',
 '새말로13길 11',
 '송이로36길 31',
 '새말로6길 24-12',
 '새말로17길 12-4',
 '송이로31길 20-15',
 '송이로31길 28-18',
 '송이로37가길 27',
 '송이로31길 32-14',
 '송이로36길 9',
 '새말로6길 53',
 '송파대로18길 13',
 '송이로38길 8-1',
 '송이로33길 12-7',
 '송이로33길 12-3',
 '동남로2길 9-12',
 '송이로36길 30',
 '동남로8길 25-5',
 '송파대로22길 5-26',
 '송이로31길 24-16',
 '송이로31길 20-20',
 '위례성대로10길 34-1',
 '가락로40길 15-7',
 '위례성대로16길 27',
 '오금로23길 17-1',
 '양재대로71길 42-7',
 '가락로39길 37',
 '백제고분로50길 11-28',
 '위례성대로6길 5',
 '오금로17길 5-37',
 '가락로42길 15-25',
 '가락로38길 11',
 '가락로40길 10',
 '올림픽로32길 39-24',
 '위례성대로6길 39',
 '올림픽로32길 19-12',
 '백제고분로50길 42-21',
 '백제고분로48나길 3-26',
 '오금로13길 15',
 '오금로25길 12',
 '오금로 231',
 '가락로39길 3',
 '양재대로71길 27-14',
 '백제고분로50길 41-10',
 '위례성대로6길 9',
 '오금로11길 30-9',
 '백제고분로50길 15-27',
 '오금로17길 30-1',
 '가락로38길 14',
 '백제고분로29길 16',
 '백제고분로22길 19-17',
 '백제고분로28길 20-52',
 '백제고분로28길 35-33',
 '삼학사로9길 20',
 '백제고분로29길 26',
 '백제고분로22길 8-13',
 '삼학사로13길 24-1',
 '백제고분로32길 11-17',
 '백제고분로24길 6',
 '삼학사로3길 36',
 '백제고분로28길 20-49',
 '가락로5길 8-14',
 '백제고분로40길 5-18',
 '백제고분로39길 13-11',
 '백제고분로37가길 33',
 '백제고분로34길 15-20',
 '가락로6길 3-13',
 '가락로5길 3-6',
 '가락로2길 3-24',
 '가락로5길 27-11',
 '석촌호수로18길 8-68',
 '백제고분로34길 18-21',
 '삼학사로18길 11',
 '백제고분로36길 20',
 '백제고분로40길 19-10',
 '가락로5길 4-20',
 '백제고분로37가길 16',
 '백제고분로34길 4-12',
 '백제고분로46길 26-42',
 '오금로22길 24-1',
 '송파대로34가길 6-8',
 '가락로18길 9',
 '송파대로34가길 30',
 '송이로4길 13',
 '송이로6길 14-1',
 '송파대로36가길 15-20',
 '가락로18길 10-1',
 '백제고분로44길 21',
 '송이로4길 7-1',
 '가락로31길 25',
 '송이로6길 14',
 '백제고분로44길 35',
 '가락로21길 60',
 '가락로31길 22',
 '송파대로36길 31-34',
 '송파대로36길 31-18',
 '백제고분로45길 17-17',
 '백제고분로45길 17-13',
 '백제고분로46길 31-15',
 '송파대로34가길 12-13',
 '동남로23길 20-18',
 '마천로27길 13',
 '성내천로6길 1-14',
 '마천로21길 9',
 '동남로24길 41',
 '성내천로14길 11-16',
 '성내천로12길 9-9',
 '동남로26길 8',
 '마천로25길 5-7',
 '문정로 267',
 '성내천로8가길 13',
 '문정로25길 5',
 '동남로26길 29',
 '문정로19길 13',
 '중대로34길 5-16',
 '동남로28길 26-5',
 '성내천로8가길 15',
 '마천로 199',
 '동남로26길 36',
 '문정로23길 12',
 '동남로23길 40-18',
 '문정로 231-11',
 '문정로17길 2',
 '문정로25길 31-4',
 '위례성대로22나길 3-10',
 '중대로27길 8',
 '석촌호수로12길 17-27',
 '도곡로64길 33-1',
 '삼전로9길 28-1',
 '백제고분로12길 24-8',
 '석촌호수로12길 23-3',
 '도곡로62길 15-13',
 '백제고분로19길 15-24',
 '백제고분로11길 6-28',
 '삼전로13길 7',
 '백제고분로12길 20-8',
 '바람드리2길 11-1',
 '풍성로25다길 21',
 '토성로15길 18',
 '강동대로7길 6',
 '한가람로12길 9',
 '천호대로152길 13',
 '풍성로8길 14',
 '목동중앙본로2길 38-43',
 '목동중앙남로16나길 9',
 '목동중앙북로8길 64-1',
 '목동중앙본로7가길 19',
 '목동중앙남로3가길 96-1',
 '목동중앙본로3길 34',
 '목동중앙서로7다길 14',
 '목동중앙로13길 19-43',
 '목동중앙북로16가길 29-1',
 '목동중앙본로3길 14',
 '목동중앙본로3길 16',
 '목동중앙본로7가길 70-18',
 '목동중앙북로 126-1',
 '목동중앙본로17길 45',
 '목동중앙서로6길 38',
 '목동중앙본로19길 13',
 '목동중앙남로 22-10',
 '목동중앙남로16라길 23',
 '목동중앙남로5길 10-10',
 '목동중앙북로16가길 11-4',
 '목동중앙북로16길 132',
 '목동중앙남로4길 5',
 '목동중앙북로8길 84-8',
 '목동중앙북로18길',
 '목동중앙남로16가길 22-3',
 '목동중앙북로10길 12-10',
 '목동중앙본로5길 68',
 '목동중앙서로8가길 7-3',
 '목동중앙북로7길 16',
 '목동중앙로13가길 17',
 '목동중앙남로3가길 20-8',
 '목동중앙북로16길 129',
 '목동중앙남로5길 37',
 '목동중앙서로7길 16-8',
 '목동중앙본로7가길 58-15',
 '목동중앙남로 12-16',
 '목동중앙남로3가길 8-26',
 '목동중앙남로16다길 9',
 '목동중앙본로7가길 68',
 '목동중앙본로7길 9-14',
 '목동중앙북로 33-20',
 '목동중앙남로13길 16',
 '목동중앙북로 83-1',
 '목동중앙북로8길 138-11',
 '목동중앙북로8길 80-17',
 '목동중앙본로7길 38-19',
 '목동중앙로5가길 25',
 '목동중앙남로9길 20',
 '목동중앙본로26길 29-8',
 '목동중앙로13나길 75',
 '목동중앙남로16나길 29',
 '목동중앙북로14길 46-1',
 '목동중앙본로24길 38',
 '목동중앙북로16길 28',
 '목동중앙본로7가길 73',
 '목동중앙본로32길 41',
 '목동중앙북로2길 28',
 '목동중앙남로5길 28-5',
 '목동중앙북로8나길 7',
 '목동중앙본로9길 23',
 '목동중앙본로20길 55',
 '목동중앙본로20길 12',
 '목동중앙로5길 43-6',
 '목동중앙본로1길 24',
 '목동중앙본로9길 3',
 '목동중앙본로20길 40',
 '목동중앙서로7다길 28',
 '목동중앙북로16길 39',
 '목동중앙남로16길 28',
 '목동중앙북로8길 80-1',
 '목동중앙본로15길 25',
 '곰달래로5길 45-14',
 '중앙로51길 8-7',
 '화곡로14길 28',
 '월정로15길 19',
 '월정로27길 21',
 '중앙로53길 22-4',
 '지양로7길 27-6',
 '신월로17길 1',
 '남부순환로82길 15-1',
 '오목로3길 35',
 '곰달래로10길 14',
 '오목로3길 25',
 '지양로 135-1',
 '남부순환로35길 30',
 '화곡로4길 29',
 '월정로15길 22-1',
 '지양로 165',
 '지양로 167',
 '지양로7길 35',
 '지양로7길 37',
 '신월로22길 3',
 '오목로10길 10-1',
 '남부순환로 604-3',
 '남부순환로36길 25',
 '가로공원로61길 10',
 '남부순환로36길 11',
 '월정로13길 6-6',
 '지양로14길 5',
 '남부순환로70길 17-11',
 '신월로9길 6',
 '오목로17길 16-2',
 '곰달래로9길 21',
 '남부순환로77길 12',
 '지양로14길 5-13',
 '신월로5길 8',
 '오목로 64-15',
 '가로공원로67길 12-4',
 '남부순환로35길 32',
 '남부순환로74길 8',
 '남부순환로82길 21',
 '남부순환로70길 12-10',
 '남부순환로80길 9',
 '중앙로55길 33',
 '중앙로55길 62-1',
 '신월로20길 26-1',
 '신월로22길 5',
 '남부순환로66길 9',
 '중앙로57길 14',
 '지양로16길 31',
 '월정로25길 20',
 '절골11길 16',
 '남부순환로71길 16-1',
 '신월로9길 12',
 '중앙로51가길 16-1',
 '곰달래로1길 42-1',
 '가로공원로66길 25',
 '가로공원로61길 26-1',
 '남부순환로63길 16-1',
 '지양로16길 37',
 '지양로16길 37-1',
 '남부순환로70길 16-7',
 '곰달래로9길 71',
 '남부순환로30길 12',
 '신월로 115-1',
 '오목로 68-1',
 '화곡로12길 23-11',
 '남부순환로82길 17',
 '지양로2길 12',
 '지양로2길 24',
 '지양로2길 22-2',
 '남부순환로70길 9-2',
 '지양로10길 3-10',
 '지양로10길 7-11',
 '월정로9길 8',
 '월정로 256-3',
 '신월로19길 8-1',
 '신월로11길 39-3',
 '남부순환로85길 17-1',
 '남부순환로73길 8-1',
 '남부순환로82길 9',
 '남부순환로82길 9-1',
 '남부순환로70길 12-5',
 '절골10길 3',
 '곰달래로11길 50-3',
 '오목로15길 23',
 '지양로13길 10',
 '가로공원로 92-5',
 '남부순환로60길 17',
 '월정로33길 3-1',
 '가로공원로66길 20',
 '오목로11길 9',
 '남부순환로31길 28',
 '지양로17길 35',
 '신남1길 7',
 '지양로14길 9-10',
 '남부순환로62길 21',
 '지양로17길 6',
 '가로공원로66길 26-1',
 '남부순환로70길 19-5',
 '지양로13길 22',
 '월정로 316',
 '월정로 316-1',
 '월정로 316-9',
 '월정로17길 24-13',
 '남부순환로74길 3-3',
 '지양로17길 27',
 '중앙로53길 22-14',
 '신월로11길 7-1',
 '남부순환로27길 9-9',
 '가로공원로69길 22',
 '중앙로55길 22',
 '가로공원로55길 36',
 '남부순환로70길 19-1',
 '남부순환로70길 17-4',
 '오목로 104',
 '곰달래로9길 15-1',
 '오목로15길 32-20',
 '오목로 39-11',
 '지양로2길 9',
 '지양로2길 5',
 '신월로22길 2',
 '남부순환로60길 15',
 '남부순환로36길 19',
 '남부순환로36길 19-1',
 '남부순환로82길 16',
 '화곡로12길 23-6',
 '월정로6길 20',
 '지양로2길 28',
 '곰달래로2길 19',
 '남부순환로82길 22-1',
 '남부순환로70길 19-19',
 '가로공원로70길 7-1',
 '남부순환로75길 10-2',
 '오목로50길 32',
 '중앙로29길 16',
 '중앙로48길 67',
 '오목로32길 15-3',
 '중앙로48길 36-1',
 '오목로32길 15-2',
 '신정중앙로15길 5-11',
 '중앙로45길 17-22',
 '신정중앙로2길 2',
 '은행정로19길 15-1',
 '오목로30길 23-4',
 '중앙로48길 62',
 '목동남로 68',
 '목동남로4길 43-4',
 '중앙로45길 22-15',
 '오목로40길 13-1',
 '목동로17길 14',
 '신월로 310-1',
 '목동남로 68-8',
 '오목로35길 16',
 '오목로30길 19-16',
 '중앙로 222-8',
 '중앙로52길 34-4',
 '오목로24길 19-5',
 '은행정로20길 5-20',
 '오목로38길 6',
 '중앙로25길 5',
 '목동동로8길 31-13',
 '중앙로27길 15-1',
 '남부순환로 700-6',
 '목동로19길 8',
 '중앙로52길 16-18',
 '국회대로53길 24-13',
 '영신로45길 13',
 '당산로10길 24-3',
 '국회대로37길 12-2',
 '당산로 160-3',
 '당산로48길 6-22',
 '당산로49길 12-2',
 '당산로46길 22',
 '당산로46가길 8',
 '디지털로 336-1',
 '대림로29다길 11-3',
 '대림로40가길 11-2',
 '대림로29나길 22',
 '가마산로34길 19',
 '디지털로67길 8',
 '시흥대로185길 15',
 '도림천로21길 33',
 '디지털로64길 2-25',
 '대림로8길 16',
 '대림로34마길 13',
 '도림천로11길 31-2',
 '대림로31다길 1-8',
 '도림로47가길 3',
 '가마산로46가길 20',
 '디지털로38길 20-14',
 '디지털로 358-10',
 '대림로7길 3-2',
 '대림로31다길 1-5',
 '대림로40길 20-1',
 '대림로40길 22',
 '디지털로 393-1',
 '대림로34나길 19',
 '가마산로46가길 3',
 '영신로1가길 14',
 '도신로29가길 2',
 '도림로113길 23-1',
 '신길로62길 37',
 '신길로62가길 1-3',
 '신길로62가길 1-5',
 '신길로62길 21-10',
 '신길로62길 23-4',
 '신길로62길 33',
 '신길로42가길 40-4',
 '신길로42가길 40-2',
 '신길로34가길 10',
 '신풍로7길 9',
 '가마산로61나길 9-20',
 '신풍로 92',
 '여의대방로17길 7',
 '여의대방로51길 21',
 '영등포로62나길 7',
 '신길로42길 30-10',
 '신길로38길 13-17',
 '신길로42길 34-4',
 '신길로38나길 3-14',
 '신길로42길 44-14',
 '여의대방로31길 6-1',
 '영등포로 369-3',
 '영등포로60길 11',
 '도신로52길 11',
 '여의대방로21길 5',
 '여의대방로35길 28',
 '신길로42가길 38-2',
 '대방천로 124-6',
 '여의대방로53가길 8',
 '여의대방로61길 33',
 '대림로34길 34',
 '대림로34차길 1',
 '신풍로14길 12',
 '신풍로 105-6',
 '도신로64길 13-13',
 '가마산로 526-6',
 '영등포로62가길 6-4',
 '여의대방로47나길 21',
 '도신로62길 20-11',
 '신길로16길 9-2',
 '여의대방로39길 20',
 '도림로63길 22',
 '영등포로80길 21',
 '여의대방로39길 28',
 '가마산로48길 41-2',
 '도신로68길 13-6',
 '도신로64가길 5',
 '양평로18길 16-5',
 '양평로 92-4',
 '양평로24길 3',
 '양평로22바길 7-2',
 '영신로19길 11-10',
 '영신로10길 12-4',
 '국회대로52길 2-1',
 '국회대로56길 14',
 '한강대로94길 10',
 '서빙고로71길 16',
 '서빙고로75가길 36',
 '보광로7길 23-5',
 '보광로7길 63',
 '장문로 93',
 '보광로21길 12',
 '장문로45바길 18-1',
 '우사단로2가길 19-1',
 '장문로45바길 18-4',
 '장문로45나길 29',
 '서빙고로97길 10-8',
 '만리재로26가길 8-1',
 '만리재로24길 39',
 '효창원로104라길 29',
 '청파로77가길 4-4',
 ' 237',
 '새창로45가길 14',
 '효창원로23나길 5',
 '효창원로37마길 16-3',
 '효창원로37나길 20-21',
 '효창원로25나길 2-23',
 '효창원로37나길 20-15',
 ' 120-5',
 '신흥로36가길 24-10',
 '신흥로36가길 24-4',
 '신흥로36가길 24-5',
 '신흥로22길 12',
 '신흥로22길 14-4',
 '신흥로20길 9',
 '신흥로22길 14-7',
 '신흥로22길 30',
 '두텁바위로38길 43',
 '신흥로11길 33',
 '신흥로11길 12',
 '소월로30길 18',
 '소월로30길 19',
 '소월로30길 25',
 '소월로30길 53-25',
 '소월로30길 53-27',
 '신흥로11가길 9',
 '신흥로36가길 24-7',
 '신흥로2길 32',
 '원효로56길 18',
 '원효로 189-7',
 '원효로41가길 14-21',
 '이촌로22길 9-9',
 '이촌로65가길 72',
 '이촌로22길 13-9',
 '회나무로28가길 7-11',
 '회나무로35길 5',
 '이태원로16길 19',
 '회나무로44다길 1',
 '회나무로44길 143',
 '회나무로21길 52',
 '보광로60길 14-6',
 '보광로60길 14-14',
 '회나무로26길 31-14',
 '서빙고로91나길 6',
 '청파로71가길 13-5',
 '청파로71다길 13',
 '청파로71나길 23-6',
 '효창원로86라길 50',
 '효창원로86라길 31-5',
 '효창원로86라길 27',
 '청파로71나길 24',
 '효창원로86나길 28',
 '효창원로 170',
 '백범로79길 98',
 '새창로 213-9',
 '한강대로7길 30-20',
 '유엔빌리지2길 95',
 '한남대로8길 9-3',
 '독서당로3길 3-12',
 '독서당로3길 10-5',
 '대사관로34나길 17',
 '독서당로5길 16-18',
 '대사관로34나길 26-4',
 '대사관로34길 62-10',
 '대사관로34길 46-3',
 '대사관로34길 52-6',
 '대사관로34가길 2-16',
 '대사관로34가길 2-7',
 '장문로49길 77',
 '장문로49나길 19',
 '대사관로30가길 40-2',
 '한남대로20길 41-5',
 '한남대로40길 45',
 '한남대로42가길 32',
 '한남대로36길 25-10',
 '한남대로27가길 15',
 '한남대로46길 2-8',
 '유엔빌리지3길 102',
 '대사관로30나길 32',
 '한남대로46길 38',
 '한남대로8길 6-28',
 '대사관로8길 6',
 '이태원로55가길 13',
 '유엔빌리지1길 17',
 '유엔빌리지길 259-5',
 '백범로45길 22',
 '백범로47길 37',
 '백범로47가길 4',
 '백범로 276',
 '효창원로66길 47',
 '백범로47길 47',
 '백범로47길 21-1',
 '효창원로76길 27',
 '후암로16다길 14-3',
 '두텁바위로47길 9-1',
 '두텁바위로38가길 11-1',
 '두텁바위로38가길 9',
 '신흥로20길 35-5',
 '두텁바위로38길 35',
 '두텁바위로38길 36',
 '소월로2가길 17',
 '두텁바위로69길 15-36',
 '후암로28라길 3',
 '두텁바위로35길 11',
 '두텁바위로53길 5',
 '후암로34가길 12-5',
 '후암로28다길 4',
 '후암로34길 12',
 '두텁바위로58길 14',
 '갈현로27길 44-8',
 '갈현로29길 30-4',
 '갈현로33가길 7-19',
 '갈현로33가길 29-1',
 '갈현로39가길 6',
 '갈현로37가길 13-8',
 '갈현로41가길 36',
 '통일로85길 1',
 '연서로29길 26',
 '갈현로35길 6-10',
 '갈현로37길 20-6',
 '갈현로29길 16',
 '갈현로 249-4',
 '연서로 205-1',
 '연서로21길 13-3',
 '연서로19길 16-8',
 '연서로21길 24',
 '연서로17길 28-3',
 '연서로17길 37',
 '갈현로 236-5',
 '갈현로23길 32-6',
 '서오릉로18길 34-6',
 '갈현로21길 21',
 '갈현로45길 18',
 '갈현로25길 14',
 '갈현로23길 12',
 '갈현로27길 21',
 '갈현로 324-5',
 '연서로23길 11-4',
 '갈현로29길 51-32',
 '갈현로25길 36',
 '서오릉로18길 13-9',
 '연서로21길 20-14',
 '갈현로21길 13-8',
 '갈현로37길 43',
 '갈현로 333-7',
 '갈현로35길 3',
 '갈현로23길 42-5',
 '갈현로25길 8',
 '연서로21길 33-8',
 '연서로19길 40-7',
 '갈현로47길 10-5',
 '서오릉로18길 35-18',
 '연서로21길 20-19',
 '갈현로45길 14-20',
 '갈현로 223',
 '갈현로23길 9-9',
 '갈현로39가길 25',
 '갈현로41길 61-1',
 '연서로25길 23-1',
 '연서로21길 34-3',
 '갈현로47길 14-6',
 '갈현로 295-17',
 '갈현로36길 3-4',
 '연서로11길 20-24',
 '갈현로16길 3-5',
 '갈현로17나길 24',
 '서오릉로25가길 3-7',
 '서오릉로25길 30',
 '서오릉로17길 18-16',
 '서오릉로17길 22-8',
 '서오릉로17길 22-9',
 '서오릉로21길 33-12',
 '서오릉로 157-19',
 '연서로11길 32-9',
 '갈현로 170-2',
 '연서로11길 12-13',
 '갈현로15길 37',
 '갈현로 139-2',
 '연서로15길 39',
 '연서로15길 45-1',
 '연서로11길 20-16',
 '연서로15길 26-1',
 '갈현로11가길 13-3',
 '갈현로15길 24-12',
 '갈현로11가길 13-13',
 '갈현로11가길 13-5',
 '연서로11길 20-14',
 '서오릉로25가길 2',
 '연서로13길 35',
 '갈현로17나길 16-1',
 '갈현로17가길 15-1',
 '갈현로11가길 18',
 '연서로15길 12-1',
 '서오릉로27길 22-1',
 '갈현로16길 3-4',
 '연서로11길 13',
 '서오릉로25길 11',
 '갈현로17가길 11',
 '갈현로 139-1',
 '서오릉로13길 24-1',
 '서오릉로27길 24',
 '갈현로17나길 17',
 '서오릉로13길 10-1',
 '서오릉로15길 5-4',
 '서오릉로23길 13',
 '진흥로16길 2-1',
 '녹번로 33-18',
 '녹번로 33-20',
 '진흥로12가길 8-59',
 '진흥로12나길 9',
 '서오릉로6가길 2',
 '녹번로 45-10',
 '서오릉로4길 14',
 '녹번로3길 23',
 '은평로21길 3-6',
 '녹번로7길 12-3',
 '녹번로 45-7',
 '녹번로4길 9',
 '통일로57길 6-4',
 '녹번로1길 26-1',
 '녹번로 64',
 '은평로21길 20-1',
 '진흥로 138-20',
 '은평로21가길 17',
 '서오릉로6길 18',
 '서오릉로6길 24-1',
 '서오릉로6가길 3',
 '서오릉로2길 13-7',
 '은평로13길 21-2',
 '은평로21길 10-6',
 '녹번로7길 17-4',
 '은평로11길 35-1',
 '통일로63길 11-3',
 '녹번로 37-13',
 '녹번로3가길 12',
 '통일로 647-2',
 '통일로53길 17-1',
 '통일로63길 6-1',
 '통일로65길 3-6',
 '통일로73길 25-8',
 '서오릉로10길 17-21',
 '진흥로 153-10',
 '통일로71길 32-6',
 '서오릉로 128-16',
 '서오릉로10길 13-14',
 '진흥로11길 8-15',
 '통일로69길 28-40',
 '통일로71가길 13-12',
 '역말로10가길 4-33',
 '역말로10가길 4-36',
 '역말로10가길 4-38',
 '역말로10가길 4-42',
 '역말로10길 23',
 '역말로10길 3-15',
 '역말로10길 3-11',
 '역말로10길 3-7',
 '역말로10길 3-1',
 '역말로10가길 5-1',
 '역말로10길 3-4',
 '역말로10가길 9-3',
 '역말로10길 1-14',
 '통일로71가길 27-10',
 '역말로10가길 4-13',
 '역말로10가길 10',
 '역말로 142',
 '역말로 152',
 '통일로71가길 16-1',
 '서오릉로10길 7',
 '역말로10길 18',
 ...]

In [35]:
# 주소 검색 함수 정의
def address_to_latlon(address):
    url = "https://dapi.kakao.com/v2/local/search/address.json?&query=" + address
    result = requests.get(urlparse(url).geturl(),
                          headers={"Authorization":"KakaoAK *****"})
    json_obj = result.json()
    global val   # 전역 변수를 지역 범위에서 사용하고 싶을 경우
    for document in json_obj['documents']:
        # 값이 NoneType 일 경우의 오류 방지
        try:
            val = [document['y'], document['x']]
        except:
            val = [0, 0]
    return val

In [36]:
# 주소 검색 함수 적용
address_to_latlon('보문로13라길 10-13')

['37.5790596886227', '127.020987493201']

In [37]:
# 주소 검색 함수 반복 적용
list2 = []
for i in add_list2:
    list2.append(address_to_latlon(i))

In [38]:
data5 = pd.DataFrame(add_list2, columns=['도로명'])
data5.head()

              도로명
0   보문로13라길 10-13
1       보문사길 88-4
2      삼선교로10바길 8
3   삼선교로10바길 27-1
4  삼선교로16가길 38-15

In [39]:
data6 = pd.DataFrame(list2, columns=['위도','경도'])
data6.head()

                 위도                경도
0  37.5790596886227  127.020987493201
1  37.5816202295665  127.017643334937
2  37.5853819042383  127.009596640254
3  37.5845155127268  127.009553732874
4  37.5839344157253  127.012032646433

In [40]:
data7 = pd.concat([data5, data6], axis=1)
data7.head()

              도로명                위도                경도
0   보문로13라길 10-13  37.5790596886227  127.020987493201
1       보문사길 88-4  37.5816202295665  127.017643334937
2      삼선교로10바길 8  37.5853819042383  127.009596640254
3   삼선교로10바길 27-1  37.5845155127268  127.009553732874
4  삼선교로16가길 38-15  37.5839344157253  127.012032646433

In [41]:
data7.to_csv('data/연립_위도경도(2).csv', index=False)

In [42]:
연립_data1 = pd.read_csv('data/연립_위도경도(1).csv')
연립_data1.head()

          도로명         위도          경도
0      논현로 10  37.472388  127.050511
1    논현로2길 66  37.474544  127.055084
2  논현로8길 62-1  37.474544  127.055084
3    논현로8길 63  37.475313  127.053546
4   개포로26길 16  37.478034  127.049109

In [43]:
연립_data2 = pd.read_csv('data/연립_위도경도(2).csv')
연립_data2.head()

              도로명         위도          경도
0   보문로13라길 10-13  37.579060  127.020987
1       보문사길 88-4  37.581620  127.017643
2      삼선교로10바길 8  37.585382  127.009597
3   삼선교로10바길 27-1  37.584516  127.009554
4  삼선교로16가길 38-15  37.583934  127.012033

In [44]:
total_data = pd.concat([연립_data1, 연립_data2])
print(len(total_data))
total_data.head()

82435

          도로명         위도          경도
0      논현로 10  37.472388  127.050511
1    논현로2길 66  37.474544  127.055084
2  논현로8길 62-1  37.474544  127.055084
3    논현로8길 63  37.475313  127.053546
4   개포로26길 16  37.478034  127.049109

In [45]:
total_data.to_csv('data/연립_위도경도.csv', index=False)

In [4]:
data = pd.read_csv('data/연립(전월세).csv')
data.head()

,시군구,번지,본번,부번,건물명,전월세구분,전용면적(㎡),계약년월,계약일,보증금(만원),월세(만원),층,건축년도,도로명
0,서울특별시 강남구 개포동,1163-4,1163,4,(1163-4),월세,13.56,201910,26,"1,000",50,4.0,2013.0,논현로 10
1,서울특별시 강남구 개포동,1163-4,1163,4,(1163-4),전세,21.88,202002,27,"16,000",0,5.0,2013.0,논현로 10
2,서울특별시 강남구 개포동,1163-4,1163,4,(1163-4),월세,13.56,202007,9,"6,000",25,2.0,2013.0,논현로 10
3,서울특별시 강남구 개포동,1163-4,1163,4,(1163-4),월세,13.56,202007,17,"3,000",40,2.0,2013.0,논현로 10
4,서울특별시 강남구 개포동,1163-4,1163,4,(1163-4),월세,13.56,202008,5,"1,000",50,2.0,2013.0,논현로 10

In [6]:
list1 = []
for i in range(len(data)):
    if '서울특별시' not in data['시군구'][i]:
        list1.append(i)
len(list1)

0

In [7]:
list1

[]

In [8]:
data['시군구'].unique()

array(['서울특별시 강남구 개포동', '서울특별시 강남구 논현동', '서울특별시 강남구 대치동', '서울특별시 강남구 도곡동',
       '서울특별시 강남구 삼성동', '서울특별시 강남구 세곡동', '서울특별시 강남구 신사동', '서울특별시 강남구 역삼동',
       '서울특별시 강남구 율현동', '서울특별시 강남구 일원동', '서울특별시 강남구 자곡동', '서울특별시 강남구 청담동',
       '서울특별시 강동구 강일동', '서울특별시 강동구 고덕동', '서울특별시 강동구 길동', '서울특별시 강동구 둔촌동',
       '서울특별시 강동구 명일동', '서울특별시 강동구 상일동', '서울특별시 강동구 성내동', '서울특별시 강동구 암사동',
       '서울특별시 강동구 천호동', '서울특별시 강북구 미아동', '서울특별시 강북구 번동', '서울특별시 강북구 수유동',
       '서울특별시 강북구 우이동', '서울특별시 강서구 가양동', '서울특별시 강서구 개화동', '서울특별시 강서구 공항동',
       '서울특별시 강서구 내발산동', '서울특별시 강서구 등촌동', '서울특별시 강서구 마곡동',
       '서울특별시 강서구 방화동', '서울특별시 강서구 염창동', '서울특별시 강서구 외발산동',
       '서울특별시 강서구 화곡동', '서울특별시 관악구 남현동', '서울특별시 관악구 봉천동', '서울특별시 관악구 신림동',
       '서울특별시 광진구 광장동', '서울특별시 광진구 구의동', '서울특별시 광진구 군자동', '서울특별시 광진구 능동',
       '서울특별시 광진구 자양동', '서울특별시 광진구 중곡동', '서울특별시 광진구 화양동',
       '서울특별시 구로구 가리봉동', '서울특별시 구로구 개봉동', '서울특별시 구로구 고척동',
       '서울특별시 구로구 구로동', '서울특별시 구로구 궁동', '서울특별시 구로구 신도림동', '서울특별시 구로구 오류동',
       '서울특별시 구로구 온수동', '서울특별시 구로구 천왕동', '서울특별시 구로구 항동', '서울특별시 금천구 가산동',
       '서울특별시 금천구 독산동', '서울특별시 금천구 시흥동', '서울특별시 노원구 공릉동', '서울특별시 노원구 상계동',
       '서울특별시 노원구 월계동', '서울특별시 노원구 중계동', '서울특별시 노원구 하계동', '서울특별시 도봉구 도봉동',
       '서울특별시 도봉구 방학동', '서울특별시 도봉구 쌍문동', '서울특별시 도봉구 창동',
       '서울특별시 동대문구 답십리동', '서울특별시 동대문구 신설동', '서울특별시 동대문구 용두동',
       '서울특별시 동대문구 이문동', '서울특별시 동대문구 장안동', '서울특별시 동대문구 전농동',
       '서울특별시 동대문구 제기동', '서울특별시 동대문구 청량리동', '서울특별시 동대문구 회기동',
       '서울특별시 동대문구 휘경동', '서울특별시 동작구 노량진동', '서울특별시 동작구 대방동',
       '서울특별시 동작구 동작동', '서울특별시 동작구 본동', '서울특별시 동작구 사당동', '서울특별시 동작구 상도1동',
       '서울특별시 동작구 상도동', '서울특별시 동작구 신대방동', '서울특별시 동작구 흑석동',
       '서울특별시 마포구 공덕동', '서울특별시 마포구 구수동', '서울특별시 마포구 노고산동',
       '서울특별시 마포구 당인동', '서울특별시 마포구 대흥동', '서울특별시 마포구 도화동', '서울특별시 마포구 동교동',
       '서울특별시 마포구 마포동', '서울특별시 마포구 망원동', '서울특별시 마포구 상수동', '서울특별시 마포구 상암동',
       '서울특별시 마포구 서교동', '서울특별시 마포구 성산동', '서울특별시 마포구 신공덕동',
       '서울특별시 마포구 신수동', '서울특별시 마포구 아현동', '서울특별시 마포구 연남동', '서울특별시 마포구 염리동',
       '서울특별시 마포구 용강동', '서울특별시 마포구 중동', '서울특별시 마포구 창전동', '서울특별시 마포구 토정동',
       '서울특별시 마포구 하중동', '서울특별시 마포구 합정동', '서울특별시 마포구 현석동',
       '서울특별시 서대문구 남가좌동', '서울특별시 서대문구 냉천동', '서울특별시 서대문구 대신동',
       '서울특별시 서대문구 대현동', '서울특별시 서대문구 북가좌동', '서울특별시 서대문구 북아현동',
       '서울특별시 서대문구 신촌동', '서울특별시 서대문구 연희동', '서울특별시 서대문구 영천동',
       '서울특별시 서대문구 옥천동', '서울특별시 서대문구 창천동', '서울특별시 서대문구 천연동',
       '서울특별시 서대문구 충정로2가', '서울특별시 서대문구 충정로3가', '서울특별시 서대문구 홍은동',
       '서울특별시 서대문구 홍제동', '서울특별시 서초구 내곡동', '서울특별시 서초구 반포동',
       '서울특별시 서초구 방배동', '서울특별시 서초구 서초동', '서울특별시 서초구 신원동', '서울특별시 서초구 양재동',
       '서울특별시 서초구 염곡동', '서울특별시 서초구 우면동', '서울특별시 서초구 잠원동',
       '서울특별시 성동구 금호동1가', '서울특별시 성동구 금호동2가', '서울특별시 성동구 금호동3가',
       '서울특별시 성동구 금호동4가', '서울특별시 성동구 도선동', '서울특별시 성동구 마장동',
       '서울특별시 성동구 사근동', '서울특별시 성동구 성수동1가', '서울특별시 성동구 성수동2가',
       '서울특별시 성동구 송정동', '서울특별시 성동구 옥수동', '서울특별시 성동구 용답동', '서울특별시 성동구 응봉동',
       '서울특별시 성동구 하왕십리동', '서울특별시 성동구 행당동', '서울특별시 성동구 홍익동',
       '서울특별시 성북구 길음동', '서울특별시 성북구 돈암동', '서울특별시 성북구 동선동1가',
       '서울특별시 성북구 동선동2가', '서울특별시 성북구 동선동3가', '서울특별시 성북구 동선동4가',
       '서울특별시 성북구 동선동5가', '서울특별시 성북구 동소문동1가', '서울특별시 성북구 동소문동4가',
       '서울특별시 성북구 동소문동6가', '서울특별시 성북구 동소문동7가', '서울특별시 성북구 보문동1가',
       '서울특별시 성북구 보문동2가', '서울특별시 성북구 보문동3가', '서울특별시 성북구 보문동4가',
       '서울특별시 성북구 보문동5가', '서울특별시 성북구 보문동6가', '서울특별시 성북구 보문동7가',
       '서울특별시 성북구 삼선동1가', '서울특별시 성북구 삼선동2가', '서울특별시 성북구 삼선동3가',
       '서울특별시 성북구 삼선동4가', '서울특별시 성북구 삼선동5가', '서울특별시 성북구 상월곡동',
       '서울특별시 성북구 석관동', '서울특별시 성북구 성북동', '서울특별시 성북구 성북동1가',
       '서울특별시 성북구 안암동1가', '서울특별시 성북구 안암동2가', '서울특별시 성북구 안암동3가',
       '서울특별시 성북구 안암동4가', '서울특별시 성북구 안암동5가', '서울특별시 성북구 장위동',
       '서울특별시 성북구 정릉동', '서울특별시 성북구 종암동', '서울특별시 성북구 하월곡동',
       '서울특별시 송파구 가락동', '서울특별시 송파구 거여동', '서울특별시 송파구 마천동', '서울특별시 송파구 문정동',
       '서울특별시 송파구 방이동', '서울특별시 송파구 삼전동', '서울특별시 송파구 석촌동', '서울특별시 송파구 송파동',
       '서울특별시 송파구 오금동', '서울특별시 송파구 잠실동', '서울특별시 송파구 풍납동', '서울특별시 양천구 목동',
       '서울특별시 양천구 신월동', '서울특별시 양천구 신정동', '서울특별시 영등포구 당산동',
       '서울특별시 영등포구 당산동1가', '서울특별시 영등포구 당산동2가', '서울특별시 영등포구 당산동3가',
       '서울특별시 영등포구 당산동4가', '서울특별시 영등포구 당산동5가', '서울특별시 영등포구 당산동6가',
       '서울특별시 영등포구 대림동', '서울특별시 영등포구 도림동', '서울특별시 영등포구 문래동1가',
       '서울특별시 영등포구 문래동3가', '서울특별시 영등포구 신길동', '서울특별시 영등포구 양평동1가',
       '서울특별시 영등포구 양평동2가', '서울특별시 영등포구 양평동3가', '서울특별시 영등포구 양평동4가',
       '서울특별시 영등포구 양평동5가', '서울특별시 영등포구 양평동6가', '서울특별시 영등포구 영등포동',
       '서울특별시 영등포구 영등포동1가', '서울특별시 영등포구 영등포동2가', '서울특별시 영등포구 영등포동4가',
       '서울특별시 영등포구 영등포동5가', '서울특별시 영등포구 영등포동6가', '서울특별시 영등포구 영등포동7가',
       '서울특별시 영등포구 영등포동8가', '서울특별시 용산구 갈월동', '서울특별시 용산구 남영동',
       '서울특별시 용산구 도원동', '서울특별시 용산구 동빙고동', '서울특별시 용산구 동자동',
       '서울특별시 용산구 문배동', '서울특별시 용산구 보광동', '서울특별시 용산구 산천동', '서울특별시 용산구 서계동',
       '서울특별시 용산구 서빙고동', '서울특별시 용산구 신계동', '서울특별시 용산구 신창동',
       '서울특별시 용산구 용문동', '서울특별시 용산구 용산동2가', '서울특별시 용산구 용산동3가',
       '서울특별시 용산구 원효로1가', '서울특별시 용산구 원효로2가', '서울특별시 용산구 원효로3가',
       '서울특별시 용산구 원효로4가', '서울특별시 용산구 이촌동', '서울특별시 용산구 이태원동',
       '서울특별시 용산구 주성동', '서울특별시 용산구 청파동1가', '서울특별시 용산구 청파동2가',
       '서울특별시 용산구 청파동3가', '서울특별시 용산구 한강로1가', '서울특별시 용산구 한강로2가',
       '서울특별시 용산구 한강로3가', '서울특별시 용산구 한남동', '서울특별시 용산구 효창동',
       '서울특별시 용산구 후암동', '서울특별시 은평구 갈현동', '서울특별시 은평구 구산동', '서울특별시 은평구 녹번동',
       '서울특별시 은평구 대조동', '서울특별시 은평구 불광동', '서울특별시 은평구 수색동', '서울특별시 은평구 신사동',
       '서울특별시 은평구 역촌동', '서울특별시 은평구 응암동', '서울특별시 은평구 증산동', '서울특별시 은평구 진관동',
       '서울특별시 종로구 가회동', '서울특별시 종로구 계동', '서울특별시 종로구 구기동', '서울특별시 종로구 내수동',
       '서울특별시 종로구 누상동', '서울특별시 종로구 누하동', '서울특별시 종로구 동숭동',
       '서울특별시 종로구 명륜1가', '서울특별시 종로구 명륜2가', '서울특별시 종로구 명륜3가',
       '서울특별시 종로구 명륜4가', '서울특별시 종로구 무악동', '서울특별시 종로구 부암동',
       '서울특별시 종로구 사직동', '서울특별시 종로구 삼청동', '서울특별시 종로구 숭인동', '서울특별시 종로구 신교동',
       '서울특별시 종로구 신문로2가', '서울특별시 종로구 신영동', '서울특별시 종로구 안국동',
       '서울특별시 종로구 연건동', '서울특별시 종로구 연지동', '서울특별시 종로구 옥인동', '서울특별시 종로구 운니동',
       '서울특별시 종로구 원서동', '서울특별시 종로구 이화동', '서울특별시 종로구 창성동', '서울특별시 종로구 창신동',
       '서울특별시 종로구 청운동', '서울특별시 종로구 체부동', '서울특별시 종로구 통의동', '서울특별시 종로구 통인동',
       '서울특별시 종로구 평창동', '서울특별시 종로구 필운동', '서울특별시 종로구 행촌동', '서울특별시 종로구 혜화동',
       '서울특별시 종로구 홍지동', '서울특별시 종로구 홍파동', '서울특별시 종로구 효자동',
       '서울특별시 중구 광희동2가', '서울특별시 중구 만리동1가', '서울특별시 중구 만리동2가',
       '서울특별시 중구 무학동', '서울특별시 중구 묵정동', '서울특별시 중구 신당동', '서울특별시 중구 쌍림동',
       '서울특별시 중구 예장동', '서울특별시 중구 을지로6가', '서울특별시 중구 장충동1가',
       '서울특별시 중구 장충동2가', '서울특별시 중구 중림동', '서울특별시 중구 필동2가', '서울특별시 중구 필동3가',
       '서울특별시 중구 황학동', '서울특별시 중구 회현동1가', '서울특별시 중랑구 망우동', '서울특별시 중랑구 면목동',
       '서울특별시 중랑구 묵동', '서울특별시 중랑구 상봉동', '서울특별시 중랑구 신내동', '서울특별시 중랑구 중화동',
       '서울특별시 서대문구 합동', '서울특별시 성동구 상왕십리동', '서울특별시 종로구 충신동',
       '서울특별시 중구 남산동2가', '서울특별시 중구 남창동', '서울특별시 서초구 원지동',
       '서울특별시 중구 회현동2가', '서울특별시 종로구 관철동', '서울특별시 서대문구 봉원동',
       '서울특별시 영등포구 영등포동3가'], dtype=object)