<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#대형마트-중복-행-확인" data-toc-modified-id="대형마트-중복-행-확인-1">대형마트 중복 행 확인</a></span></li><li><span><a href="#대형마트-중복-행-제거" data-toc-modified-id="대형마트-중복-행-제거-2">대형마트 중복 행 제거</a></span></li><li><span><a href="#기준(부동산-위도경도)별-대형마트-수" data-toc-modified-id="기준(부동산-위도경도)별-대형마트-수-3">기준(부동산 위도경도)별 대형마트 수</a></span></li><li><span><a href="#패스트푸드-중복-행-확인" data-toc-modified-id="패스트푸드-중복-행-확인-4">패스트푸드 중복 행 확인</a></span></li><li><span><a href="#패스트푸드-중복-행-제거" data-toc-modified-id="패스트푸드-중복-행-제거-5">패스트푸드 중복 행 제거</a></span></li><li><span><a href="#기준(부동산-위도경도)별-패스트푸드점-수" data-toc-modified-id="기준(부동산-위도경도)별-패스트푸드점-수-6">기준(부동산 위도경도)별 패스트푸드점 수</a></span></li><li><span><a href="#편의점-중복-행-확인" data-toc-modified-id="편의점-중복-행-확인-7">편의점 중복 행 확인</a></span></li><li><span><a href="#편의점-중복-행-제거" data-toc-modified-id="편의점-중복-행-제거-8">편의점 중복 행 제거</a></span></li><li><span><a href="#기준(부동산-위도경도)별-편의점-수" data-toc-modified-id="기준(부동산-위도경도)별-편의점-수-9">기준(부동산 위도경도)별 편의점 수</a></span></li></ul></div>

In [95]:
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings(action='ignore')

In [96]:
단독다가구 = pd.read_csv('data/단독다가구_위도경도.csv')
print(단독다가구.shape)
단독다가구.head()

(12342, 3)

      도로명         위도          경도
0   논현로6길  37.473561  127.050895
1  논현로18길  37.477885  127.046338
2  개포로20길  37.477040  127.048356
3  선릉로12길  37.483899  127.060991
4   논현로8길  37.474467  127.051458

In [99]:
단독다가구['경도'] = 단독다가구['경도'].astype(str)
단독다가구['위도'] = 단독다가구['위도'].astype(str)
단독다가구['기준'] = 단독다가구['위도'] + 단독다가구['경도']

In [100]:
단독다가구.head()

,도로명,위도,경도,기준
0,논현로6길,37.4735609971211,127.050895232485,37.4735609971211127.050895232485
1,논현로18길,37.4778848357129,127.046338152861,37.4778848357129127.046338152861
2,개포로20길,37.477039601042,127.048356001948,37.477039601042127.048356001948
3,선릉로12길,37.4838993527963,127.060991290466,37.4838993527963127.060991290466
4,논현로8길,37.474467349626295,127.05145805033301,37.474467349626295127.05145805033301

In [101]:
연립 = pd.read_csv('data/연립_위도경도.csv')
print(연립.shape)
연립.head()

(82435, 3)

          도로명         위도          경도
0      논현로 10  37.472388  127.050511
1    논현로2길 66  37.474544  127.055084
2  논현로8길 62-1  37.474544  127.055084
3    논현로8길 63  37.475313  127.053546
4   개포로26길 16  37.478034  127.049109

In [102]:
연립['경도'] = 연립['경도'].astype(str)
연립['위도'] = 연립['위도'].astype(str)
연립['기준'] = 연립['위도'] + 연립['경도']

In [103]:
연립.head()

,도로명,위도,경도,기준
0,논현로 10,37.4723876864126,127.050510865064,37.4723876864126127.050510865064
1,논현로2길 66,37.4745435620733,127.055084221135,37.4745435620733127.055084221135
2,논현로8길 62-1,37.4745435620733,127.055084221135,37.4745435620733127.055084221135
3,논현로8길 63,37.475312650290796,127.05354614244301,37.475312650290796127.05354614244301
4,개포로26길 16,37.4780340050176,127.049108807588,37.4780340050176127.049108807588

In [104]:
오피스텔 = pd.read_csv('data/오피스텔_위도경도.csv')
print(오피스텔.shape)
오피스텔.head()

(3462, 3)

            도로명         위도          경도
0       개포로 213  37.478745  127.046113
1       개포로 623  37.494341  127.079648
2  논현로18길 10-10  37.477252  127.046084
3   선릉로129길 3-4  37.516104  127.041071
4    도산대로46길 11  37.521292  127.036652

In [105]:
오피스텔['경도'] = 오피스텔['경도'].astype(str)
오피스텔['위도'] = 오피스텔['위도'].astype(str)
오피스텔['기준'] = 오피스텔['위도'] + 오피스텔['경도']

In [106]:
오피스텔.head()

,도로명,위도,경도,기준
0,개포로 213,37.4787447572028,127.046112568695,37.4787447572028127.046112568695
1,개포로 623,37.494341198165,127.07964775319401,37.494341198165127.07964775319401
2,논현로18길 10-10,37.477252336419,127.04608384006399,37.477252336419127.04608384006399
3,선릉로129길 3-4,37.51610414689579,127.041071323525,37.51610414689579127.041071323525
4,도산대로46길 11,37.521291505069,127.03665223786601,37.521291505069127.03665223786601

In [107]:
부동산 = pd.concat([단독다가구, 연립, 오피스텔]).reset_index(drop=True)
print(부동산.shape)
부동산.head()

(98239, 4)

,도로명,위도,경도,기준
0,논현로6길,37.4735609971211,127.050895232485,37.4735609971211127.050895232485
1,논현로18길,37.4778848357129,127.046338152861,37.4778848357129127.046338152861
2,개포로20길,37.477039601042,127.048356001948,37.477039601042127.048356001948
3,선릉로12길,37.4838993527963,127.060991290466,37.4838993527963127.060991290466
4,논현로8길,37.474467349626295,127.05145805033301,37.474467349626295127.05145805033301

In [108]:
대형마트 = pd.read_csv('편의시설/300m내_대형마트.csv')
print(대형마트.shape)
대형마트.head()

(28348, 7)

,경도,위도,장소명,도로명,편의시설_경도,편의시설_위도,주택형태
0,127.060991,37.483899,GS수퍼마켓 개포블레스티지점,서울 강남구 선릉로 8,127.062217,37.482159,단독다가구
1,127.060694,37.484075,GS수퍼마켓 개포블레스티지점,서울 강남구 선릉로 8,127.062217,37.482159,단독다가구
2,127.061118,37.483602,GS수퍼마켓 개포블레스티지점,서울 강남구 선릉로 8,127.062217,37.482159,단독다가구
3,127.061983,37.483285,GS수퍼마켓 개포블레스티지점,서울 강남구 선릉로 8,127.062217,37.482159,단독다가구
4,127.060078,37.483999,GS수퍼마켓 개포블레스티지점,서울 강남구 선릉로 8,127.062217,37.482159,단독다가구

In [109]:
대형마트['경도'] = 대형마트['경도'].astype(str)
대형마트['위도'] = 대형마트['위도'].astype(str)
대형마트['기준'] = 대형마트['위도'] + 대형마트['경도']

In [110]:
대형마트.head()

,경도,위도,장소명,도로명,편의시설_경도,편의시설_위도,주택형태,기준
0,127.060991290466,37.4838993527963,GS수퍼마켓 개포블레스티지점,서울 강남구 선릉로 8,127.062217,37.482159,단독다가구,37.4838993527963127.060991290466
1,127.060693844398,37.4840747521106,GS수퍼마켓 개포블레스티지점,서울 강남구 선릉로 8,127.062217,37.482159,단독다가구,37.4840747521106127.060693844398
2,127.06111847254499,37.4836015938737,GS수퍼마켓 개포블레스티지점,서울 강남구 선릉로 8,127.062217,37.482159,단독다가구,37.4836015938737127.06111847254499
3,127.06198259187599,37.4832847996201,GS수퍼마켓 개포블레스티지점,서울 강남구 선릉로 8,127.062217,37.482159,단독다가구,37.4832847996201127.06198259187599
4,127.06007757611201,37.4839988417672,GS수퍼마켓 개포블레스티지점,서울 강남구 선릉로 8,127.062217,37.482159,단독다가구,37.4839988417672127.06007757611201

## 대형마트 중복 행 확인

In [111]:
대형마트[대형마트.duplicated()]

,경도,위도,장소명,도로명,편의시설_경도,편의시설_위도,주택형태,기준
121,127.062509883909,37.5003328401756,롯데슈퍼 대치점,서울 강남구 도곡로 515,127.062719,37.499777,단독다가구,37.5003328401756127.062509883909
179,127.03238284485901,37.4920771229315,노브랜드 강남역삼점,서울 강남구 강남대로 324,127.030893,37.492025,단독다가구,37.4920771229315127.03238284485901
180,127.03238284485901,37.4920771229315,이마트에브리데이 역삼점,서울 강남구 역삼로 124,127.033264,37.493842,단독다가구,37.4920771229315127.03238284485901
191,127.03402378517,37.493727667287395,이마트에브리데이 역삼점,서울 강남구 역삼로 124,127.033264,37.493842,단독다가구,37.493727667287395127.03402378517
192,127.03402378517,37.493727667287395,롯데슈퍼 역삼3점,서울 강남구 역삼로 153,127.036017,37.495028,단독다가구,37.493727667287395127.03402378517
...,...,...,...,...,...,...,...,...
27872,127.021305262132,37.5702864662261,이마트 청계천점,서울 중구 청계천로 400,127.021800,37.571348,오피스텔,37.5702864662261127.021305262132
27873,127.021305262132,37.5702864662261,이마트 청계천점,서울 중구 청계천로 400,127.021800,37.571348,오피스텔,37.5702864662261127.021305262132
27877,127.08677277871901,37.5958857899922,동서울농협,서울 중랑구 망우로 288-1,127.084499,37.595839,오피스텔,37.5958857899922127.08677277871901
27882,127.079733398613,37.5929815440002,롯데슈퍼 상봉점,서울 중랑구 망우로32길 23,127.076892,37.592863,오피스텔,37.5929815440002127.079733398613
27930,126.90319711416299,37.4789637705931,관악농협하나로마트,서울 관악구 남부순환로 1369,126.902678,37.480018,오피스텔,37.4789637705931126.90319711416299

In [112]:
부동산[부동산['기준']=='37.5003328401756127.062509883909']

,도로명,위도,경도,기준
202,삼성로64길,37.5003328401756,127.062509883909,37.5003328401756127.062509883909
277,삼성로,37.5003328401756,127.062509883909,37.5003328401756127.062509883909

In [113]:
부동산[부동산['기준']=='37.493727667287395127.03402378517']

,도로명,위도,경도,기준
182,역삼로,37.493727667287395,127.03402378517,37.493727667287395127.03402378517
463,역삼로10길,37.493727667287395,127.03402378517,37.493727667287395127.03402378517

## 대형마트 중복 행 제거

In [114]:
대형마트 = 대형마트.drop(대형마트[대형마트.duplicated()].index, axis=0).reset_index(drop=True)   # drop_duplicates()
print(대형마트.shape)
대형마트.head()

(27536, 8)

,경도,위도,장소명,도로명,편의시설_경도,편의시설_위도,주택형태,기준
0,127.060991290466,37.4838993527963,GS수퍼마켓 개포블레스티지점,서울 강남구 선릉로 8,127.062217,37.482159,단독다가구,37.4838993527963127.060991290466
1,127.060693844398,37.4840747521106,GS수퍼마켓 개포블레스티지점,서울 강남구 선릉로 8,127.062217,37.482159,단독다가구,37.4840747521106127.060693844398
2,127.06111847254499,37.4836015938737,GS수퍼마켓 개포블레스티지점,서울 강남구 선릉로 8,127.062217,37.482159,단독다가구,37.4836015938737127.06111847254499
3,127.06198259187599,37.4832847996201,GS수퍼마켓 개포블레스티지점,서울 강남구 선릉로 8,127.062217,37.482159,단독다가구,37.4832847996201127.06198259187599
4,127.06007757611201,37.4839988417672,GS수퍼마켓 개포블레스티지점,서울 강남구 선릉로 8,127.062217,37.482159,단독다가구,37.4839988417672127.06007757611201

In [115]:
대형마트.to_csv('편의시설/300m내_대형마트(중복제거).csv', index=False)

## 기준(부동산 위도경도)별 대형마트 수

In [116]:
대형마트.groupby(['기준'])['장소명'].count().sort_values(ascending=False)

기준
37.570835587390704126.84037558608699    6
37.56859908881621126.84275537747101     6
37.5960052612377127.087261864983        6
37.57060341173121126.84011708874701     6
37.57038662514126.840244784286          6
                                       ..
37.5606030082784127.031406412435        1
37.56060364767461126.927616127346       1
37.5606069839045127.03947340108299      1
37.560609415794794126.92776608678       1
33.2480661563758126.56068077601101      1
Name: 장소명, Length: 23610, dtype: int64

In [117]:
패스트푸드 = pd.read_csv('편의시설/300m내_패스트푸드.csv')
print(패스트푸드.shape)
패스트푸드.head()

(24126, 7)

,경도,위도,장소명,도로명,편의시설_경도,편의시설_위도,주택형태
0,127.060991,37.483899,롯데리아 개포점,서울 강남구 선릉로 26,127.061465,37.482201,단독다가구
1,127.060694,37.484075,롯데리아 개포점,서울 강남구 선릉로 26,127.061465,37.482201,단독다가구
2,127.045229,37.479780,써브웨이 포이사거리점,서울 강남구 논현로 84,127.045263,37.477526,단독다가구
3,127.046581,37.479855,써브웨이 포이사거리점,서울 강남구 논현로 84,127.045263,37.477526,단독다가구
4,127.045831,37.478206,써브웨이 포이사거리점,서울 강남구 논현로 84,127.045263,37.477526,단독다가구

In [118]:
패스트푸드['경도'] = 패스트푸드['경도'].astype(str)
패스트푸드['위도'] = 패스트푸드['위도'].astype(str)
패스트푸드['기준'] = 패스트푸드['위도'] + 패스트푸드['경도']

In [119]:
패스트푸드.head()

,경도,위도,장소명,도로명,편의시설_경도,편의시설_위도,주택형태,기준
0,127.060991290466,37.4838993527963,롯데리아 개포점,서울 강남구 선릉로 26,127.061465,37.482201,단독다가구,37.4838993527963127.060991290466
1,127.060693844398,37.4840747521106,롯데리아 개포점,서울 강남구 선릉로 26,127.061465,37.482201,단독다가구,37.4840747521106127.060693844398
2,127.04522930859699,37.479780087904295,써브웨이 포이사거리점,서울 강남구 논현로 84,127.045263,37.477526,단독다가구,37.479780087904295127.04522930859699
3,127.046580863676,37.4798545267632,써브웨이 포이사거리점,서울 강남구 논현로 84,127.045263,37.477526,단독다가구,37.4798545267632127.046580863676
4,127.04583050040199,37.4782063336653,써브웨이 포이사거리점,서울 강남구 논현로 84,127.045263,37.477526,단독다가구,37.4782063336653127.04583050040199

## 패스트푸드 중복 행 확인

In [120]:
패스트푸드[패스트푸드.duplicated()]

,경도,위도,장소명,도로명,편의시설_경도,편의시설_위도,주택형태,기준
104,127.062509883909,37.5003328401756,노브랜드버거 대치점,서울 강남구 도곡로 501,127.061013,37.499233,단독다가구,37.5003328401756127.062509883909
105,127.062509883909,37.5003328401756,KFC 대치동점,서울 강남구 도곡로 517,127.062959,37.499769,단독다가구,37.5003328401756127.062509883909
106,127.02956666435699,37.5070395191103,맘스터치 강남논현점,서울 강남구 강남대로120길 47,127.027194,37.507925,단독다가구,37.5070395191103127.02956666435699
138,127.08271792651199,37.490772902621,KFC 일원동점,서울 강남구 일원로 28,127.080414,37.491206,단독다가구,37.490772902621127.08271792651199
212,127.12535807815901,37.530403944015795,맥도날드 강동구청,서울 강동구 성내로 15,127.122531,37.530304,단독다가구,37.530403944015795127.12535807815901
...,...,...,...,...,...,...,...,...
23755,127.122110013915,37.482317757257796,버거킹 문정역점,서울 송파구 법원로8길 13,127.122532,37.484629,오피스텔,37.482317757257796127.122110013915
23756,127.122110013915,37.482317757257796,맘스터치 문정역점,서울 송파구 송파대로 167,127.122232,37.485016,오피스텔,37.482317757257796127.122110013915
23777,126.919970935009,37.6020950478394,써브웨이 응암점,서울 은평구 은평로 108,126.919673,37.599708,오피스텔,37.6020950478394126.919970935009
23825,126.90161082541401,37.467473503247106,버거킹 금천독산FS점,서울 금천구 시흥대로 388,126.898329,37.468132,오피스텔,37.467473503247106126.90161082541401
23978,127.05964171508002,37.611832843944,롯데리아 석관점,서울 성북구 돌곶이로 75,127.057570,37.610087,오피스텔,37.611832843944127.05964171508002

In [121]:
부동산[부동산['기준']=='37.5003328401756127.062509883909']

,도로명,위도,경도,기준
202,삼성로64길,37.5003328401756,127.062509883909,37.5003328401756127.062509883909
277,삼성로,37.5003328401756,127.062509883909,37.5003328401756127.062509883909

## 패스트푸드 중복 행 제거

In [122]:
패스트푸드 = 패스트푸드.drop(패스트푸드[패스트푸드.duplicated()].index, axis=0).reset_index(drop=True)   # drop_duplicates()
print(패스트푸드.shape)
패스트푸드.head()

(23474, 8)

,경도,위도,장소명,도로명,편의시설_경도,편의시설_위도,주택형태,기준
0,127.060991290466,37.4838993527963,롯데리아 개포점,서울 강남구 선릉로 26,127.061465,37.482201,단독다가구,37.4838993527963127.060991290466
1,127.060693844398,37.4840747521106,롯데리아 개포점,서울 강남구 선릉로 26,127.061465,37.482201,단독다가구,37.4840747521106127.060693844398
2,127.04522930859699,37.479780087904295,써브웨이 포이사거리점,서울 강남구 논현로 84,127.045263,37.477526,단독다가구,37.479780087904295127.04522930859699
3,127.046580863676,37.4798545267632,써브웨이 포이사거리점,서울 강남구 논현로 84,127.045263,37.477526,단독다가구,37.4798545267632127.046580863676
4,127.04583050040199,37.4782063336653,써브웨이 포이사거리점,서울 강남구 논현로 84,127.045263,37.477526,단독다가구,37.4782063336653127.04583050040199

In [123]:
패스트푸드.to_csv('편의시설/300m내_패스트푸드(중복제거).csv', index=False)

## 기준(부동산 위도경도)별 패스트푸드점 수

In [124]:
패스트푸드.groupby(['기준'])['장소명'].count().sort_values(ascending=False)

기준
37.61393199276971126.929610657786       8
37.6114977979985126.915480818535        6
35.8535169765623128.549377052773        6
37.6110328822877126.915473190131        6
37.6021824467851127.08042245533599      6
                                       ..
37.543229613619296126.83663370679899    1
37.5432203816097126.835500255779        1
37.5432155959501126.964930025938        1
37.5432066246139126.840379065572        1
33.5061298401656126.539246511365        1
Name: 장소명, Length: 18534, dtype: int64

In [125]:
편의점 = pd.read_csv('편의시설/300m_편의점.csv', index_col=0)
print(편의점.shape)
편의점.head()

(731523, 7)

,경도,위도,장소명,도로명,편의시설_경도,편의시설_위도,주거형태
0,127.050895,37.473561,GS25 양재구룡점,서울 서초구 논현로5길 18,127.048909,37.472115,단독다가구
1,127.050895,37.473561,GS25 개포영광점,서울 강남구 논현로4길 12,127.051224,37.472586,단독다가구
2,127.050895,37.473561,GS25 개포타운점,서울 강남구 논현로12길 13,127.049313,37.474735,단독다가구
3,127.050895,37.473561,GS25 포이한라점,서울 강남구 논현로4길 43,127.053211,37.474186,단독다가구
4,127.050895,37.473561,세븐일레븐 양재구룡점,서울 서초구 논현로11길 10,127.047798,37.473806,단독다가구

In [126]:
편의점['경도'] = 편의점['경도'].astype(str)
편의점['위도'] = 편의점['위도'].astype(str)
편의점['기준'] = 편의점['위도'] + 편의점['경도']

In [127]:
편의점.head()

,경도,위도,장소명,도로명,편의시설_경도,편의시설_위도,주거형태,기준
0,127.050895232485,37.4735609971211,GS25 양재구룡점,서울 서초구 논현로5길 18,127.048909,37.472115,단독다가구,37.4735609971211127.050895232485
1,127.050895232485,37.4735609971211,GS25 개포영광점,서울 강남구 논현로4길 12,127.051224,37.472586,단독다가구,37.4735609971211127.050895232485
2,127.050895232485,37.4735609971211,GS25 개포타운점,서울 강남구 논현로12길 13,127.049313,37.474735,단독다가구,37.4735609971211127.050895232485
3,127.050895232485,37.4735609971211,GS25 포이한라점,서울 강남구 논현로4길 43,127.053211,37.474186,단독다가구,37.4735609971211127.050895232485
4,127.050895232485,37.4735609971211,세븐일레븐 양재구룡점,서울 서초구 논현로11길 10,127.047798,37.473806,단독다가구,37.4735609971211127.050895232485

## 편의점 중복 행 확인

In [131]:
편의점[편의점.duplicated()]

,경도,위도,장소명,도로명,편의시설_경도,편의시설_위도,주거형태,기준
83,127.047651596997,37.47656965031409,GS25 개포럭키점,서울 강남구 개포로20길 12,127.047244,37.477915,단독다가구,37.47656965031409127.047651596997
84,127.047651596997,37.47656965031409,이마트24 포이사거리점,서울 강남구 개포로 202,127.044978,37.478107,단독다가구,37.47656965031409127.047651596997
85,127.047651596997,37.47656965031409,CU 개포대성점,서울 강남구 논현로16길 25,127.048139,37.477067,단독다가구,37.47656965031409127.047651596997
86,127.047651596997,37.47656965031409,이마트24 강남오픈로드점,서울 강남구 논현로16길 6,127.047071,37.476059,단독다가구,37.47656965031409127.047651596997
87,127.047651596997,37.47656965031409,GS25 포이점,서울 강남구 개포로22길 40,127.049369,37.476544,단독다가구,37.47656965031409127.047651596997
...,...,...,...,...,...,...,...,...
730409,127.062483041739,37.612921570209295,세븐일레븐 석계화랑로점,서울 성북구 화랑로40길 26,127.062932,37.613201,오피스텔,37.612921570209295127.062483041739
730410,127.062483041739,37.612921570209295,GS25 성북한천로점,서울 성북구 한천로 572,127.062998,37.610808,오피스텔,37.612921570209295127.062483041739
730411,127.062483041739,37.612921570209295,세븐일레븐 노벨리아시티,서울 성북구 화랑로 299,127.061021,37.613646,오피스텔,37.612921570209295127.062483041739
730412,127.062483041739,37.612921570209295,CU HD장삼주유소점,서울 성북구 화랑로 293,127.061002,37.613339,오피스텔,37.612921570209295127.062483041739
730413,127.062483041739,37.612921570209295,씨스페이스 석계역점,서울 성북구 한천로78길 71,127.064930,37.613546,오피스텔,37.612921570209295127.062483041739

In [132]:
부동산[부동산['기준']=='37.47656965031409127.047651596997']

Empty DataFrame
Columns: [도로명, 위도, 경도, 기준]
Index: []

## 편의점 중복 행 제거

In [133]:
편의점.drop_duplicates(inplace=True)

In [134]:
편의점

,경도,위도,장소명,도로명,편의시설_경도,편의시설_위도,주거형태,기준
0,127.050895232485,37.4735609971211,GS25 양재구룡점,서울 서초구 논현로5길 18,127.048909,37.472115,단독다가구,37.4735609971211127.050895232485
1,127.050895232485,37.4735609971211,GS25 개포영광점,서울 강남구 논현로4길 12,127.051224,37.472586,단독다가구,37.4735609971211127.050895232485
2,127.050895232485,37.4735609971211,GS25 개포타운점,서울 강남구 논현로12길 13,127.049313,37.474735,단독다가구,37.4735609971211127.050895232485
3,127.050895232485,37.4735609971211,GS25 포이한라점,서울 강남구 논현로4길 43,127.053211,37.474186,단독다가구,37.4735609971211127.050895232485
4,127.050895232485,37.4735609971211,세븐일레븐 양재구룡점,서울 서초구 논현로11길 10,127.047798,37.473806,단독다가구,37.4735609971211127.050895232485
...,...,...,...,...,...,...,...,...
731518,127.07854530363599,37.602057932739896,CU 중랑이화교제일점,서울 중랑구 중랑역로 87,127.077603,37.601213,오피스텔,37.602057932739896127.07854530363599
731519,127.07854530363599,37.602057932739896,GS25 중화제일점,서울 중랑구 동일로129길 16,127.078829,37.599569,오피스텔,37.602057932739896127.07854530363599
731520,127.07854530363599,37.602057932739896,GS25 중화다미소점,서울 중랑구 동일로136길 10,127.080212,37.602186,오피스텔,37.602057932739896127.07854530363599
731521,127.07854530363599,37.602057932739896,GS25 S중화역점,서울 중랑구 동일로 지하 797,127.079461,37.601781,오피스텔,37.602057932739896127.07854530363599
731522,127.07854530363599,37.602057932739896,미니편의점,서울 중랑구 봉화산로 42,127.078930,37.601468,오피스텔,37.602057932739896127.07854530363599

## 기준(부동산 위도경도)별 편의점 수

In [135]:
편의점.groupby(['기준'])['장소명'].count().sort_values(ascending=False)

기준
37.530365702832896126.848405781477     31
37.5731744494963126.998728082785       31
37.5303479354231126.848181583229       31
37.567092944029795127.022926379186     30
37.5460761336877127.07195136089899     30
                                       ..
37.4956649417126.816822221512           1
37.4956697289163126.818112825428        1
37.547337021615206127.101058390188      1
37.5914935926225126.902767686879        1
37.49094708197371127.15784020850201     1
Name: 장소명, Length: 65149, dtype: int64

- GS25, CU, 세븐일레븐, 이마트24, 미니스톱

In [136]:
list(편의점['장소명'].unique())

['GS25 양재구룡점',
 'GS25 개포영광점',
 'GS25 개포타운점',
 'GS25 포이한라점',
 '세븐일레븐 양재구룡점',
 'GS25 개포사랑점',
 'CU 포이대원점',
 '세븐일레븐 개포그린점',
 '세븐일레븐 세븐포이3호점',
 '프로토 포이점',
 '이마트24 포이사거리점',
 'GS25 개포럭키점',
 'CU 포이점',
 '미니스톱 양재점',
 'CU 개포대성점',
 '이마트24 강남오픈로드점',
 'GS25 양재트윈타워점',
 'GS25 강남개포점',
 '세븐일레븐 포이5호점',
 'GS25 개포미래점',
 '세븐일레븐 양재삼호점',
 '세븐일레븐 포이중앙점',
 'GS25 포이그린점',
 '세븐일레븐 포이4호점',
 '세븐일레븐 양재12호점',
 'GS25 포이점',
 '이마트24 강남개포점',
 '세븐일레븐 개포본점',
 'CU 개포사랑점',
 '세븐일레븐 개포1호점',
 '세븐일레븐 개포타운점',
 'GS25 도곡STX점',
 'CU 양재강남점',
 'CU 양재2동점',
 '세븐일레븐 개포현대점',
 '팝스토어',
 '이마트24 개포래미안점',
 '미니스톱 논현한바위점',
 'CU 강남논현타운점',
 'GS25 논현초교점',
 'GS25 논현미래점',
 'CU 논현혜성점',
 'GS25 논현이편한점',
 'GS25 논현영동시장점',
 'CU 논현광명점',
 'GS25 논현드림점',
 'CU 신논현역점',
 'GS25 논현평화점',
 '세븐일레븐 역삼보브점',
 'CU 강남거평타운점',
 'GS25 논현마루점',
 'CU 논현윤진점',
 'GS25 논현정노점',
 '이마트24 논현진성점',
 'CU 논현힐탑점',
 'CU 논현조이점',
 '이마트24 강남고개점',
 '미니스톱 논현힐탑점',
 '세븐일레븐 논현한영점',
 'GS25 논현한영점',
 'CU 논현한미점',
 'GS25 논현으뜸점',
 'GS25 힐탑점',
 'GS25 논현동부점',
 'GS25 S9언주역점',
 'TJ움직이는편의점',
 'CU 학동역점',
 'GS25 학동행복점',
 '세븐일레븐 학동점',
 'CU 논현세원점',
 'GS25 논현진실점',
 '이마트24 논현개나리점',
 'GS25 S학동역점',
 'GS25 논현동우점',
 'CU 논현아성점',
 '세븐일레븐 강남YMCA점',
 'GS25 논현경남점',
 'GS25 역삼영동점',
 '세븐일레븐 역삼해피점',
 '세븐일레븐 강남인텔렉스점',
 '더시가',
 '세븐일레븐 논현혜인점',
 '세븐일레븐 신논현강남점',
 'CU 논현평화점',
 'GS25 논현우람점',
 'GS25 논현삼익점',
 'GS25 논현금옥점',
 'CU 잠원성한점',
 'CU 논현동화점',
 '세븐일레븐 논현영동점',
 '세븐일레븐 논현12호점',
 'GS25 S논현역점',
 '세븐일레븐 논현학나래점',
 'CU 논현역드림점',
 'CU 논현두산위브점',
 '세븐일레븐 논현경복점',
 'CU 논현성원점',
 'GS25 논현영동점',
 'CU 논현우람점',
 '이마트24 논현세기점',
 'GS25 논현목련점',
 'CU 논현신우점',
 'GS25 논현타운점',
 '세븐일레븐 논현흥산점',
 'GS25 논현사랑점',
 '이마트24 R강남대로점',
 'CU 반포미소점',
 'GS25 논현대지본점',
 '세븐일레븐 반포공원점',
 'CU 논현학동점',
 'GS25 학동제일점',
 'GS25 논현동국점',
 '미니스톱 논현보람점',
 '세븐일레븐 논현4호점',
 'GS25 논현77점',
 'GS25 논현학동점',
 'CU 논현SK점',
 'GS25 논현보람점',
 'GS25 논현은선점',
 'GS25 삼성언주점',
 'GS25 삼성캐슬점',
 '미니스톱 논현행운점',
 'CU 강남삼성점',
 '세븐일레븐 논현제일점',
 'CU 논현LH점',
 '세븐일레븐 논현중앙점',
 '세븐일레븐 삼성동래미안점',
 'TJ움직이는편의점 삼성점',
 '삼성동래미안점',
 '세븐일레븐 논현한어울림점',
 '세븐일레븐 논현스타우스점',
 '이마트24 논현101점',
 'GS25 논현동현점',
 'CU 논현한진점',
 '세븐일레븐 강남학동점',
 'GS25 청담대로점',
 '세븐일레븐 논현6호점',
 '미니스톱 청담유시어터점',
 'CU 논현대승점',
 '세븐일레븐 학동사거리점',
 '이마트24 강남구청역점',
 'GS25 반포제일점',
 '세븐일레븐 논현스타점',
 'CU 신사성환점',
 'GS25 잠원주흥점',
 'GS25 논현행운점',
 '미니스톱 신사만남점',
 'GS25 논현스카이점',
 'GS25 신사대로점',
 'GS25 신사센터점',
 '미니스톱 강남신사점',
 'GS25 잠원사랑점',
 'GS25 G신사남서울점',
 '세븐일레븐 잠원제일점',
 'GS25 신사현대점',
 'GS25 잠원강남점',
 'GS25 학동공원점',
 'CU 신사렉스점',
 'CU 논현골드점',
 'GS25 논현누리점',
 '세븐일레븐 논현13호점',
 'CU 논현강남점',
 '세븐일레븐 논현11호점',
 '세븐일레븐 청담2점',
 'GS25 S강남구청역점',
 '주)코리아세븐-논현',
 '이마트24 선릉청운점',
 'CU 논현선정릉점',
 'CU 선정릉역점',
 '미니스톱 삼성플러스원점',
 'GS25 논현성암점',
 'GS25 삼성으뜸점',
 'CU 논현경복점',
 '미니스톱 논현삼릉역점',
 'CU 삼성럭키점',
 'GS25 논현파라곤점',
 'CU 논현세관사거리점',
 '세븐일레븐 논현건설회관점',
 '세븐일레븐 세관사거리점',
 '이마트24 뉴서울주유소점',
 'GS25 강남나누리점',
 '이마트24 논현청학점',
 '이마트24 도산대로점',
 '이마트24 R논현점',
 'GS25 압구정신사점',
 'GS25 신사중앙점',
 '세븐일레븐 논현타운점',
 'CU 신사중앙점',
 '세븐일레븐 논현학동공원점',
 '세븐일레븐 압구정칼릭스점',
 'CU 논현세일점',
 'GS25 반포중앙점',
 'CU 신논현타워점',
 'CU 역삼본점',
 '미니스톱 서초반포점',
 'GS25 강남센타점',
 'CU 역삼황제펭귄점',
 '이마트24 역삼휴먼터치빌점',
 '세븐일레븐 논현본점',
 'GS25 논현스타점',
 'GS25 차병원본점',
 'M마트',
 'GS25 신사제일점',
 'CU 논현영동점',
 '세븐일레븐 논현14호점',
 '세븐일레븐 신사대로점',
 'CU 논현학사점',
 'GS25 강남영동점',
 'CU 신사가로수길점',
 '세븐일레븐 신사4호점',
 '세븐일레븐 신사본점',
 'CU 논현APEX점',
 '(주)코리아세븐논현미성점',
 '세븐일레븐 잠원중앙점',
 'GS25 S신사역점',
 '그린편의점',
 'GS25 논현하니점',
 'CU 역삼목화점',
 '세븐일레븐 역삼선릉로점',
 '세븐일레븐 선릉스타점',
 'CU 역삼경복점',
 '세븐일레븐 역삼14호점',
 'GS25 역삼미소점',
 '세븐일레븐 거평타운점',
 'GS25 논현무궁화점',
 'GS25 역삼소망점',
 'CU 역삼역촌점',
 'GS25 역삼제일점',
 'GS25 강남리츠칼튼점',
 'GS25 신사진주점',
 '세븐일레븐 서초논현점',
 'CU 신사강남점',
 '미니스톱 신사제일점',
 'GS25 대치단국점',
 'GS25 대치중앙점',
 'GS25 대치에이스점',
 'CU 대치본점',
 'CU 대치타운점',
 '미니스톱 대치시내점',
 '세븐일레븐 대치공원점',
 'GS25 대치희망점',
 'GS25 한티단국점',
 '이마트24 대치삼성점',
 'CU 대치은마점',
 'CU 대치현대점',
 '세븐일레븐 대치본점',
 'CU 대치예영점',
 '세븐일레븐 대치한티점',
 'GS25 도곡초교점',
 'CU 대치샤인점',
 '베스티안편의점',
 'GS25 강남한티점',
 'CU 대치롯데점',
 'CU 대치태양점',
 'GS25 대치타운점',
 'GS25 대치사랑점',
 'GS25 대치제일점',
 '세븐일레븐 대치16호점',
 'CU 대치미니점',
 'CU 대치타운중앙점',
 '세븐일레븐 대치10호점',
 '세븐일레븐 대치삼성로점',
 '세븐일레븐 대치마루점',
 'T24',
 '이마트24 엔씨타워점',
 'CU 삼성본점',
 'CU 대치플러스점',
 '이마트24 대치휘문점',
 '세븐일레븐 대치7호점',
 'CU 대치메트로칸점',
 '세븐일레븐 대치6호점',
 'GS25 강남쥬비스점',
 '세븐일레븐 대치승리점',
 '세븐일레븐 대치으뜸점',
 'CU 강남해성점',
 '미니스톱 메트로칸점',
 '이마트24 포스코센터점',
 '세븐일레븐 포스코센터점',
 'K마트',
 'GS25 대치사거리점',
 'CU 대치세정점',
 '세븐일레븐 대치덕일점',
 '컬투편의점 대치점',
 '인더라인25 대치점',
 'GS25 대치골드점',
 '이마트24 대치타운점',
 'CU 대치동부점',
 'CU 대치예스점',
 'GS25 대치명문점',
 '미니스톱 대치멤버스점',
 '미니스톱 테헤란로점',
 'GS25 대치스카이점',
 '세븐일레븐 대치우성점',
 'GS25 대치은행점',
 'GS25 강남대치점',
 'GS25 대치타워점',
 'GS25 선릉로즈점',
 'GS25 대치미래점',
 'CU 대치금강점',
 'CU 대치한국점',
 '이마트24 위워크 마켓 선릉3호점',
 '세븐일레븐 역삼진선점',
 'GS25 R선릉7점',
 '미니스톱 골드로즈점',
 'GS25 대치삼성타운점',
 '세븐일레븐 대치은마사거리점',
 '세븐일레븐 강남SLI점',
 '세븐일레븐 강남롯데점',
 'CU 선릉역점',
 '세븐일레븐 L7강남점',
 'CU 대치우일점',
 'GS25 개나리SK점',
 '세븐일레븐 대치선릉로점',
 'CU 삼성1호점',
 'GS25 대치선릉점',
 'CU 대치삼성점',
 'GS25 대치은마점',
 '이마트24 대치은마점',
 'GS25 대치학원점',
 'CU 역삼센타점',
 'CU 역삼벚꽃길점',
 'GS25 역삼아워홈점',
 'GS25 역삼흑룡점',
 'GS25 역삼2점',
 'GS25 역삼행운점',
 '세븐일레븐 역삼5호점',
 '세븐일레븐 역삼특허점',
 '미니스톱 역삼만남점',
 'GS25 강남사랑점',
 '이마트24 역삼서희점',
 'GS25 역삼성우점',
 'GS25 역삼하나점',
 'GS25 역삼명진점',
 '365PLUS 역삼서희점',
 'GS25 대치대명점',
 'CU 삼성마젤란점',
 'CU 삼성위브점',
 '세븐일레븐 삼성페이토점',
 'GS25 대치SK타운점',
 'CU 대치역점',
 'GS25 대치래미안점',
 '이마트24 대치SK점',
 '세븐일레븐 대치4호점',
 'GS25 강남동원점',
 '세븐일레븐 대치나인점',
 'GS25 도곡렉슬점',
 '세븐일레븐 대치아이파크점',
 '세븐일레븐 도곡렉슬점',
 'GS25 대치은마타운점',
 'GS25 역삼대홍점',
 'GS25 역삼블루점',
 'GS25 도곡신호점',
 'CU 도곡아이파크점',
 '세븐일레븐 역삼웰스토어점',
 '세븐일레븐 강남도곡로점',
 'GS25 도곡럭키본점',
 '이마트24 R역삼윤이점',
 'GS25 도곡롯데점',
 '홈웨이 역삼점',
 '이마트24 서초위브점',
 'CU 양재디오빌점',
 'GS25 서초영동점',
 '미니스톱 도곡공원점',
 '이마트24 푸르덴셜타워점',
 '세븐일레븐 서초페이토점',
 'GS25 도곡푸른점',
 'CU 역삼푸른점',
 '세븐일레븐 역삼15호점',
 'CU 메인타워점',
 '세븐일레븐 도곡중앙점',
 '세븐일레븐 도곡3호점',
 '금화매점',
 'CU 양재점',
 'GS25 도곡양재점',
 'GS25 양재유진점',
 'GS25 도곡센터점',
 'CU 서초구청점',
 '세븐일레븐 서초테마점',
 '미니스톱 양재에이스점',
 '세븐일레븐 도곡스타점',
 'CU M양재역점',
 'GS25 S양재역1호점',
 'GS25 도곡점',
 '이마트24 강남도곡점',
 'CU 매봉산점',
 '세븐일레븐 매봉점',
 '세븐일레븐 도곡본점',
 'GS25 도곡매봉점',
 '세븐일레븐 도곡시네마점',
 '세븐일레븐 매봉역점',
 'GS25 S매봉역점',
 '세븐일레븐 도곡2호점',
 '세븐일레븐 강남도곡점',
 '세븐일레븐 양재시장점',
 'GS25 도곡도서관점',
 '해피타임 CVS도곡점',
 'IGA 익스프레스 양재남부점',
 'CU 도곡대원점',
 'CU 양재오피스점',
 '세븐일레븐 양재11호점',
 'GS25 양재프랜드점',
 '세븐일레븐 양재10호점',
 '세븐일레븐 양재경원점',
 'CU 도곡벚꽃길점',
 '세븐일레븐 양재이스타빌점',
 '세븐일레븐 서초노블레스점',
 'GS25 S양재역2호점',
 'GS25 양재타운점',
 '세븐일레븐 양재역점',
 '뉴타임25편의점 양재역점',
 'GS25 역삼타운점',
 '세븐일레븐 역삼18호점',
 'CU 역삼푸르지오점',
 'CU 역삼로즈점',
 '세븐일레븐 역삼래미안점',
 '세븐일레븐 역삼22호점',
 'GS25 삼성봉은점',
 'CU 강남로얄점',
 'GS25 서울라마다점',
 '세븐일레븐 삼성8호점',
 '세븐일레븐 삼성10호점',
 '이마트24 삼성119점',
 'CU 삼성로점',
 'GS25 삼성본점',
 'GS25 강남은성점',
 'GS25 삼성제일점',
 'CU 삼성햇살점',
 'GS25 삼성그린점',
 'GS25 삼성중앙점',
 '이마트24 강남리테일점',
 'CU HD오천주유소점',
 'CU 삼성한우리점',
 'GS25 S9삼성중앙역점',
 'GS25 삼성선릉점',
 '세븐일레븐 삼성예술점',
 '이마트24 R스타필드코엑스몰6호점',
 'GS25 삼성영진점',
 'GS25 오크우드점',
 '아셈마트',
 'GS25 코엑스신협점',
 'CU 삼성우주점',
 '씨스페이스 삼성1점',
 '이마트24 삼성래미안점',
 '365PLUS 삼성래미안점',
 '인더라인25H편의점 삼정점',
 'CU 삼성가멸점',
 'GS25 삼성한울점',
 'GS25 삼성센트럴점',
 'GS25 삼성터미널점',
 'GS25 삼성스타점',
 'CU 삼성리저브점',
 '이마트24 위워크선릉2호',
 '플젠24시마트 강남점',
 'CU 청담블루밍점',
 'CU JJ상아점',
 '세븐일레븐 강남청담점',
 'CU 삼성아이파크점',
 '이마트24 코엑스몰1호점',
 '이마트24 스타필드코엑스몰4호점',
 'GS25 무역센타점',
 '이마트24 스타필드코엑스몰2호점',
 '이마트24 스타필드코엑스몰5호점',
 '이마트24 코엑스몰3호점',
 'GS25 봉은사점',
 'GS25 S9봉은사역점',
 '바이앤조이',
 'CU 삼성대웅점',
 'CU 삼성신코점',
 '세븐일레븐 삼성대웅점',
 '이마트24 대웅제약점',
 'CU 청담진흥점',
 'GS25 청담진흥점',
 'GS25 강남청담점',
 'GS25 S청담역점',
 'C라움',
 '이마트24 R선릉아크로텔점',
 'CU 역삼점',
 'GS25 역삼사랑점',
 'GS25 삼성승리점',
 'CU 삼성선능점',
 '세븐일레븐 역삼MG스타점',
 'GS25 선릉넥슨점',
 '세븐일레븐 선릉오성점',
 'CU 선릉제일점',
 '세븐일레븐 코엑스아셈타워점',
 '세븐일레븐 공항타워점',
 '쉼터편의점 코엑스점',
 'CU 삼성현대점',
 '세븐일레븐 세곡리엔점',
 'IGA마트 강남세곡점',
 'GS25 강남드림하이점',
 'CU 세곡지웰점',
 'GS25 보금자리점',
 'CU 수서나산점',
 'CU 수서역점',
 'GS25 수서벤처점',
 '미니스톱 수서벤처점',
 '세븐일레븐 수서효성점',
 '세븐일레븐 수서역사5호점',
 '세븐일레븐 수서사이룩스점',
 'CU 수서한아름점',
 '세븐일레븐 수서역사1호점',
 '세븐일레븐 수서역사3호점',
 '세븐일레븐 수서역사4호점',
 '세븐일레븐 수서역사2호점',
 'CU 강남신동아점',
 'GS25 로데오점',
 'CU 압구정거리점',
 'CU 청담보람점',
 'GS25 청담88점',
 'GS25 청담센터점',
 '이마트24 청담아이어스점',
 '이마트24 강남압구정점',
 '미니스톱 압구정로데오점',
 'GS25 강남로데오점',
 'GS25 신사장터점',
 '미니스톱 압구정5점',
 '미니스톱 압구정가은점',
 'CU 압구정로데오점',
 '미니스톱 프린세스점',
 'CU 강남소망점',
 'GS25 압구정신구점',
 'CU 신사세화점',
 'GS25 신사자생점',
 'GS25 강남신사점',
 'GS25 압구정CGV점',
 'CU 신사신구점',
 'CU 신사현대점',
 'CU 압구정CGV점',
 '미니스톱 압구정스퀘어점',
 '세븐일레븐 리갈펠리스점',
 '세븐일레븐 압구정8호점',
 'GS25 신사성원점',
 'GS25 신사코원점',
 'CU 신사드림점',
 '세븐일레븐 신사5호점',
 'GS25 신사강남점',
 'CU 신사한남점',
 'CU 신사프리미어점',
 'GS25 압구정화인점',
 '세븐일레븐 압구정본점',
 'GS25 신사초롱점',
 '스피드박스',
 'GS25 신사증권점',
 'GS25 압구정유림점',
 'CU 압구정신사점',
 '세븐일레븐 신사한나래점',
 'CU 압구정동호점',
 'CU 신사초원점',
 'IGA마트 압구정역점',
 'CU 잠원크레신점',
 '세븐일레븐 압구정11호점',
 'GS25 신현대점',
 '세븐일레븐 압구정2점',
 'CU 압구정미성점',
 '미니스톱 신사증권점',
 'GS25 압구정역점',
 'CU 신사월드점',
 'GS25 압구정시티점',
 'CU 압구정역점',
 'GS25 신사타운점',
 '세븐일레븐 신사로데오점',
 '세븐일레븐 압구정로데오점',
 '세븐일레븐 압구정12호점',
 '이마트24 위워크 디자이너클럽점',
 '베스트올 압구정로데오점',
 '미니스톱 청담누리점',
 '코오롱웰케어',
 'GS25 역삼싱아점',
 '이마트24 역삼센터점',
 'GS25 역삼우리점',
 'GS25 역삼햇살점',
 'GS25 역삼혜성점',
 'CU 역삼타운점',
 'CU 역삼한서점',
 '세븐일레븐 역삼은석점',
 '세븐일레븐 역삼17호점',
 'GS25 역삼대로점',
 'CU 역삼가화점',
 'CU 역삼경남점',
 'GS25 역삼행복점',
 '이마트24 역삼은성점',
 'CU 역삼건화점',
 'GS25 역삼아람점',
 'CU 역삼형지점',
 '세븐일레븐 역삼세브란스점',
 'GS25 강남YBM점',
 'GS25 강남프리미엄점',
 '미니스톱 강남센터점',
 'GS25 강남본점',
 'CU 역삼시티점',
 'CU M강남역점',
 'CU 역삼강남점',
 'GS25 서초제일점',
 'GS25 강남타운점',
 'GS25 강남시티힐점',
 '이마트24 서초센터점',
 'CU 강남해커스점',
 'GS25 강남메트로점',
 '29CM스토어',
 'GS25 서초프라자점',
 '미니스톱 역삼타워점',
 'GS25 역삼태극점',
 '세븐일레븐 역삼타운점',
 '미니스톱 역삼태극점',
 'GS25 강남쌍용점',
 '세븐일레븐 역삼프레스티점',
 'GS25 강남쉐르빌점',
 '썬마트 역삼본점',
 'GS25 역삼프리미엄점',
 'CU 역삼미래점',
 'GS25 역삼본점',
 'CU 역삼신웅점',
 'GS25 역삼테헤란점',
 '세븐일레븐 역삼코넬점',
 'CU 역삼테헤란점',
 'GS25 역삼프라임점',
 '세븐일레븐 역삼한서점',
 'GS25 지에스타워점',
 '세븐일레븐 르네상스점',
 'GS25 역삼띵동점',
 'GS25 역삼르네상스점',
 '미니스톱 역삼태광점',
 '세븐일레븐 KT강남점',
 'CU 역삼에클라트점',
 'CU 국기원사거리점',
 'GS25 역삼쌍마점',
 'GS25 역삼이담점',
 'GS25 강남N타워점',
 '이마트24 역삼푸르지오점',
 '이마트24 역삼중앙점',
 '이마트24 역삼테헤란점',
 'GS25 역삼캐피탈점',
 'CU 강남세브란스점',
 '이마트24 연세장례식장 강남점',
 '비지에프리테일 대치미래',
 '이마트24 역삼신한점',
 'CU 서초아이파크점',
 'CU 역삼태양점',
 '이마트24 강남더인피닛점',
 'GS25 강남아트점',
 'CU 서초캐슬점',
 'CU 서초다우점',
 'CU 서초유앤아이점',
 'GS25 서초디오빌점',
 'CU 역삼우리점',
 'CU 역삼화랑점',
 '세븐일레븐 역삼스타공원점',
 'GS25 역삼참마을점',
 'GS25 역삼스타점',
 '세븐일레븐 역삼창조점',
 '베스토아',
 'CU 역삼포스틸점',
 'CU 서초도씨에빛점',
 'GS25 역삼효성점',
 'CU 강남승리점',
 'GS25 역삼월드점',
 '세븐일레븐 역삼개나리점',
 'GS25 역삼충현점',
 '이마트24 역삼리테일점',
 'GS25 강남역삼점',
 'GS25 역삼미래점',
 'GS25 강남갤러리점',
 'CU 역삼사랑점',
 '세븐일레븐 역삼스마일점',
 '세븐일레븐 역삼우일점',
 'CU 강남센타점',
 '동양마트거평타운점',
 '세븐일레븐 역삼8호점',
 '세븐일레븐 강남제일점',
 'GS25 강남태양점',
 'CU C놀다가게강남점',
 '세븐일레븐 강남중앙점',
 '미니스톱 국기원점',
 '비지에프리테일 강남밀라노점',
 '미니스톱 역삼충현점',
 'GS25 역삼제스트점',
 'CU 역삼삼부자점',
 '세븐일레븐 강남언주로점',
 '세븐일레븐 역삼발렌타인점',
 'CU 역삼카이로스점',
 '편의점사랑 서초코리아',
 '세븐일레븐',
 'CU 서초현대렉시온점',
 'CU 풍림플러스점',
 'CU 서초프라임점',
 'GS25 역삼지에스점',
 'GS25 지에스강남점',
 '세븐일레븐 역삼한은점',
 'GS25 지에스사랑점',
 'GS25 역삼거북점',
 '세븐일레븐 역삼언주로점',
 'GS25 역삼센트럴점',
 '미니스톱 역삼디오빌점',
 'CU 강남시티점',
 'GS25 강남상록회관점',
 '세븐일레븐 강남선릉점',
 '세븐일레븐 역삼명랑점',
 '이마트24 역삼승리점',
 'GS25 역삼덕원점',
 '세븐일레븐 강남IBC점',
 'CU 역삼진미점',
 'GS25 역삼코디점',
 '세븐일레븐 역삼은탑점',
 'GS25 강남태강점',
 'CU 역삼유토빌점',
 '세븐일레븐 역삼피에스따점',
 '제트프러스원',
 'GS25 지에스본점',
 'CU 역삼하나점',
 'GS25 역삼기쁨점',
 'GS25 역삼쏘도베점',
 '세븐일레븐 역삼하이츠점',
 '세븐일레븐 역삼10호점',
 '희망매점',
 '세븐일레븐 서초바로세움점',
 'GS25 S9신논현역점',
 'GS25 서초효성점',
 '세븐일레븐 서초행복점',
 '미니스톱 서초이즈타워점',
 'GS25 역삼상록점',
 'GS25 역삼아르누보점',
 '미니스톱 역삼성지점',
 '이마트24 위워크마켓 선릉1호',
 'GS25 역삼넥스빌점',
 'CU 큰길타워점',
 'GS25 서초여신점',
 'CU 역삼디오빌점',
 'CU 역삼성보점',
 'L마트',
 'CU 율현중앙점',
 'GS25 강남유블레스점',
 'GS25 강남에이스타워점',
 '미니스톱 자곡신영점',
 'CU 자곡현대점',
 '포유25',
 'GS25 강남세곡점',
 'GS25 일원대청점',
 'CU 일원마루공원점',
 '세븐일레븐 일원미래점',
 'CU 강남일원점',
 'GS25 일원센타점',
 'CU 일원다솜점',
 'GS25 일원스타점',
 'CU 강남행복점',
 '미니스톱 일원본점',
 'GS25 일원으뜸점',
 'CU 미가마트점',
 '마트24시',
 '세븐일레븐 강남일원점',
 '세븐일레븐 S3일원역점',
 'CU 개포루체하임점',
 '미니스톱 대청역점',
 'CU 일원한솔점',
 'GS25 세곡래미안점',
 'CU 강남남명학사점',
 '이마트24 청담본점',
 'GS25 청담미래점',
 'CU 청담오션점',
 'GS25 청담본점',
 'GS25 청담중앙점',
 'GS25 청담빌리지점',
 '이마트24 청담하나점',
 'CU 청담경원점',
 '세븐일레븐 청담황해점',
 'GS25 청담사거리점',
 'CU 청담삼환점',
 '세븐일레븐 청담7호점',
 'GS25 청담타운점',
 'GS25 청담우리본점',
 'CU 청담강변점',
 '이마트24 청담휴먼스타빌점',
 'GS25 청담여신점',
 '이마트24 청담에이스점',
 'CU 청담영동점',
 'CU 청담1동점',
 'GS25 청담골프존점',
 'GS25 청담칼릭스점',
 'GS25 R서울강남4점',
 'GS25 R서울구북4점',
 'CU 청담노아점',
 'CU 청담청아점',
 'GS25 삼성메디슨점',
 'CU 대치점',
 'GS25 대치삼성점',
 '세븐일레븐 대치11호점',
 'GS25 코스모타워점',
 '세븐일레븐 대치코스모점',
 '세븐일레븐 대치동일점',
 '세븐일레븐 청담대우점',
 'CU 청담엘점',
 'CU 청담현대점',
 '세븐일레븐 청담그린점',
 'CU 청담자이점',
 'GS25 청담삼익점',
 '이마트24 영동대로점',
 '이마트24 청담리테일점',
 'GS25 청담자이점',
 'CU 강남청담점',
 '세븐일레븐 청담튼튼병원점',
 '세븐일레븐 청담루나점',
 '케이스토어',
 'CU 고덕에이스점',
 'GS25 고덕리엔점',
 '세븐일레븐 고덕리앤파크점',
 '25마트',
 'GS25 고덕샘터점',
 'GS25 고덕점',
 'CU 고덕동남점',
 'GS25 고덕파크점',
 '세븐일레븐 고덕광문점',
 '365PLUS 강동고덕점',
 'CU 강동그라시움점',
 'GS25 그라시움샘터점',
 'CU 고덕2단지점',
 'CU 고덕래미안점',
 'GS25 고덕아르테온점',
 'GS25 고덕그라시움점',
 'CU 그라시움점',
 'GS25 길동우성점',
 'GS25 우성스타점',
 'GS25 길동타운점',
 'CU 길동우성점',
 'CU 강동천중로점',
 'CU 길동엘리트점',
 'GS25 길동하나점',
 '세븐일레븐 길동복조리점',
 '세븐일레븐 천호5호점',
 '세븐일레븐 길동으뜸점',
 '웨이스탑편의점 길동점',
 '이마트24 길동오네뜨점',
 'GS25 길동우림점',
 'GS25 강동스마일점',
 '이마트24 길동으뜸점',
 'GS25 길동삼익점',
 'CU 강동오네뜨점',
 '세븐일레븐 길동본점',
 '세븐일레븐 길동무궁화점',
 '세븐일레븐 명일삼익점',
 'GS25 길동미래점',
 'CU 길동미소점',
 'GS25 길동하이브점',
 'GS25 강동세무서점',
 'CU 길동마루점',
 '이마트24 길동호가점',
 '이마트24 길동제일점',
 '세븐일레븐 길동스위트점',
 '세븐일레븐 길동도고점',
 '세븐일레븐 S길동역점',
 '풍기인삼농협 하나로미니',
 '베스트올 길동2호점',
 '포유',
 'GS25 둔촌동안점',
 '세븐일레븐 길동제일점',
 'CU 둔촌점',
 '해피스페이스24 길동점',
 'GS25 길동퍼스트점',
 'CU 강동개나리점',
 '세븐일레븐 강동길동점',
 '세븐일레븐 길동우성점',
 '로그인편의점',
 'CU 굽은다리점',
 'CU 강동해오름점',
 'GS25 길동베네치아점',
 'CU 강동축복점',
 '세븐일레븐 길동4호점',
 '세븐일레븐 길동해그린점',
 '세븐일레븐 길동우성중앙점',
 '세븐일레븐 S굽은다리역점',
 '이마트24 강동자이점',
 '미니스톱 강동천호점',
 'GS25 강동천일점',
 'GS25 강동원일점',
 '이마트24 천호스타점',
 'CU 천호암사점',
 '미니스톱 천호중앙점',
 '세븐일레븐 천호공원점',
 'GS25 천호하이츠점',
 'CU 강동천일점',
 'CU HD암사주유소점',
 '세븐일레븐 천호로뎀점',
 '365PLUS 천호강변점',
 'GS25 강동리버점',
 '이마트24 R천호벚꽃길점',
 'GS25 강동성심점',
 '이마트24 R강동ECT점',
 'GS25 천호금환점',
 'CU 길동한신점',
 'CU 강동풍차점',
 'CU 길동SK점',
 '미니스톱 길동드림힐점',
 'CU 강동역점',
 '세븐일레븐 길동와이시티점',
 'CU 길동청광점',
 'CU 성내으뜸점',
 'CU 강동하이빌점',
 '세븐일레븐 천호대로점',
 '미니스톱 길동승리점',
 'GS25 천호후레쉬점',
 'CU 강동은성점',
 '세븐일레븐 길동타임점',
 '세븐일레븐 천호삼성점',
 '그린마트',
 '미니스톱 길동현대점',
 '이마트24 강동프라자점',
 'CU HD길동고속주유소점',
 'CU 명일삼익점',
 'GS25 천호은혜점',
 'CU 천호3동점',
 'CU 천호제일점',
 '세븐일레븐 강동구민회관점',
 '세븐일레븐 길동6호점',
 '미니스톱 강동둔촌점',
 'GS25 강동둔촌점',
 'CU 둔촌하이츠점',
 'GS25 둔촌주공점',
 '세븐일레븐 둔촌2호점',
 '이마트24 둔촌수진점',
 'CU 둔촌미소점',
 '이마트24 영릉중앙보훈역점',
 'GS25 둔촌신성점',
 '세븐일레븐 보훈병원입구점',
 'GS25 S9중앙보훈병원역점',
 '세븐일레븐 서울보훈병원점',
 '보훈식당/편의점',
 'GS25 둔촌프라자점',
 'GS25 강동베스트점',
 'GS25 강동성내점',
 '미니스톱 성내승리점',
 'CU 둔촌현대점',
 'GS25 둔촌역점',
 'GS25 강동풍성로점',
 'CU 성내발리점',
 '동원마트',
 '세븐일레븐 강동파밀리에점',
 '세븐일레븐 천호현대점',
 '세븐일레븐 천호사거리점',
 'GS25 천호점',
 'GS25 천호위브점',
 'CU 강동천호대로점',
 '미니스톱 천호현대점',
 'CU 천호로데오점',
 'CU 강동블루점',
 '이마트24 천호태영점',
 'GS25 강동트레벨점',
 'CU 천호푸르지오점',
 'GS25 천호한강점',
 'GS25 성내한일점',
 'GS25 R강동5점',
 'GS25 R강동4점',
 '동양마트천호사거리',
 'CU 명일우량점',
 'GS25 고덕시티점',
 'GS25 명일청솔점',
 'CU 명일스타힐스점',
 '세븐일레븐 강동고덕점',
 '세븐일레븐 명일이마트점',
 '세븐일레븐 고덕역점',
 '세븐일레븐 강동경희대병원점',
 '세븐일레븐 S고덕역점',
 '운강상사',
 'CU 명일상암로점',
 'GS25 명일주공점',
 'CU 명일한영점',
 '씨스페이스 보물섬점',
 '이마트24 R명일역점',
 'CU 명일점',
 'GS25 강동명일역점',
 'GS25 강동펠리스점',
 '미니스톱 명일스타점',
 '세븐일레븐 명일점',
 'CU 강동한솔점',
 '세븐일레븐 S명일역점',
 'GS25 명일타운점',
 'GS25 명일중앙점',
 'GS25 명일점',
 'CU 천호햇살점',
 '세븐일레븐 천호본점',
 'IGA마트 천호일동점',
 '애플마트 천호점',
 'CU 명일명성점',
 '세븐일레븐 명일고명초점',
 'GS25 암사시장점',
 'GS25 암사상암점',
 '미니스톱 암사그랜드점',
 '이마트24 암사역점',
 'GS25 강동암사점',
 'CU 암사상암로점',
 '세븐일레븐 암사희망점',
 '세븐일레븐 천호브라운스톤점',
 'CU 암사중앙점',
 '미니스톱 강동영광점',
 '세븐일레븐 암사햇살점',
 '옐로우25편의점',
 'GS25 천호역점',
 'GS25 강동강변점',
 '세븐일레븐 천호피렌체점',
 '이마트24 천호베네시티점',
 'CU 천호문구거리점',
 '세븐일레븐 천호역점',
 ...]

In [138]:
편의점2 = 편의점[(편의점['장소명'].str.contains('GS25')) | (편의점['장소명'].str.contains('CU'))
                |(편의점['장소명'].str.contains('세븐일레븐')) | (편의점['장소명'].str.contains('이마트24'))
                |(편의점['장소명'].str.contains('미니스톱'))].reset_index(drop=True)
print(편의점2.shape)
편의점2.head()

(488640, 8)

,경도,위도,장소명,도로명,편의시설_경도,편의시설_위도,주거형태,기준
0,127.050895232485,37.4735609971211,GS25 양재구룡점,서울 서초구 논현로5길 18,127.048909,37.472115,단독다가구,37.4735609971211127.050895232485
1,127.050895232485,37.4735609971211,GS25 개포영광점,서울 강남구 논현로4길 12,127.051224,37.472586,단독다가구,37.4735609971211127.050895232485
2,127.050895232485,37.4735609971211,GS25 개포타운점,서울 강남구 논현로12길 13,127.049313,37.474735,단독다가구,37.4735609971211127.050895232485
3,127.050895232485,37.4735609971211,GS25 포이한라점,서울 강남구 논현로4길 43,127.053211,37.474186,단독다가구,37.4735609971211127.050895232485
4,127.050895232485,37.4735609971211,세븐일레븐 양재구룡점,서울 서초구 논현로11길 10,127.047798,37.473806,단독다가구,37.4735609971211127.050895232485

In [139]:
편의점2.groupby(['기준'])['장소명'].count().sort_values(ascending=False)

기준
37.5303479354231126.848181583229        31
37.584474482051704127.03151233348301    30
37.5647509410716127.008243893412        30
37.4851745815704126.89950299655399      30
37.557338440249204126.94384773446899    30
                                        ..
37.5873188797892126.931113607505         1
37.4953829834711126.93852352014099       1
37.4658937393917126.90692275146401       1
37.619320442895126.999987993369          1
37.5570830081005127.015430166623         1
Name: 장소명, Length: 65095, dtype: int64

In [141]:
편의점2[편의점2['기준']=='37.5303479354231126.848181583229']

,경도,위도,장소명,도로명,편의시설_경도,편의시설_위도,주거형태,기준
429577,126.848181583229,37.5303479354231,CU 화곡이슬점,서울 강서구 곰달래로24길 19,126.847241,37.529741,연립,37.5303479354231126.848181583229
429578,126.848181583229,37.5303479354231,CU 화곡사거리점,서울 강서구 곰달래로 123,126.846574,37.530717,연립,37.5303479354231126.848181583229
429579,126.848181583229,37.5303479354231,이마트24 강서까치산점,서울 강서구 강서로10길 19,126.849026,37.530383,연립,37.5303479354231126.848181583229
429580,126.848181583229,37.5303479354231,GS25 화곡행운점,서울 강서구 강서로 47-6,126.846046,37.532072,연립,37.5303479354231126.848181583229
429581,126.848181583229,37.5303479354231,GS25 화곡한나점,서울 강서구 강서로5나길 21,126.847090,37.528411,연립,37.5303479354231126.848181583229
429582,126.848181583229,37.5303479354231,GS25 화곡고가점,서울 강서구 강서로 19,126.847699,37.529619,연립,37.5303479354231126.848181583229
429583,126.848181583229,37.5303479354231,CU 강서스카이점,서울 강서구 강서로5나길 50,126.845698,37.528746,연립,37.5303479354231126.848181583229
429584,126.848181583229,37.5303479354231,CU 까치산시장점,서울 강서구 강서로12길 39,126.849094,37.532129,연립,37.5303479354231126.848181583229
429585,126.848181583229,37.5303479354231,GS25 강서으뜸점,서울 강서구 강서로7길 45,126.845269,37.529295,연립,37.5303479354231126.848181583229
429586,126.848181583229,37.5303479354231,GS25 화곡세화점,서울 강서구 곰달래로25길 8,126.849221,37.531178,연립,37.5303479354231126.848181583229
429587,126.848181583229,37.5303479354231,세븐일레븐 강서화곡점,서울 강서구 곰달래로 111,126.845320,37.530589,연립,37.5303479354231126.848181583229
429588,126.848181583229,37.5303479354231,GS25 강서까치산점,서울 강서구 강서로16길 22,126.847493,37.532877,연립,37.5303479354231126.848181583229
429589,126.848181583229,37.5303479354231,미니스톱 까치산점,서울 강서구 강서로7길 19,126.846712,37.529474,연립,37.5303479354231126.848181583229
429590,126.848181583229,37.5303479354231,CU 화곡행운점,서울 강서구 강서로8길 47,126.850617,37.530088,연립,37.5303479354231126.848181583229
429591,126.848181583229,37.5303479354231,세븐일레븐 S까치산역점,서울 강서구 강서로 지하 54,126.846612,37.531957,연립,37.5303479354231126.848181583229
453240,126.848181583229,37.5303479354231,미니스톱 까치산점,서울 강서구 강서로7길 19,126.846712,37.529474,연립,37.5303479354231126.848181583229
482767,126.848181583229,37.5303479354231,CU 화곡이슬점,서울 강서구 곰달래로24길 19,126.847241,37.529741,오피스텔,37.5303479354231126.848181583229
482768,126.848181583229,37.5303479354231,CU 화곡사거리점,서울 강서구 곰달래로 123,126.846574,37.530717,오피스텔,37.5303479354231126.848181583229
482769,126.848181583229,37.5303479354231,이마트24 강서까치산점,서울 강서구 강서로10길 19,126.849026,37.530383,오피스텔,37.5303479354231126.848181583229
482770,126.848181583229,37.5303479354231,GS25 화곡행운점,서울 강서구 강서로 47-6,126.846046,37.532072,오피스텔,37.5303479354231126.848181583229
482771,126.848181583229,37.5303479354231,GS25 화곡한나점,서울 강서구 강서로5나길 21,126.847090,37.528411,오피스텔,37.5303479354231126.848181583229
482772,126.848181583229,37.5303479354231,GS25 화곡고가점,서울 강서구 강서로 19,126.847699,37.529619,오피스텔,37.5303479354231126.848181583229
482773,126.848181583229,37.5303479354231,CU 강서스카이점,서울 강서구 강서로5나길 50,126.845698,37.528746,오피스텔,37.5303479354231126.848181583229
482774,126.848181583229,37.5303479354231,CU 까치산시장점,서울 강서구 강서로12길 39,126.849094,37.532129,오피스텔,37.5303479354231126.848181583229
482775,126.848181583229,37.5303479354231,GS25 강서으뜸점,서울 강서구 강서로7길 45,126.845269,37.529295,오피스텔,37.5303479354231126.848181583229
482776,126.848181583229,37.5303479354231,GS25 화곡세화점,서울 강서구 곰달래로25길 8,126.849221,37.531178,오피스텔,37.5303479354231126.848181583229
482777,126.848181583229,37.5303479354231,세븐일레븐 강서화곡점,서울 강서구 곰달래로 111,126.845320,37.530589,오피스텔,37.5303479354231126.848181583229
482778,126.848181583229,37.5303479354231,GS25 강서까치산점,서울 강서구 강서로16길 22,126.847493,37.532877,오피스텔,37.5303479354231126.848181583229
482779,126.848181583229,37.5303479354231,미니스톱 까치산점,서울 강서구 강서로7길 19,126.846712,37.529474,오피스텔,37.5303479354231126.848181583229
482780,126.848181583229,37.5303479354231,CU 화곡행운점,서울 강서구 강서로8길 47,126.850617,37.530088,오피스텔,37.5303479354231126.848181583229
482781,126.848181583229,37.5303479354231,세븐일레븐 S까치산역점,서울 강서구 강서로 지하 54,126.846612,37.531957,오피스텔,37.5303479354231126.848181583229

In [142]:
편의점2

,경도,위도,장소명,도로명,편의시설_경도,편의시설_위도,주거형태,기준
0,127.050895232485,37.4735609971211,GS25 양재구룡점,서울 서초구 논현로5길 18,127.048909,37.472115,단독다가구,37.4735609971211127.050895232485
1,127.050895232485,37.4735609971211,GS25 개포영광점,서울 강남구 논현로4길 12,127.051224,37.472586,단독다가구,37.4735609971211127.050895232485
2,127.050895232485,37.4735609971211,GS25 개포타운점,서울 강남구 논현로12길 13,127.049313,37.474735,단독다가구,37.4735609971211127.050895232485
3,127.050895232485,37.4735609971211,GS25 포이한라점,서울 강남구 논현로4길 43,127.053211,37.474186,단독다가구,37.4735609971211127.050895232485
4,127.050895232485,37.4735609971211,세븐일레븐 양재구룡점,서울 서초구 논현로11길 10,127.047798,37.473806,단독다가구,37.4735609971211127.050895232485
...,...,...,...,...,...,...,...,...
488635,127.07854530363599,37.602057932739896,GS25 중화동일점,서울 중랑구 동일로139길 38,127.076799,37.603369,오피스텔,37.602057932739896127.07854530363599
488636,127.07854530363599,37.602057932739896,CU 중랑이화교제일점,서울 중랑구 중랑역로 87,127.077603,37.601213,오피스텔,37.602057932739896127.07854530363599
488637,127.07854530363599,37.602057932739896,GS25 중화제일점,서울 중랑구 동일로129길 16,127.078829,37.599569,오피스텔,37.602057932739896127.07854530363599
488638,127.07854530363599,37.602057932739896,GS25 중화다미소점,서울 중랑구 동일로136길 10,127.080212,37.602186,오피스텔,37.602057932739896127.07854530363599
488639,127.07854530363599,37.602057932739896,GS25 S중화역점,서울 중랑구 동일로 지하 797,127.079461,37.601781,오피스텔,37.602057932739896127.07854530363599

In [143]:
편의점2.to_csv('편의시설/300m내_편의점(중복제거).csv', index=False)